### ISSUE TITLE
Bug report : バグ報告

### ISSUE THREAD

**Issue by project100man** [saturday06/VRM-Addon-for-Blender#10]
**Describe the bug :バグについて**
outlineが出てこない

**To Reproduce:バグの再現方法**
バグが発生する手順を書いてください。
バグが発生するモデルのファイルやそのURL、エラーメッセージを添付してもらえると助かります。

マテリアルに行って、outlineなんとかをいじくってF12押してレンダリングしてるのですが、輪郭線が出ません

**Expected behavior:期待する動作**
どうのようにバグを直してほしいか書いてください。
**Screenshots:スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。
**Desktop (please complete the following information):PC環境情報**
 - OS: [e.g. Win,Mac,ubuntu,Fedora,...]
 - Blender [e.g. 2.80,2.81...]
 - Addon Version [e.g. 076]

**Additional context :なにか他に書いておきたいことはこちらへ**

何か勘違いしてるのですかね？

**Comment by iCyP** [comment]
Blenderのリアルタイムで実現可能な背面法輪郭線はMToonの輪郭線描画と互換性（テクスチャによる線太さの制御）がないためシェーダーやモディファイアによる実装はされていませんので今の所仕様です。
現メンテナのどようび氏に実装案があれば改善されるかもしれません。
該当パラメータはvrmエクスポート時とpreview MToon（実験的機能）によるglsl描画時に利用されます

なおblender上で輪郭線を出すだけなら　https://dskjal.com/blender/edge-detection.html　

が参考になると思います。

MToonのプレビューを希望であれば、MToonのみで構成されたメッシュであれば、それを選択してVRM Helperタブから　preview MToonを押すことで原点近くに輪郭線ありで描画する実験的機能があります。が、非常に重く、またビューポート描画を破壊し、レンダリング結果には出せないので気をつけてください。なお、macではシェーダーエラーが出るのでボタン自体が出ないようになっています。

**Comment by project100man** [comment]
まだ未実装だったのですね、
返信ありがとうございます
