### ISSUE TITLE
Feature request / 要望: template_listを使用したUIに置き換えたい

### ISSUE THREAD

**Issue by FujiSunflower** [saturday06/VRM-Addon-for-Blender#104]
**Is your feature request related to a problem? Please describe. / バグじゃないけどアドオンの動作でなにか困ってることがあれば**
VRM Blend Shape ProxyとVRM Spring BoneのUIが煩雑に感じる。

**Describe the solution you'd like / どう動いてほしいかをどうぞ**
[template_list](https://docs.blender.org/api/3.1/bpy.types.UILayout.html)を使用したUIに置き換えたい。
![image](https://user-images.githubusercontent.com/20571538/161654027-b1c789cd-b210-48d8-ac11-a5c2d29673c7.png)

**Describe alternatives you've considered / 他にこんなんでもいいよ、というのがあれば**
追加ボタンと削除ボタンに差異があると、リストが理解しやすくなるかもしれない。

**Additional context / なんかほかに書きたいことがあれば**
とりあえず0.0版を今年でなんとか仕上げたいですね。

**Comment by saturday06** [comment]
ご指摘ありがとうございます。Spring Boneに関しては仰る通り非常に煩雑かつ縦にUIが伸びてしまっていてつらい感じでした。これは対応します。今年中には間に合うと思います。

Blend Shape Proxyに関してはUniVRM風のUIにした方が、ユーザーがUniVRMと相互移行しやすいという点で良いのかもしれません。こちらはもう少し検討します。

**Comment by FujiSunflower** [comment]
UniVRM風のグリッドUIもtemplate_listを使用すると作れますね。悩ましい部分ではあります。

**Comment by saturday06** [comment]
グリッドのやつUILayout.operatorのボタンを並べるのを想定していました。ご指摘をいただき調べたらtemplate_listを使った方が良さそうな感じでした。ありがとうございます！

**Comment by FujiSunflower** [comment]
#127

**Comment by saturday06** [comment]
全ての一覧編集になりそうなUIをtemplate_listで置き換えました。ご要望ありがとうございました！
