### ISSUE TITLE
Bug report / バグ報告: Missing humanoid hips in some re-exported VRM files

### ISSUE THREAD

**Issue by evshiron** [saturday06/VRM-Addon-for-Blender#105]
**Describe the bug / バグについて**
I am playing with this [avatar](https://hub.vroid.com/characters/2974913185632193937/models/1253656964142098419), and have encountered strange pose in [VRM Viewer](https://vrm-viewer-48655.web.app/).

Other avatars like [this](https://hub.vroid.com/characters/7939147878897061040/models/2292219474373673889) don't have this issue.

I try importing and exporting in Unity with UniVRM, and the exported VRM file doesn't have this issue neither. 

I am new to VRM and can't figure out what's wrong with the steps, so I assume it to be a bug.

**To Reproduce / バグの再現方法**
1. Launch Blender, delete the default cube, and import this VRM file (`a.vrm`)
2. Export as another VRM file (`b.vrm`)
3. Open [VRM Viewer](https://vrm-viewer-48655.web.app/) and load `b.vrm`, and select Pose > ダブルピース
![162491381-c3bd222b-953b-48e9-9cf7-3043d69fdd56.png](https://user-images.githubusercontent.com/8800643/162491381-c3bd222b-953b-48e9-9cf7-3043d69fdd56.png)
The console show that Humaniod Hips can not be found.

**Expected behavior / 期待する動作**
![162491840-32da7eed-996d-4b47-b432-c9cf6c07f39c.png](https://user-images.githubusercontent.com/8800643/162491840-32da7eed-996d-4b47-b432-c9cf6c07f39c.png)
When you repeat step 3 with `a.vrm`, the expected result is shown above.

**Screenshots / スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。

**Desktop (please complete the following information) / PC環境情報**
- OS: Windows 10
- Blender 3.0.0
- Addon Version 2.3.6

**Additional context / なにか他に書いておきたいことはこちらへ**

**Comment by saturday06** [comment]
It is most likely a bug in VRM Viewer. I followed your steps and the Humanoid Hips were exported correctly.

**Comment by evshiron** [comment]
Yep, but when I edited and exported in Unity, the file worked properly in VRM Viewer. There might be some differences I guess.

I am writing a script to diagnosis a bit and will report back later.

**Comment by saturday06** [comment]
I think https://github.com/pixiv/three-vrm/pull/577/files is probably related.

**Comment by evshiron** [comment]
Nice catch! I find that VRM Viewer is using a [very old version](https://github.com/toamariitutu/vrm-viewer/blob/dev/package.json#L81) of `@pixiv/three-vrm`, and when I update to the latest version (which is `0.6.10`), the issue is gone.
