### ISSUE TITLE
展開されたテクスチャーを移動した際のエラーメッセージが不親切なのをどうにかしたい

### ISSUE THREAD

**Issue by saturday06** [saturday06/VRM-Addon-for-Blender#11]
**Is your feature request related to a problem? Please describe.:バグじゃないけどアドオンの動作でなにか困ってることがあれば**

https://knb-mayumi.com/gltferr/
テクスチャーファイルをBlender外で移動したままエクスポートしようとすると「gltfはPNGとJPEGのみの対応です。」というエラーが出るが、エラーの状況を正しく表現はしていないように見える。

**Describe the solution you'd like:どう動いてほしいかをどうぞ**

状況を正しく表現したエラーメッセージに変更する

**Describe alternatives you've considered:他にこんなんでもいいよ、というのがあれば**

**Additional context::なんかほかに書きたいことがあれば**

対応が終わったら上記ブログ記事の人に連絡をすると良さそう

**Comment by saturday06** [comment]
Image.filepathの値からファイルの存在チェックをしようと思ったんですが、びみょうにパスっぽくないんですよね。ソースを見ないといけなそう。

**Comment by iCyP** [comment]
e.g below will return bool
```py
import os, bpy
os.path.exists( bpy.data.materials['body1.001'].node_tree.nodes['Image Texture.002'].image.filepath_from_user())
```
used in 
https://github.com/saturday06/VRM_IMPORTER_for_Blender/blob/185a42e422c66d87de9637afc5d95dd8ed34582b/misc/glb_factory.py#L118-L123

may fix this
https://github.com/saturday06/VRM_IMPORTER_for_Blender/blob/185a42e422c66d87de9637afc5d95dd8ed34582b/misc/vrm_helper.py#L401-L415
like below (not checked)
```py
 for image in used_images: 
     if image.is_dirty or not image.filepath: 
         messages.append( 
             lang_support( 
                 f"{image.name} is not saved. Please save.", 
                 f"{image.name} のBlender上での変更を保存してください。", 
             ) 
         ) 
##########################################
     if not os.path.exists(image.filepath_from_user()):
        messages.append(
                 f"{image.name} is not found. Please load file of it in blender.", 
                 f"{image.name} の画像ファイルが指定ファイルパス上に見つかりません。画像を読み込み直してください。", 
        )
     elif image.file_format.lower() not in ["png", "jpeg"]:
##   ↑↑↑↑  #############################
         messages.append( 
             lang_support( 
                 f"glTF only supports PNG and JPEG textures but {image.name} is {image.file_format}", 
                 f"glTFはPNGとJPEGのみの対応ですが、{image.name}は{image.file_format}です。", 
             ) 
         ) 
```
I apologize for inconvenience. 🙇

**Comment by saturday06** [comment]
Thanks! I couldn't have found `filepath_from_user`. I'll fix it soon.

**Comment by saturday06** [comment]
Fixed.
