### ISSUE TITLE
Feature request / 要望: matcap_vectorノードにノーマルマップの入力を追加したい

### ISSUE THREAD

**Issue by FujiSunflower** [saturday06/VRM-Addon-for-Blender#110]
**Is your feature request related to a problem? Please describe. / バグじゃないけどアドオンの動作でなにか困ってることがあれば**
Blender内部のプレビューでMatcapにノーマップの影響を追加しづらいのを感じました。

**Describe the solution you'd like / どう動いてほしいかをどうぞ**
matcap_vectorノードにノーマルマップの入力を追加したい。
![image](https://user-images.githubusercontent.com/20571538/164330734-58566066-0e8c-429c-9ac3-f5bd95c9c420.png)
![image](https://user-images.githubusercontent.com/20571538/164330972-55e72726-7fa2-46e7-b65d-33fd4927de5f.png)

**Describe alternatives you've considered / 他にこんなんでもいいよ、というのがあれば**
一般ユーザーには自由度のあるノードではなく、設定欄の決まっているパネルで設定出来ても面白いかもしれません。
あるいはノード設定用のオペレーターなどを用意するのも良いかもしれませんね。

**Additional context / なんかほかに書きたいことがあれば**
アドオンだいぶ便利になりましたね。Unityエディタ拡張への恐ろしい対抗馬に感じます。

**Comment by saturday06** [comment]
ありがとうございます！~こちらは休日中には対応できると思います！~ すみませんちょっと考慮事項あるかもです

> 一般ユーザーには自由度のあるノードではなく、設定欄の決まっているパネルで設定出来ても面白いかもしれません。あるいはノード設定用のオペレーターなどを用意するのも良いかもしれませんね。

その方式ならば、MToonは数値の0, 1, 2で表示モード切替している箇所があり、そういうのの操作が現状むつかしいという問題も解決できそうです。考えます。

> アドオンだいぶ便利になりましたね。Unityエディタ拡張への恐ろしい対抗馬に感じます。

ありがとうございます！ちょっとコードを書くのが遅いんじゃないかというコンプレックスがあったんですが、長く続けていればある程度どうにかなるものだとわかりました！

**Comment by saturday06** [comment]
最終的に、MatCapテクスチャの入力にノーマルマップテクスチャの出力を接続するようになりました。ご要望ありがとうございます！
