### ISSUE TITLE
Bug report / バグ報告: custom split normal export is broken. カスタム法線の出力が壊れている

### ISSUE THREAD

**Issue by iCyP** [saturday06/VRM-Addon-for-Blender#114]
**Describe the bug / バグについて**
カスタム法線の出力が壊れている。

**To Reproduce / バグの再現方法**
カスタム法線を持つモデルを出力すると法線がおかしくなっている。

**Screenshots / スクリーンショット**
![before_after](https://user-images.githubusercontent.com/3232308/165521811-0fd3bf46-7377-4baf-b060-c9386aaaceae.png)

**Desktop (please complete the following information) / PC環境情報**
- OS:  Windows11
- Blender:version: 2.93.8, 3.0
- Addon Version :2.3.12

**Additional context / なにか他に書いておきたいことはこちらへ**
bmesh.ops.triangulate はカスタム法線を維持しないようです。
カスタム法線(ex:球法線を転写したモデル)にて下記を実行するとカスタム法線が破損します。
```py
import bmesh,bpy
bm = bmesh.from_edit_mesh(bpy.context.active_object.data)
bmesh.ops.triangulate(bm,faces=bm.faces[:])
bmesh.update_edit_mesh(bpy.context.active_object.data)
```
また、
```
bpy.ops.mesh.quads_convert_to_tris(quad_method='BEAUTY', ngon_method='BEAUTY')

```
はカスタム法線を維持したまま分割できますが、meshオペレーターなので、やり方を変えないといけなくなると思います。
また、手前味噌ですが、先のFB_ngon_encodingブランチ 9099d39 はこの問題を回避できるようです。

既出のissue,失礼しました。いつもお疲れ様です。よろしくお願いいたします。

**Comment by iCyP** [comment]
カスタム法線持ちのvrm export 出来るblendファイルを添付します。(blender3.0
[custom normal suzanne.zip](https://github.com/saturday06/VRM_Addon_for_Blender/files/8572343/custom.normal.suzanne.zip)

**Comment by saturday06** [comment]
ありがとうございます！

FB_ngon_encodingのマージも含めてGW中目標に作業します！

**Comment by saturday06** [comment]
すみません、こちらFB_ngon_encodingコミット  https://github.com/saturday06/VRM_Addon_for_Blender/commit/9099d39887899833d46e5f869d598ad1533970d1 いったんマージさせていただいたのですが、コーナーケースへの対応もやっておきたいため、いったん `tessface_fan()` 内で素朴な三角分割のみ行い、頂点の並べ替えをせずにリターンするようにしました ↓ https://github.com/saturday06/VRM_Addon_for_Blender/blob/2_3_13/io_scene_vrm/exporter/legacy_vrm_exporter.py#L1646

三角分割は bmesh.calc_loop_triangles()を使うと法線が保たれるっぽいのでそれを用いています。シェイプ無しの法線は正しくなるようになりましたが、シェイプキーでの変形時の法線がまだちょっと怪しいので引き続き検証します。

**Comment by saturday06** [comment]
未解決だったシェイプキー法線ですが、どうやらBlenderが自動計算したシェイプキー法線とだいたい同じ出力ができていることは確認できたのですが、どうもその自動計算がMToonと非常に相性が悪いということがわかりました。また、Unityでfbxインポート時に、シェイプキー法線の削除を選ぶのも一般的( https://qiita.com/ApricotLemon/items/221cbd85b8e149e832c0 )のようなので「MToonの場合はデフォルトではシェイプキー法線を出力しない」を実装しました。設定で個別に出力をONにできます

シェイプキー無し
<img src="https://user-images.githubusercontent.com/532872/203988245-f2512a44-d241-4abc-9ded-6fa6c111ff80.png" width="300">

シェイプさせる：Blender自動計算シェイプキー法線
<img src="https://user-images.githubusercontent.com/532872/203988431-fb18bff1-b208-4f19-a502-c397dee7a8b3.png" width="300">

シェイプさせる: シェイプキー法線データを全削除
<img src="https://user-images.githubusercontent.com/532872/203988558-0ec377ff-a9f8-4b7e-9f28-07abcc662bcd.png" width="300">
