### ISSUE TITLE
Feature request / 要望: アーマチュア作成時のボーン組み合わせ計算が遅い

### ISSUE THREAD

**Issue by saturday06** [saturday06/VRM-Addon-for-Blender#115]
**Is your feature request related to a problem? Please describe. / バグじゃないけどアドオンの動作でなにか困ってることがあれば**

glTF読み込みは一瞬で終わるが、その後のボーン組み合わせの再計算が非常に遅い。スプリングボーンを大量に配置しているモデルで顕著

**Describe the solution you'd like / どう動いてほしいかをどうぞ**

glTF読み込みくらいと同程度の速度で他の読み込みをしたい

**Describe alternatives you've considered / 他にこんなんでもいいよ、というのがあれば**

**Additional context / なんかほかに書きたいことがあれば**

**Comment by FujiSunflower** [comment]
[Best Practice](https://docs.blender.org/api/3.1/info_best_practice.html)でたびたび解説される話題ですが、forループではなく[for]の内包表記の方が処理が速い場合がありますね。

**Comment by saturday06** [comment]
こちらはだいぶ改善されたためクローズとします
