### ISSUE TITLE
Feature request / 要望: 追加したシェイプキーをVRMのモーフとして使えるようにしたい

### ISSUE THREAD

**Issue by Bancho29** [saturday06/VRM-Addon-for-Blender#125]
お久しぶりです。

**Is your feature request related to a problem? Please describe. / バグじゃないけどアドオンの動作でなにか困ってることがあれば**

シェイプキーを追加し、更にそれをブレンドシェイプとして登録した後にエクスポートしたVRMモデルですが、

3teneFREE（ https://3tene.com/ ）
まじかる☆ですくとっぷ （ https://booth.pm/ja/items/1271268 ）

では追加したブレンドシェイプが動作しましたが、

Vroid2Pmx 
（公開版 ver1.00.04 https://bowlroll.net/file/267190 
β版 現在 ver 1.01.00_β11 配布場所（要登録）https://com.nicovideo.jp/community/co5387214 ）

でPMX形式に変換した時、公開版では追加したブレンドシェイプの名前がモーフ名として出力されるもののモーフとして変換されておらず、後者では追加したブレンドシェイプ自体変換されませんでした。

（後述の検証用モデルを添えて）Vroid2Pmx の開発者に聞いたところ、
「モーフ情報が全然書き込まれてないので、モーフとしての出力は難しい」
と返答がありました。
（こちらでも「visual studio code」を使って確認しましたが、スクリーンショットの3605行～3630行辺りが追加したブレンドシェイプらしいです…）

また、シェイプキーを使用した後にエクスポートすると、その時点の形状で固定されてエクスポートされます。

余談ですが、Blenderのgltfエクスポーター/インポーターを使用した時は、追加したシェイプキーが動作しました。

**Describe the solution you'd like / どう動いてほしいかをどうぞ**

Blenderで追加したシェイプキーを、VRM形式でもモーフ情報として保持してほしい。

**Additional context / なんかほかに書きたいことがあれば**

検証用データを
https://drive.google.com/drive/folders/1-Ei0qjQA6iLDOJIVZ7wf2qoT16rEue2T?usp=sharing
にアップしました。

VRMモデル：モーフテスト.vrm
（対象ブレンドシェイプ：
　mune_large（胸の巨大化）
　skirt_short（スカート縮小））

jsonデータ：モーフテスト.vrmgltf
（「visual studio code」にVRM/VCI Tools（ https://marketplace.visualstudio.com/items?itemName=fumobox.vtool ）をインストールして出力）

スクリーンショット：スクリーンショット .png

**Comment by saturday06** [comment]
ご提案ありがとうございます！

しかし、「モーフ情報が書き込まれていない」が本当ならば、そもそも3teneFREEやまじかる☆ですくとっぷでもブレンドシェイプは動作しないですし、VRM標準の ~happy~ joyとかのブレンドシェイプも動作しなくなるので、 `モーフテスト.vrm` にはモーフ情報は書き込まれています。

ちなみに `モーフテスト.vrmgltf` にはモーフ情報が含まれていないので、そのあたりでVroid2Pmxの開発者さんとの誤解を生んでいるような気がします。

**Comment by saturday06** [comment]
ブレンドシェイプhappyは標準ではありませんでした。joyに訂正します

**Comment by Bancho29** [comment]
改めてVroid2Pmxの開発者さんにこのスレを踏まえて追加質問しましたが、

> Vroid2Pmxは日本語モーフ名を出力する関係上、VRoid Studioで定められたモーフのみを出力対象としています。

という事でした。

しかしながら、このアドオンでエクスポートしたVRMモデルが正常に出力されている事は了解しました。

> 追伸：
> その後、早速Vroid2Pmxで頂点モーフの出力を実装して頂けました…

最後に、お目汚しすみませんでした。
