### ISSUE TITLE
Feature request / 要望: メッシュとメッシュオブジェクトが混同して使用されている気がする

### ISSUE THREAD

**Issue by FujiSunflower** [saturday06/VRM-Addon-for-Blender#128]
**Is your feature request related to a problem? Please describe. / バグじゃないけどアドオンの動作でなにか困ってることがあれば**
メッシュとメッシュオブジェクトが混同して使用されている気がします。
格納されるプロパティがボーンなら”BONE_DATA”アイコンを設定する変更が #127 の更新にあるのですが、メッシュのアイコンで"MESH_DATA"というよりは"OUTLINER_OB_MESH"を使用した方が良い箇所がありました。

**Describe the solution you'd like / どう動いてほしいかをどうぞ**
Unityでメッシュレンダラー付きのゲームオブジェクト → Blenderでのメッシュオブジェクト
Unityでメッシュレンダラーに格納されているメッシュ → Blenderでのメッシュ
複数のメッシュオブジェクトが同じメッシュをデータとして使用する場合もあります。

**Describe alternatives you've considered / 他にこんなんでもいいよ、というのがあれば**
link_to_objectの仕様変更あるいは廃止

**Additional context / なんかほかに書きたいことがあれば**
link_to_objectがBlendファイルに隠れてしまっているので、BlendファイルからBlendファイルにアペンドした際に急に飛び出てびっくりしました。

**Comment by saturday06** [comment]
link_to_objectの廃止を検討しています。 https://github.com/saturday06/VRM_Addon_for_Blender/issues/86 ←こちらのイシューで作業します。

**Comment by saturday06** [comment]
アイコンのご指摘は助かります。修正致します。

**Comment by saturday06** [comment]
メッシュの件はこちらのリリースで修正しました。
https://github.com/saturday06/VRM_Addon_for_Blender/releases/tag/2_3_23
