### ISSUE TITLE
Bug report / バグ報告: 

### ISSUE THREAD

**Issue by BannedMan** [saturday06/VRM-Addon-for-Blender#129]
** Describe the bug **
Please write what kind of bug is occurring.

**the automatic bones/bone choices never show a bones**

** To Reproduce / How to reproduce a bug **
1. Go to **Vrm addon**
2. Click on**Huminoid**'
3. Scroll down to **automatic bones productions**'
4. See error and **_click any bones_** ** Describe the bug / About bugs **
 **_no bones appear when you select automatic bones_**
Please write what kind of bug is occurring.
**_missing bones being able to be selected_**

** Expected behavior **
Please write how you would like the bug fixed. 
**_I would like to show every single bone, so I could choose the right bones rather than being frustrated because I could not see any bones to choose :(_**
** Screenshots / Screenshots **
![image](https://user-images.githubusercontent.com/94157805/169635203-6c038601-5310-42bc-9c9c-809c5f74cf83.png)

Please attach any screenshots that may be helpful.
** Desktop (please complete the following information) / PC environment information ** Nitro AN5
--OS: [e.g. Windows, macOS, Ubuntu Linux, ...] windows
--Blender [e.g. 2.93.5, 3.1.2, ...] 2.90
--Addon Version [e.g. 2.3.8] 2.3.1

**Additional context / なにか他に書いておきたいことはこちらへ**
**I want to be able to see every single bone to select to assign them to hips and or other things, please**

**Comment by saturday06** [comment]
Hi !

VRM has a parent-child relationship for bones in the specification. The addon only shows a drop-down selection of bones that satisfy the relationship. If the bones you want to set in your hips are not showing, even though they meet the specifications, it may be a bug.

If you feel this is a bug, please send me your .blend file to investigate bug fixes. Thanks!

**Comment by BannedMan** [comment]
OH OK. let me check

**Comment by BannedMan** [comment]
here please look at this https://drive.google.com/file/d/1UqGVhXDRaX5jXeML0amN8-Wr-NAaOlLs/view?usp=sharing

**Comment by saturday06** [comment]
The download is complete. I'll investigate!

**Comment by saturday06** [comment]
OK

Your `hips` will not be `VRM Hips`.

![image](https://user-images.githubusercontent.com/532872/169640321-29c82631-efe0-4c99-84c4-91648117411f.png)

VRM spec says 

https://vrm.dev/en/univrm/humanoid/humanoid_overview#id3
```
(root) - hips - spine - chest - upper chest
              + left upper leg
              + right upper leg
```

Your model is
```
(root) - spine - chest - upper chest
       + hips + left upper leg
              + right upper leg
```

It's not a bug.

**Comment by BannedMan** [comment]
it is? oh I am sorry terrible sorry I'm new to blender

ok thanks, I was confused about this.. thanks for the answer... sorry for wasting your time

**Comment by tdw46** [comment]
> OK
> 
> Your `hips` will not be `VRM Hips`.
> 
> ![image](https://user-images.githubusercontent.com/532872/169640321-29c82631-efe0-4c99-84c4-91648117411f.png)
> 
> VRM spec says
> 
> https://vrm.dev/en/univrm/humanoid/humanoid_overview#id3
> 
> ```
> (root) - hips - spine - chest - upper chest
>               + left upper leg
>               + right upper leg
> ```
> 
> Your model is
> 
> ```
> (root) - spine - chest - upper chest
>        + hips + left upper leg
>               + right upper leg
> ```
> 
> It's not a bug.

@saturday06 I've made sure to follow this bone hierarchy spec in the attached file and still have no hip bone showing up. 
![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/10996763/d230fe46-05b8-46bc-a261-340ae77b16a5)

https://drive.google.com/file/d/1m5-KZmnZegjiKiqt7g4MZ43YFPz3llPU/view?usp=sharing

**Comment by saturday06** [comment]
@tdw46 Has the problem been resolved? I opened your blend file and it appears to have the "Hips" set correctly.

<img width="500" alt="スクリーンショット 2023-08-27 16 01 01" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/24a6323c-467d-44e9-8ce0-2717408f38a1">
