### ISSUE TITLE
Bug report / バグ報告:  How to test Spring bones and colliders?

### ISSUE THREAD

**Issue by 3dcinetv** [saturday06/VRM-Addon-for-Blender#132]
**Describe the bug / バグについて**
_A clear and concise description of what the bug is.
どのようなバグが起きているのか書いてください。_

When I add SPRING BONES, I have no way to test the parameters for spring and
tension.

**To Reproduce / バグの再現方法**
バグが発生する手順を書いてください。
バグが発生するモデルのファイルやそのURL、エラーメッセージを添付してもらえると助かります。

**Expected behavior / 期待する動作**
どうのようにバグを直してほしいか書いてください。
**Screenshots / スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。

**Desktop (please complete the following information) / PC環境情報**
- OS: [e.g. Windows, macOS, Ubuntu Linux, ...]
Windows 10
- Blender [e.g. 2.93.5, 3.1.2, ...]
3.2
- Addon Version [e.g. 2.3.8] 
2.3.26

**Additional context / なにか他に書いておきたいことはこちらへ**

**Comment by 3dcinetv** [comment]
Hello. How do I test spring bones and collision parameters inside Blender using the addon? Do I push "PLAY" in the timeline?

**Comment by saturday06** [comment]
Hi !
Currently there's no functionalities for test spring bones and colliders yet.

**Comment by 3dcinetv** [comment]
Is the "spring bones" from Blender useful to export with the VRM model and edit the "spring bone values" script in Unity?

**Comment by saturday06** [comment]
Yes!

**Comment by saturday06** [comment]
Now we have VRM 1.0 support. When that is done, I will start making a preview of the springborn physics, so please wait.

**Comment by iillya** [comment]
> Now we have VRM 1.0 support. When that is done, I will start making a preview of the springborn physics, so please wait.

Hi! Can you tell me an approximate time  when a preview of the springborn physics will be realized?

**Comment by saturday06** [comment]
I'm working on the [springbone](https://github.com/saturday06/VRM-Addon-for-Blender/tree/springbone) branch but it's more difficult than I thought and is taking a long time.

**Comment by saturday06** [comment]
With the recent release, an experimental animation feature has been implemented.

<img width="300" alt="screenshot" src="https://user-images.githubusercontent.com/532872/229365087-856284bf-2990-4cac-b034-9d9e80e67ea9.png">

https://user-images.githubusercontent.com/532872/229365118-03d6b5c4-0646-48c8-85a1-24e6215bd01d.mp4
