### ISSUE TITLE
Feature request / 要望: VRM 1.0インポートでTemperanceボーン推定を使うかどうするか慎重に検討する

### ISSUE THREAD

**Issue by saturday06** [saturday06/VRM-Addon-for-Blender#137]
**Is your feature request related to a problem? Please describe. / バグじゃないけどアドオンの動作でなにか困ってることがあれば**

VRM 1.0からノードの回転情報が残るのでTemperanceボーン推定がうまく行くかもと思っていたが、 https://github.com/KhronosGroup/glTF-Blender-IO/issues/1662 で、Temperanceも微妙な点があるよねという話になっている。このイシューの議論を読みつつ、ボーン推定をどう行うかを検討する必要がある。

**Describe the solution you'd like / どう動いてほしいかをどうぞ**

**Describe alternatives you've considered / 他にこんなんでもいいよ、というのがあれば**

**Additional context / なんかほかに書きたいことがあれば**

**Comment by FujiSunflower** [comment]
知識共有程度に書いておくと、回転を無視しようとしてBlenderでボーンの長さを0にするとボーンが自動的に消えることがありますね。

**Comment by saturday06** [comment]
共有ありがとうございます。現在はボーン編集時に長さ0にならないように、内部利用のための最小のボーンの長さを定めています。
https://github.com/saturday06/VRM_Addon_for_Blender/blob/2_4_3/io_scene_vrm/editor/make_armature.py#L12

**Comment by saturday06** [comment]
次の仕様になった

- Temeranceボーン推定を行う
- Temperanceボーン推定で軸の交換が行われた場合、関連するコンストレイントの軸も同時に変換する
- コンストレイントの軸を変換する場合、Humanoidボーンの軸がなるべく正しくなるようにする。
- Foot, Eyeボーンのボーン推定ができない場合、正面を向けるようにする
