### ISSUE TITLE
I'm having issues exporting a VRM file

### ISSUE THREAD

**Issue by PrincessNia** [saturday06/VRM-Addon-for-Blender#140]
I created my model in VRoid and exported it.

I imported it into Blender with no issues and made several modifications to the mesh and armature.

I was able to export it without any problems several times, but recently (since I added IK to the arms and legs) it will no longer let me export because it's throwing me an error that required bones aren't assigned.

I've asked around and nobody has any clue how to fix this so I would greatly appreciate your assistance.

I am running Windows 10 64-bit with Blender 3.0.0

![image](https://user-images.githubusercontent.com/16831074/179973214-f835ce1f-a1a9-43e6-9836-5ff4eb8e447b.png)

**Comment by saturday06** [comment]
Please check the bone structure requirement written in the documentation https://vrm.dev/en/univrm/humanoid/humanoid_overview#id3

If the problem persists, please send me the .blend file for verification. If you do not want to make the file public in its entirety, please use twitter DM to https://twitter.com/saturday06 or send email to dyob@lunaport.net .

**Comment by PrincessNia** [comment]
[nyxBlendFile.zip](https://github.com/saturday06/VRM_Addon_for_Blender/files/9169264/nyxBlendFile.zip)

I have enclosed the blend file.

Please have a look at it as I am far beyond a novice when it comes to modifying professional quality models.

I super appreciate your speedy response time and willingness to help.

**Comment by saturday06** [comment]
Thanks!

The armature experiencing the following issues. 
- `Hand_R` must be descendants of `LowerArm_R`, but they are not.
- `Hand_L` must be descendants of `LowerArm_L`, but they are not.
- `Foot_R` must be descendants of `LowerLeg_R`, but they are not.
- `Foot_L` must be descendants of `LowerLeg_L`, but they are not.

Please change the structure of the bone while referring to https://vrm.dev/en/univrm/humanoid/humanoid_overview#id3 .
Also, unfortunately, it does not support parent-child relationships using constraints.

**Comment by PrincessNia** [comment]
Thanks!

and just to confirm. In order to correct this I would just have to re-parent things, right?

**Comment by saturday06** [comment]
> In order to correct this I would just have to re-parent things, right?

Yes!

**Comment by PrincessNia** [comment]
I just want to extend to you a very triumphant "thank you" as the simple act of putting the bones in the right order has fixed, well, everything.

Have a lovely day.
