### ISSUE TITLE
Feature request / 要望: ブレンドシェイプ関連について

### ISSUE THREAD

**Issue by Bancho29** [saturday06/VRM-Addon-for-Blender#144]
**Is your feature request related to a problem? Please describe. / バグじゃないけどアドオンの動作でなにか困ってることがあれば**

VRM_Addon_for_Blenderでブレンドシェイプを新規追加しまくったモデルを制作してますが、VRM_Addon_for_Blender単体だけでは面倒くさい、もしくは出来ない事があり、それらの解決のためにUnityを立ち上げる事も多々あり、出来ればBlender単体で完結できればいいのに…と思いました。

**Describe the solution you'd like / どう動いてほしいかをどうぞ**

(1)ブレンドシェイプの順番を変更できるようにして欲しい

　Blenderのシェイプキーは「アイテムの上下（▲▼ボタン)」で順番を変更出来ますし、UniVRMでもドラッグするだけでブレンドシェイプを変更出来ますが、VRM_Addon_for_Blenderだと作成順で固定される為、

「ブレンドシェイプAとブレンドシェイプCの間にブレンドシェイプBを入れたい」

場合、

「ブレンドシェイプBとブレンドシェイプCの同内容の新ブレンドシェイプを作って、旧ブレンドシェイプB/Cを消す」

という手間が必要なため、最低でもプロパティの「アイテムの上下（▲▼ボタン)」同等の機能を実装してほしい。
（特に、一つのblendファイルで複数のバージョンを生成したい場合、現状「Unityで1体ずつブレンドシェイプの順番を変更する」か「Blenderで上述の面倒くさい方法で変更する」か「諦める」かしかありません…）

(2)ブレンドシェイプのプレビューの実装

　以前のバージョンでは「ブレンドシェイプ＝シェイプキー」だったので確認も楽だったのですが、現行の仕様になってからはVRMを出力してアプリで確認する必要があり、トライ＆エラーがしにくくなっています…

　そこで、「MMD Tools」(現行バージョンは https://github.com/UuuNyaa/blender_mmd_tools )の「バインド」機能（MMDのモーフ(≒ブレンドシェイプ)をBlendeのシェイプキーとドライバーで再現する機能）と同等の機能を実装してほしい。

(3)ブレンドシェイプでのマテリアルの扱い
　こちらは優先度を低くしてもいいので…

　マテリアルの透明度をシェイプで変更する方法（ https://twitter.com/chronus321/status/1093078387592056832 ）をVRM_Addon_for_Blenderで再現する場合、
（上記の方法を行ったVRMモデルをBlenderで読み込んだ結果を元に解析）

1)「Add Material Value Bind」を押す
2)マテリアルを設定する
3)プロパティに「_Color」を入力する
4)「Add value」を4回押して、出来た「Value 0～4」に「0」を入力

で再現しましたが、解りやすくするためにその「Value」の名前を任意に変更できるようにして欲しい。
（また、特定のプロパティを入力したときに、自動的にValueの名前を変更するようなテンプレートも実装してほしい）

（それと、こちらの「「UV Coordinates」と「_MainTex_ST」を利用してテクスチャを切り替える」方法（ https://vtuber-kagurayunon.com/3d/vrm_unity_change2/ ）は再現できませんでした…）

**Additional context / なんかほかに書きたいことがあれば**

今回も要望ばかりでしたが、よろしくお願いします。

**Comment by saturday06** [comment]
ご要望ありがとうございます。今はVRM 1.0対応をしたいのでそれが落ち着いたら見直します。

**Comment by Bancho29** [comment]
了解です。

**Comment by Bancho29** [comment]
これからかなり時間が経ち、その後のバージョンで実装されたので〆ます。
