### ISSUE TITLE
Documentation request: Material Assignment // 資料請求 マテリアルアサインメント

### ISSUE THREAD

**Issue by ZexMaxwell001** [saturday06/VRM-Addon-for-Blender#145]
I would like some extra documentation on how to setup materials on the VRM and how the material could be changed during an expression.

VRMに素材を設定する方法と、表現中に素材を変更する方法について、追加のドキュメントが欲しいです。

**Comment by saturday06** [comment]
I will write during the year-end holidays. Until then, please refer to https://github.com/saturday06/VRM_Addon_for_Blender/issues/107#issuecomment-1100589848

**Comment by saturday06** [comment]
Material documentation is ready.

- https://vrm-addon-for-blender.info/en/material-pbr?locale_redirection
- https://vrm-addon-for-blender.info/en/material-mtoon?locale_redirection
