### ISSUE TITLE
Bug report: is this vrm allowed to edited please check its "otherPermissionUrl" value

### ISSUE THREAD

**Issue by satttayyo** [saturday06/VRM-Addon-for-Blender#149]
When importing .vrm file appears VRM License Confirmation plate how to fix it?

**Comment by kazu0617** [comment]
addon can't detect your model can import, so check permission url in your browser, and check no problem to edit it.
if it's ok to edit it, now you can import that avatar.
if no problem, click [import anyway] and press [OK] to continue import process.

アドオン側ではそのモデルをインポートしていいか判断ができないため、自分のブラウザでそのURLを開いていただき、編集して問題ないかを確認して下さい。もし問題ない場合はインポート可能です。
**問題ない場合のみ** [インポートする] をクリックし、[OK] を押すことでインポートの作業を続行できます。

**Comment by saturday06** [comment]
Thanks for the addition, kazu0617.

There is a hidden feature that allows you to skip the license check by setting the environment variable `BLENDER_VRM_AUTOMATIC_LICENSE_CONFIRMATION` to the string `true`. This add-on is loaded with Blender, an editing tool, and therefore the check is made in terms of "Is the VRM editable?". This is a hidden feature that I didn't really want to implement, but I think there are cases where the license check is inappropriate.

For example, if kazu0617 is working on converting data for NeosVR, I think it might be better to see if the "A person who can perform with this avatar" is appropriate. If you don't mind, it would be very helpful if you could pick up the license information from VRM and call System.Windows.Forms from PowerShell to create a confirmation dialog, which I haven't tried but it seems rather implementable!

Translated with www.DeepL.com/Translator (free version)

---

kazu0617さん、補足ありがとうございます。

隠し機能があり、環境変数 `BLENDER_VRM_AUTOMATIC_LICENSE_CONFIRMATION` に文字列 `true` を設定することでライセンスチェックをスキップすることができます。このアドオンはBlenderという編集ツールでロードするという性質上「そのVRMは編集可能か?」という観点のチェックをしています。本当はこのスキップはあまり実装したくは無かった隠し機能なのですが、しかし、そのライセンスチェックが不適切な場合もあると思います。

例えば、kazu0617さんが取り組まれているNeosVR向けのデータの変換であれば「アバターに人格を与えることの許諾範囲」が適切かをみる方が良い可能性があると私は考えます。もしよければ、VRMからライセンス情報を拾って、PowerShellからSystem.Windows.Formsを呼んで確認ダイアログを作るのとか、試してはないですがわりと実装可能な感じがするので、その辺りを良い感じにしていだだけるととても助かります！

**Comment by kazu0617** [comment]
認知していただきありがとうございます…！

一応saturday06さんから頂いた環境変数を元に、「VRM_Addon_for_Blenderの方のインポートを強制的に実行する」という側面が強いことから「自己の責任の下実行するんですよ」という意味合いを持たせつつ、Batで一通り書いていたことからザクザクと実装しました。
https://github.com/kazu0617/vrmtoglb_autoconvert/pull/16
もし問題があればすぐに取り消す方向で考えていますが、ひとまずは以下の画像の通り進める方針です。

![image](https://user-images.githubusercontent.com/6259214/187077960-57d750a0-1eca-465c-a55b-82bc7135dde2.png)
![image](https://user-images.githubusercontent.com/6259214/187077782-d0551cf4-f360-4bca-90c8-da653be94e65.png)

**Comment by saturday06** [comment]
確認ありがとうございます！私としてはこの内容で問題無いと感じます。
こちらの考えを汲んだ実装を行なっていただいたものだと思います。対応ありがとございました!
