### ISSUE TITLE
Bug report : バグ報告

### ISSUE THREAD

**Issue by Maverynthia** [saturday06/VRM-Addon-for-Blender#15]
**Describe the bug :バグについて**
どのようなバグが起きているのか書いてください。

Material.001 doesn't connect VRM SHADER node group to Material output node in material node tree.

**To Reproduce:バグの再現方法**
バグが発生する手順を書いてください。
バグが発生するモデルのファイルやそのURL、エラーメッセージを添付してもらえると助かります。

Add a material and try to export.

**Expected behavior:期待する動作**
どうのようにバグを直してほしいか書いてください。
**Screenshots:スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。
**Desktop (please complete the following information):PC環境情報**
 - OS: [e.g. Win,Mac,ubuntu,Fedora,...]
 - Blender [e.g. 2.80,2.81...]
 - Addon Version [e.g. 076]

Export without error.

**Additional context :なにか他に書いておきたいことはこちらへ**

The only info I can find is a very LQ material video that I can't view as it's on NicoNico and SUPER LQ. Is there some written documentation? Can the exporter just make the nodes for me?

**Comment by saturday06** [comment]
Currently the plugin requires that the material output surface must connect GLTF or MToon_unversioned or TRANSPARENT_ZWRITE directly. Here is an instruction

![1](https://user-images.githubusercontent.com/532872/102085528-1f6abe00-3e5a-11eb-9f99-1a479dfe9f87.png)

![2](https://user-images.githubusercontent.com/532872/102085536-2265ae80-3e5a-11eb-8751-5e827c3c3575.png)

**Comment by saturday06** [comment]
> The only info I can find is a very LQ material video that I can't view as it's on NicoNico and SUPER LQ. Is there some written documentation? Can the exporter just make the nodes for me?

Currently no. I understand the importance. I'll do it when I can afford my life.

**Comment by saturday06** [comment]
I wrote the material documentation.

- https://vrm-addon-for-blender.info/en/material-mtoon/
- https://vrm-addon-for-blender.info/en/material-pbr/
