### ISSUE TITLE
[CLEARED] Bug about exporting VRM 

### ISSUE THREAD

**Issue by Alzazmon** [saturday06/VRM-Addon-for-Blender#163]
As I was able to solve my problem, I would just like to be able to delete this topic if possible ^^
It was just an error by all my fault

Thank you by advance and sorry for my english ^^'

**Comment by saturday06** [comment]
Hi!
Thanks for your report. It's a bug. The bug has been fixed in the latest version (2.8.1) that was just released. Please give it a try.

**Comment by Alzazmon** [comment]
> Hi! Thanks for your report. It's a bug. The bug has been fixed in the latest version (2.8.1) that was just released. Please give it a try.

Thanks for your answer @saturday06 and i resolve it and it just a problem by myself on some object's corruption ;)
So of course i'll continue to use this version of VRM converter in blender ^^
