### ISSUE TITLE
Feature request: delete hidden edges when import VRM

### ISSUE THREAD

**Issue by modforge2** [saturday06/VRM-Addon-for-Blender#166]
when vrm file import in blender, mesh will be all triganulated(It calls on 'hidden edges' on C4D, idk what calls in blender).
Can you import mesh by quads?

 ＋いいプラグインありがとう！

**Comment by saturday06** [comment]
VRM supports only triangular polygons. So VRM Add-on cannot implement your request. If you are interested in VRM having n-gon (not triangulated polygons) , please join the discussion at https://github.com/KhronosGroup/glTF/pull/1620
