### ISSUE TITLE
How to avoid / fix "Joints on vertex id:{XXX} in:{X} are truncated" during export

### ISSUE THREAD

**Issue by platote** [saturday06/VRM-Addon-for-Blender#167]
**Describe the bug**
When exporting the .vrm from Blender with the addon, I am getting a lot of "Joints on vertex id:{XXX} in:{X} are truncated"

See screenshot below  : 
![image](https://user-images.githubusercontent.com/84842352/201938628-eb069b6e-143c-4dd2-8c41-04622ab9dbed.png)

Can anyone help me: 

1) What does these errors mean ? 
2) How can I avoid these/ fix these ?

Thanks,

**Comment by saturday06** [comment]
A warning is issued if the number of vertex weights is greater than 4. The VRM specification supports more than 4 weights, but [the VRM Consortium reference implementation does not support them](https://github.com/vrm-c/UniVRM/issues/1476), so there is no interoperability.

**Comment by saturday06** [comment]
If there are many requests from users and I have time, I may be able to export more than 4 weights along with sufficient warnings.
