### ISSUE TITLE
Bug report: extract texture images into the folder console error!

### ISSUE THREAD

**Issue by zhump** [saturday06/VRM-Addon-for-Blender#168]
**Describe the bug**
extract texture images into the folder console error!

**Expected behavior**
The model is successfully imported and the texture images can be imported into a separate folder.

**Screenshots**

<img width="835" alt="image" src="https://user-images.githubusercontent.com/7962067/205363390-dd714045-9262-459d-945b-6bac18adb179.png">

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/7962067/205362508-aa71ae42-6a56-4f46-ab55-9671256d55ad.png">

**Desktop (please complete the following information)**
- OS: macOS 11.4
- Blender ：3.3.0 、3.3.1
- Addon Version ：2.3.11

**Comment by saturday06** [comment]
Thanks for your report. It's a bug. The bug has been fixed in the latest version (2.10.4) that was just released. Please give it a try.

**Comment by zhump** [comment]
Already ok, repair was very prompt, thank you
