### ISSUE TITLE
Not compatible with Blender 3.4. Please Upgrade the addon

### ISSUE THREAD

**Issue by rfs5052** [saturday06/VRM-Addon-for-Blender#173]
I'm getting a non compatible error with the new version of the addon (2.11.0), in Blender 3.4.

**Comment by rfs5052** [comment]
For some reason the error went away after I restarted Blender. Not sure what's causing this.

**Comment by madqueensaph** [comment]
I'm having the issue mentioned with the most recent version of VRM Addon (2.14.3) and the current version of Blender (3.4.1); however, I believe my case is an issue stemming from the `io_scene_gltf2` library, which seems to be a core Blender library instead of one covered by this project.

**Comment by Crimson-foxGITHUB** [comment]
Fixed in 2.17.5
