### ISSUE TITLE
Hair Error | [VRM Add-on:Warning] No weight on vertex id:X in: Hair001

### ISSUE THREAD

**Issue by mlocverm** [saturday06/VRM-Addon-for-Blender#174]
I had an error, few points on hair is not moving. I open console and there are lot of hair errors like:
`[VRM Add-on:Warning] No weight on vertex id:X in: Hair001`

This error happens after I changed the clothes textures/skin/image
_Skull mask on head is an Accesories I import from VMagicMirror, not from Blender._

Still quite new on Blender and making vrm models, is there a way to fix this error??

Screenshot from VMagicMirror:
Original:
![vrm hair error blender2](https://user-images.githubusercontent.com/93627850/209629353-8652d22e-6e28-44a7-8368-5d89678bfeb0.jpg)

Edited:
![VRM hair error blender](https://user-images.githubusercontent.com/93627850/209628325-7d2e6084-c639-41a0-89b9-fe08e91f4176.jpg)

**Comment by saturday06** [comment]
I think the SpringBone settings are gone.

Check the "VRM 0.x Spring Bone" panel.
<img width="300" src="https://user-images.githubusercontent.com/532872/209636137-00e3c94e-fb29-41c5-8587-f2b2d239b69c.png">

**Comment by mlocverm** [comment]
I just saw your message and yes that's the problem.
I don't know how to fix it, but I re-import everything and now it is **FIXED** and works good!
Thank you so much for the time and help! ✨ ✨ 

Screenshot:
![vrm hair error blender3](https://user-images.githubusercontent.com/93627850/209664229-2f7c5190-9463-4d2b-9503-11072de8a573.jpg)

**Comment by mlocverm** [comment]
> I think the SpringBone settings are gone.
> 
> Check the "VRM 0.x Spring Bone" panel. <img alt="" width="300" src="https://user-images.githubusercontent.com/532872/209636137-00e3c94e-fb29-41c5-8587-f2b2d239b69c.png">

I just saw your message and yes that's the problem.
I don't know how to fix it, but I re-import everything and now it is **FIXED** and works good!
Thank you so much for the time and help! ✨ ✨ 

Screenshot:
![vrm hair error blender3](https://user-images.githubusercontent.com/93627850/209664555-b72e13d0-f8a6-4e28-bfba-fa6445ef4bfb.jpg)
