### ISSUE TITLE
Feature request: leave my Principled BSDF materials =)

### ISSUE THREAD

**Issue by tapunpuri** [saturday06/VRM-Addon-for-Blender#175]
**Is your feature request related to a problem? Please describe.**
when importing a model, all materials with Principled BSDF are automatically deleted, which was not the case in earlier versions (2_10_3). But I love using Principled BSDF in my models.

**Describe the solution you'd like**
It may be better to make an item in the import window with automatic removal of such materials or not.

**Comment by saturday06** [comment]
The add-on doesn't delete materials with Principled BSDF automatically. If the deletion occurs, it is a bug. I would like you to send me your VRM files for investigation.

**Comment by tapunpuri** [comment]
Sorry. I fixed it the first time and now I couldn't repeat it. False alarm
