### ISSUE TITLE
Bug report : バグ報告

### ISSUE THREAD

**Issue by shadow211** [saturday06/VRM-Addon-for-Blender#18]
**Describe the bug :バグについて**
どのようなバグが起きているのか書いてください。
Cannot export vrm even the validate shows no error.

**To Reproduce:バグの再現方法**
1. Imported a vrm file
2. Add a cube
3. Make cube triangle
4.Assign material on cube
5. Open vrm helper ,and select all, and press "validate  VRM model" button
6.Out put log "No error ,ready for export"
7.select file-export-vrm, name file 456.vrm and click save
8.Few seconds later ,come an error like the attached photo
![QQ截图20201013100352](https://user-images.githubusercontent.com/15362291/95807273-50d0eb80-0d3c-11eb-8781-3ca7b527e13e.png)

バグが発生する手順を書いてください。
バグが発生するモデルのファイルやそのURL、エラーメッセージを添付してもらえると助かります。

**Expected behavior:期待する動作**
どうのようにバグを直してほしいか書いてください。
Successfully exported vrm file.
**Screenshots:スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。
**Desktop (please complete the following information):PC環境情報**
 - OS: [Windows 10 version 1909]
 - Blender [2.83]
 - Addon Version [0.97.0]

**Additional context :なにか他に書いておきたいことはこちらへ**

**Comment by saturday06** [comment]
Currently meshes under armature must have weights. Please add weights to the cube and try again.  Sorry for inconvenience. "validate VRM model" functionalities are incomplete yet. 

`ZeroDivisionError` is wrong error description. I'll fix it.

**Comment by saturday06** [comment]
I modified the code so that ZeroDivisionError does not occur.
