### ISSUE TITLE
Feature request: Export VRM0 From VRM 1.0

### ISSUE THREAD

**Issue by hazre** [saturday06/VRM-Addon-for-Blender#184]
**Is your feature request related to a problem? Please describe.**
Currently you need to maintain two different VRM versions since not every application supports the new VRM 1.0 version. This adds extra work while maintaining VRMs.

**Describe the solution you'd like**
The blender plugin should be able to export to older versions since for the most part it's the same thing without the new features and few adjustments done to VRM1.

On export when the file system window opens, there should be a option to select to export as VRM0 while using VRM1 format in the actual scene.

**Describe alternatives you've considered**
Maintaining multiple blend files with different VRM versions.

**Comment by saturday06** [comment]
You can change VRM version on the VRM panel. You probably don't need to maintain multiple blend files.

<img width="513" alt="スクリーンショット 2023-01-30 035729" src="https://user-images.githubusercontent.com/532872/215349446-6f6f4b8d-8e48-4f82-8214-967f81356beb.png">

Automatic downgrading is very difficult.
