### ISSUE TITLE
Export Vroid base without some bone

### ISSUE THREAD

**Issue by pasunna** [saturday06/VRM-Addon-for-Blender#188]
I want to separate Hair bone from body bone
(to use modular on different character body)
but when I delete body bone and try to export
the add-on don't allow it until it get all body bone
is it possible to make this in current version or in the future?

**Comment by saturday06** [comment]
> is it possible to make this in current version or in the future?

No. The VRM specification doesn't allow missing required bones. The add-on supports exporting only a valid VRM.

If you want to change the spec, please create an issue on the VRM Consortium https://github.com/vrm-c/vrm-specification/issues .
