### ISSUE TITLE
要望: 複数のコンストレイントを有効にする。/Several constraint should be enabled?

### ISSUE THREAD

**Issue by derodero-art** [saturday06/VRM-Addon-for-Blender#191]
**バグじゃないけどアドオンの動作でなにか困ってることがあれば**
VRM1.0のコンストレイントについて、ボーンに複数のコンストレイントがあっても一番上の1つしか認識しない。
前腕のツイストボーンなどを作る際は、通常はトラック＋回転コピーの２つのコンストレイントで作られると思う。
もしかしたら私が一つのコンストレイントで達成する方法を知らないだけかもしれませんが。
I have question abbout how to make twist bone like as forarm since a bone can have only one constraint.
Generarly twist bone is composed track constraint and rotation copy, isn't it.
Maybe just I'm not knowing the way to solve this situation by using only one constraint but.

**どう動いてほしいかをどうぞ**
複数のコンストレイントを有効にして欲しい。
上記の用途を考えれば最低２つ。
At least 2 constraint should be  enable for this kind of case?

**他にこんなんでもいいよ、というのがあれば**

**なんかほかに書きたいことがあれば**

**Comment by saturday06** [comment]
ご要望ありがとうございます。ただ、残念ながら現在のVRM 1.0ではボーンひとつにつきコンストレイントはひとつまでなので、現状のままではBlenderアドオン側では対応ができません。VRMの仕様を決めているVRMコンソーシアムのレポジトリに要望を作成お願いします。こちらです → https://github.com/vrm-c/vrm-specification/issues

**Comment by derodero-art** [comment]
ありがとうございます。VRMにコンストレイントを導入する主な目的として前腕ツイストがあげられていた筈なので、何か方法があるのでしょうね。
Blender側としては普通は2つのコンストレイントを要すると思うのですが、もう少し調べてみます。

**Comment by saturday06** [comment]
既に確認済みかもですが、VRMコンソーシアムのコンストレイント・ツイストサンプルモデルが参考になるかもしれません
https://github.com/vrm-c/vrm-specification/tree/993a90a5bda9025f3d9e2923ad6dea7506f88553/samples/VRM1_Constraint_Twist_Sample
