### ISSUE TITLE
Bug report: Error when I do re-generate rig for blender

### ISSUE THREAD

**Issue by Semo11111** [saturday06/VRM-Addon-for-Blender#194]
When adding a meta rig, the names of the bones appear in the vrm without problems, but when I want to upgrade the bones through the re-granrate-rig button, all the names of the bones disappear and I am not allowed to add them manually. Please help and thanks

https://ibb.co/dLy37Qj
https://ibb.co/6yGXgG9

**Comment by saturday06** [comment]
Unfortunately, the current add-on does not support armatures generated by the "Re-Generate Rig". This is because the armature does not meet VRM's bone structure requirements.
