### ISSUE TITLE
Bug report: Install not showing in addons list

### ISSUE THREAD

**Issue by sunsetroomrain3** [saturday06/VRM-Addon-for-Blender#195]
Hello, the addon is not showing in the addons list after installing the unzipped file through addons then install. I've checked all of the tabs including the testing tab and it is not there. I have also tried various combinations of versions of the addon and blender.
I've tried:
vrm add on version 2.14.6 with blender 3.4
vrm add on version 2.4.5 with blender 3.0
vrm add on version 2.4.5 with blender 2.83.20
The add on does not show in any of these instances

Thank you very much! Your time is appreciated!

**Comment by saturday06** [comment]
Hi!

> after installing the unzipped file

The downloaded add-on file is a zip file, but please do not unzip it, as the unzipped data will not function as an add-on.

**Comment by sunsetroomrain3** [comment]
> 

Ya I tried with zipped file, didn't work, that's what I meant, sorry

**Comment by saturday06** [comment]
OK. The downloaded zip may be corrupted. Please upload the zip file to this issue for investigation.

**Comment by sunsetroomrain3** [comment]
I ended up deleting them, found out I could just rename the file extension to import them in blender and that seems to be working for me for now, thanks though! Appreciate it!
