### ISSUE TITLE
Latest Blender 2.8 - VRM Importer Add-on has Compile error

### ISSUE THREAD

**Issue by wooooooosh** [saturday06/VRM-Addon-for-Blender#2]
Here is the error that shows:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/jasonmerchant/Library/Application Support/Blender/2.80/scripts/addons/VRM_IMPORTER_for_Blender2_8-master/__init__.py", line 14, in <module>
    from .misc import glsl_drawer
  File "/Users/jasonmerchant/Library/Application Support/Blender/2.80/scripts/addons/VRM_IMPORTER_for_Blender2_8-master/misc/glsl_drawer.py", line 132, in <module>
    class glsl_draw_obj():
  File "/Users/jasonmerchant/Library/Application Support/Blender/2.80/scripts/addons/VRM_IMPORTER_for_Blender2_8-master/misc/glsl_drawer.py", line 395, in glsl_draw_obj
    geocode = toon_geometry_shader)
Exception: Shader Compile Error, see console for more details

**Comment by iCyP** [comment]
Sorry for your inconvenience. Shader developing now.
If you need working it, please remove addon once and install from https://github.com/iCyP/VRM_IMPORTER_for_Blender2_8/releases/tag/0.71 

For future development, it would be helpful if you could tell us your environment (OS \ GPU \ blender)．

Thank you.

**Comment by wooooooosh** [comment]
It says it installed, but it does not show up in the blender add on list. (I double checked and it did copy the folder to the correct location for add ons, it's just not being recognized at all after that)

I am on a Mac, blender 2.8, intel gpu

**Comment by iCyP** [comment]
https://developer.apple.com/documentation/macos_release_notes/macos_mojave_10_14_release_notes
OpenGL on Mac is deprecated... Thank you for your report. but I don't have mac, sorry. I will think about answer for it.

Error is meaning it caused by shader compile of opengl when addon initialize with my new add function. But, my Surface Pro4 and Desktop(Geforce1070) don't have any problem.

**Comment by iCyP** [comment]
In haste, I turned off opengl draw function on mac(depends on bpy.app.build_platform == b'Darwin')
Then, I think new version will work on mac without opengl draw function.

**Comment by wooooooosh** [comment]
The mac itself has no problems with OpenGL. I've programmed in both Metal and OpenGL. When they say deprecated, they merely mean that they recommend you program with Metal because of the performance increases, but Apple has done nothing to break OpenGL support.

**Comment by iCyP** [comment]
My answer is already above.
I won't have mac and your environment. So I can't develop for mac and so on. 
If you still have problem about it, please fix it by yourself. You have got the chance of OSS contribution.
Thank you.
