### ISSUE TITLE
Feature request: MToon 1.0 Outlines Preview/Export for New Files

### ISSUE THREAD

**Issue by mattrossman** [saturday06/VRM-Addon-for-Blender#202]
**Is your feature request related to a problem? Please describe.**
When I import a VRM 1.0 character with outlines ([example](https://github.com/vrm-c/vrm-specification/blob/993a90a5bda9025f3d9e2923ad6dea7506f88553/samples/VRM1_Constraint_Twist_Sample/vrm/VRM1_Constraint_Twist_Sample.vrm)), I see that a complex node graph is set up in the Geometry Nodes tab to produce the outline effect. I can then adjust the outline parameters via the corresponding Geometry Nodes modifier entry object's .
<img width="563" alt="image" src="https://user-images.githubusercontent.com/22670878/219719938-b2567eb7-e637-4f7a-85e3-e92580255cfd.png">

However, I don't see a way to reproduce this effect when authoring a new model, and I'm not clear how the exporter expects outline parameters to be set up.

I only see how to add the MToon_unversioned shading node group, and changing those outline parameters doesn't appear to affect the rendered preview.

**Describe the solution you'd like**
I want to be able to add the `VRM Add-on MToon 1.0 Outline Geometry Revision 1` node tree to a new file, similar to how the `MToon_unversioned` tree is available from the shader node editor under "Add > Group".

I'd expect the parameters I choose for this node tree would somehow get synced to the outline parameters for the MToon_unversioned shader and would propagate to the exported VRM.

**Describe alternatives you've considered**
n/a

**Additional context**

https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0#

**Comment by saturday06** [comment]
Hi,

> I want to be able to add the VRM Add-on MToon 1.0 Outline Geometry Revision 1 node tree to a new file,

You can add an outline on the "VRM MToon Material" panel.

<img alt="vrm-outline" src="https://user-images.githubusercontent.com/532872/219822653-97c1c59d-ce40-4182-8942-6fb14c29f53f.png">

**Comment by mattrossman** [comment]
Wow, I had no idea that panel exists.

I am trying it out now, but I can't see the outline taking effect. Is there something else I need to configure?

In this screenshot I seem to have the same settings as you, but I can't see an outline.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/22670878/219824227-4a9fae13-7eda-4a3e-9dd4-a687addc2c9f.png">


My steps are:

* Create a new file
* Add a light
* Add a mesh
* Open materials panel
* Add a new material to mesh
* Scroll down and "Enable VRM Toon Material"
* Change shade color
* Change "Outline Width Mode" to "World Coordinates"
* Increase "Outline Width" value

I am using Blender 3.4.1 and add-on version 2.14.10

**Comment by saturday06** [comment]
Blender 3.4.1 can't preview a mtoon outline because of the bug https://projects.blender.org/blender/blender/issues/103663 . Please use Blender 3.3 LTS or wait for Blender 3.5

**Comment by mattrossman** [comment]
Thank you, I can see the outline using Blender 3.3!

<img width="973" alt="image" src="https://user-images.githubusercontent.com/22670878/219878068-7bfbcf60-9049-4590-a0cc-66eae64faaee.png">

By the way, is this "VRM Material" section of the add-on documented somewhere? I could only find info about the main "VRM" sidebar [on the website](https://vrm-addon-for-blender.info/en/). Without this Issue thread, I wouldn't have known about this workflow for creating MToon materials.

Perhaps a tutorial on the website summarizing the info here would help others. I am willing to contribute an English version.
