### ISSUE TITLE
Bug report: GLTF2 - "metallicFactor" and "roughnessFactor" missing  |  causes shading terminator mismatch in blender vs Unity vs 3js

### ISSUE THREAD

**Issue by tdw46** [saturday06/VRM-Addon-for-Blender#205]
**Describe the bug**
MToon1 materials don't include "metallicFactor" and "roughnessFactor" on export. This seems to play a critical role in shadow terminator offset in other target VRM software. Unity's export with the same VRM files and settings always includes a "metallicFactor" and "roughnessFactor" = 1 on MToon Materials. 

The fallback values of metallicFactor: 0 and roughnessFactor: 0.9 seem to get added to PBR materials, but not MToon.

**To Reproduce**
1. Export any VRM file from blender, and export the same scene from Unity.
2. Visit the online viewer at this URL to see the visible difference in shading in 3js: https://pixiv.github.io/three-vrm/packages/three-vrm-materials-mtoon/examples/loader-plugin.html
4. Examine the JSON of both files at the following URL: https://gltf-inspector.glitch.me/
5. You'll find the only difference is the blender exported version does not contain "metallicFactor" and "roughnessFactor" for MToon Materials.

**Expected behavior**
 "metallicFactor" and "roughnessFactor" should be set to 1 and 1 for MToon Materials, as with the Unity exporter.
**Screenshots**

**Desktop (please complete the following information)**
- OS: Windows
- Blender 3.4
- Addon Version 2.12.0

**Additional context**
I've tried explicitly adding the following lines in a few files in the exporter, but no luck:
`pbr_metallic_roughness_dict["metallicFactor"] = 1.0`
`pbr_metallic_roughness_dict["roughnessFactor"] = 1.0`

Added them in gltf2_addon_vrm_exporter.py, legacy_vrm_exporter.py.

**Comment by tdw46** [comment]
Update: I've modified the exporter to successfully include these JSON PBRMat values, but that still doesn't fix the issue. For some reason my material shadows are inconsistent between blender and other VRM target software

**Comment by tdw46** [comment]
For context, here's my scene in blender:
![image](https://user-images.githubusercontent.com/10996763/221332452-130ccfd8-f184-4c86-b166-dce049dd6f51.png)

And here's my scene in 3js VRM viewer on web. Which matches what I see in unity target applications:
![image](https://user-images.githubusercontent.com/10996763/221332482-9bee8e7b-b368-4938-bcf9-fe19bf9bb805.png)

**Comment by saturday06** [comment]
I think this is due to the different nature of the light source between Blender and the 3js VRM viewer, but it also seems like a bug in the add-on.

Please send me the VRM file exported by the add-on and the VRM file exported by Unity to my email address (dyob@lunaport.net) or twitter DM (https://twitter.com/@saturday06) for investigation.

**Comment by saturday06** [comment]
This bug has been fixed in version 2.14.2 of the addon that I just released. It was caused by  `Additive Shading Shift Texture` not being exported. Thank you for your cooperation.
