### ISSUE TITLE
MToonマテリアルの'Bump Scale'は名称が適切ではないのではないか

### ISSUE THREAD

**Issue by Cj-bc** [saturday06/VRM-Addon-for-Blender#21]
モデリングに関してはとても初心者なので、間違った意見があるかもしれませんがご容赦ください。

---
MToonのマテリアル上では`Bump scale`と書かれたものがありますが、[vrm.devのドキュメント](https://vrm.dev/docs/univrm/shaders/shader_mtoon/)では存在していません。
https://github.com/saturday06/VRM_IMPORTER_for_Blender/blob/d4111b74717acaadbee17379e4b4b2806cb23a2d/vrm_types.py#L304

# Describe the solution you'd like:どう動いてほしいかをどうぞ

ノードを見てみたところ、`Normap map`の`Strength`に繋がれていました。(全ての`Group Input`ノードを見ましたが、ここのみで使われているようでした)
また、vrm.devのドキュメントにも[Normap mapの強さの値](https://vrm.dev/docs/univrm/shaders/shader_mtoon/#normal-map)は存在するようなので、`Normal map scale`などとした方がわかりやすいのではないかなと思いました。
慣習的な呼び方なのかなと思って調べてみたのですが見つけられませんでした...
Initial commitから存在するので、仕様の方の名前が変わったのかもしれないですね

![スクリーンショット 2020-10-23 0 12 00](https://user-images.githubusercontent.com/16875061/96892204-61176200-14c4-11eb-969f-19a2cc3d8218.png)

**Comment by saturday06** [comment]
ご指摘ありがとうございます。vrm.devのドキュメントには無いようですが、MToonのソースには表示名として `Normal Scale` とされているので、それに合わせるか `_BumpScale` のままにするのがとりあえず安全だと思いました。
https://github.com/Santarh/MToon/blob/v3.4/MToon/Resources/Shaders/MToon.shader#L10

ただ、ちょっと互換性の問題があるので、暫くこのままにしておいてタイミングを見計らっていっぺんに変更したい気持ちがあります。

**Comment by Cj-bc** [comment]
なるほど、そちらのソースを把握しておりませんでした...
それであれば、そのままの方が良さそうですね。ユーザーとして内部を見ることもあまりないので...
閉じておきます！
