### ISSUE TITLE
NormalMapTextureのキーは何故_BumpMapなのか

### ISSUE THREAD

**Issue by Cj-bc** [saturday06/VRM-Addon-for-Blender#22]
内部では`_bumpMap`となっているものを、`NomalmapTexture`という表記で表示しているようなのですが、これは何かしら意図があるのでしょうか
initial commitからあるのでiCyPさんに聞かないとわからない気はしますが...仕様変更なのでしょうか...
利用している上では問題がないのですが、後々紛らわしいかなという気がしました。(コードリーディングしていて引っかかりました)
管理上問題がないと判断されるのであれば閉じてしまって構わないです

https://github.com/saturday06/VRM_IMPORTER_for_Blender/blob/d4111b74717acaadbee17379e4b4b2806cb23a2d/vrm_types.py#L335

**Comment by iCyP** [comment]
個人的にbumpmapというとheight mapを連想する事から、法線mapであることを明示することを優先したんだと思います。

**Comment by Cj-bc** [comment]
なるほど、こちらの知識不足でした...
ありがとうございます、閉じておきます
