### ISSUE TITLE
バグ報告: VroidStudio 1.2.xで出力したVRM 1.0モデルでの不具合

### ISSUE THREAD

**Issue by Bancho29** [saturday06/VRM-Addon-for-Blender#221]
VroidStudio 1.2.xよりVRM 1.0出力に対応したので早速試してみましたが、
以下の不具合が見つかりましたので報告します。
## バグについて

1. ブレンドシェイプが無視される
VroidStudio 1.2.2で出力したVRM 1.0モデルをインポートしたところ、（1.0で一新された）ブレンドシェイプが無視される。（モデルのシェイプキー自体は読み込めた）
 **スクリーンショット**
![スクリーンショット (137)](https://user-images.githubusercontent.com/19154759/224213590-1d435aeb-39b4-4411-8b0a-c27d5519ad5b.png)
（1.0で一新された）ブレンドシェイプが無視されている
![スクリーンショット (138)](https://user-images.githubusercontent.com/19154759/224213652-514075ba-e89b-44fa-a34e-3dfc036717ad.png)
モデルのシェイプキー自体は読み込めている

2. エクスポートの不具合
上記のインポートしたモデルをエクスポートした場合、髪が前後逆になった上、モデルの移動に追随しなかったり、最悪読み込めなかったりする。 
こちらの調査だと、新規作成したモデルは（髪の挙動以外は）読み込めたが、サンプルモデル（こちらではBを使用）から出力したモデルは読み込めなかったり、読み込めたとしても正常にポーズが取ることが出来なかった。
当然、無視されたブレンドシェイプはエクスポートされていなかった。
 **スクリーンショット**
![スクリーンショット (139)](https://user-images.githubusercontent.com/19154759/224213929-d424bffd-564f-479a-8be4-653df3bd86b0.png)
VRMViewMeister 2.0.1での出力例1
左：ベースの1.0形式モデル　右：アドオンでインポート→エクスポートしたモデル
髪が前後逆になっている
![スクリーンショット (140)](https://user-images.githubusercontent.com/19154759/224213937-147d7065-cb80-4070-add1-6c70e89220fe.png)
VRMViewMeister 2.0.1での出力例2
髪がモデルの移動に追随しない
![スクリーンショット (142)](https://user-images.githubusercontent.com/19154759/224214313-3d47f131-bc3b-43d9-99bb-971d66d2adda.png)
VMagicMirror v3.0.2での出力例1
ベースモデルでの表示。
目の表示に不具合にあるが、アプリの不具合の模様です。
![スクリーンショット (143)](https://user-images.githubusercontent.com/19154759/224214326-57b74029-430f-4527-be59-820ded4ed6b3.png)
VMagicMirror v3.0.2での出力例2
アドオンでインポート→エクスポートしたモデルでの表示。
VRMViewMeisteで読み込めなかったモデルはこのアプリで読めましたが、もはや実用以前です…
VRMViewMeisteで読み込めたモデルは（上記の問題を除けば）正常に動作しました。

## 期待する動作
VRM 1.0でもVroidStudioがデファクトスタンダードになると思うので、上記の修正お願い致します。

## PC環境情報

- OS:Windows11
- Blender 3.4.1
- VRM-Addon-for-Blender 2.14.17
- VroidStudio 1.2.2
- VRMViewMeister 2.0.1（https://booth.pm/ja/items/3796032）
- VMagicMirror v3.0.2（https://baku-dreameater.booth.pm/items/1272298）

## なにか他に書いておきたいことはこちらへ
また、要望としてVRM0形式のデフォルトのブレンドシェイプをVRM 1.0形式に変換できるようにして欲しい。

**Comment by saturday06** [comment]
報告ありがとうございます。調査します。

**Comment by saturday06** [comment]
取り急ぎ先ほどリリースしたバージョン2.14.18で、VRM 1.0のexpressionが読めない不具合を修正しました。また MToon 1.0とBlender 3.3以上の組み合わせでアウトラインの設定があると、アウトライン表示調整用の一時的なメッシュが追加でエクスポートされてしまう不具合も修正しました。その他の不具合については追って調査します。ご報告ありがとうございました。

**Comment by Bancho29** [comment]
先程2.14.18を使用しましたが、上記の
- expression(旧ブレンドシェイプ)のインポートの不具合
- インポート→エクスポートしたモデルの読み込みの不具合

が修正されていました。

早速の修正ありがとうございました。
