### ISSUE TITLE
Feature Request: Spring bones - Wiggle bones addon to fork in Blender 3.6+? 

### ISSUE THREAD

**Issue by 3dcinetv** [saturday06/VRM-Addon-for-Blender#225]
_## Is your feature request related to a problem?_
Spring bones in the VRM addon could work if we fork the Wiggle Bones addon to be adapted to the parameters
(and export variables) to write the VRM spring script for VRM  exported models using Blender.

For almost 3 years, we've been expecting a function to make spring bones work in Blender. Spring bones are the only thing that keep me fiddling with Unity, otherwise, I'd use the VRM-Addon-for-Blender only. But we don't have spring bones

_## Describe the solution you'd like_
Fork the Wiggle Addon to write the Spring Bone script accepted by the VRM format.
https://github.com/shteeve3d/blender-wiggle-2

_A clear and concise description of what you want to happen._
The "Spring parameters" of the VRM export script to make a compatible VRM spring-bone script to export with the model
could be based on the Wiggle addon for Blender. The user just have to "push play" in the timeline to see the spring bone work.

_## Describe alternatives you've considered_
I've been using Unity VRM export exclusively because of the collider and spring bone scripts. Nothing else. Everything else
I can do and setup in Blender.

_## Additional context_

There's only 1 issue with the Wiggle Bone addon for the VRM Spring Bones script fork, that I am proposing:
If you open the .py script you'll read at the end, all of the notes that are stopping further development of the wiggle addon and this includes the ability to export a baked simulation of the wiggle bones. This might be an issue when the "compatible VRM Spring bone and Collision scripts" are exported within the VRM model from Blender.

**Comment by saturday06** [comment]
Thanks for the request. I am trying to build a Spring Bone implementation from scratch on the [springbone](https://github.com/saturday06/VRM-Addon-for-Blender/tree/springbone) branch. If I find it impossible with my programming skills, I will adopt your suggestion.

**Comment by saturday06** [comment]
See also
https://github.com/saturday06/VRM-Addon-for-Blender/issues/132#issuecomment-1493383030
