### ISSUE TITLE
要望: ボーン名の短縮後の親子関係について

### ISSUE THREAD

**Issue by nira-yusan** [saturday06/VRM-Addon-for-Blender#231]
## バグじゃないけどアドオンの動作でなにか困ってることがあれば
X軸ミラーを使えるようにするために「ボーン名を短くする」を使ったのですが、ミラーはできるようになりましたがボーンにメッシュがついてきません………調べたところ親子関係がなくなってると見たのですが………

## どう動いてほしいかをどうぞ
「ボーン名を短くする」を使ってもメッシュがボーンに追従するようにしてほしいです！

## 他にこんなんでもいいよ、というのがあれば
よければ、VRMをインポートした時点でX軸ミラーを使えるようにしてほしいです！

**Comment by saturday06** [comment]
報告ありがとうございます！

すみませんが、私の手元環境では正しく動作していて現象の確認がとれないため、お使いのOSとBlenderのバージョンを教えていただきたいです。

私の手元環境では「ボーン名を短くする」を実行してもボーンにメッシュはついてきます。確認してみた動画を貼り付けます。

https://user-images.githubusercontent.com/532872/230694693-d468d783-dd2b-4173-ba72-9037ee00ebef.mp4

また、メッシュとボーンの親子関係にも変化がないです。

私の手元環境は次の通りです
- Windows 11
- Blender 3.3.5

**Comment by nira-yusan** [comment]
Blender3.0.0
MacOS

環境はこの内容です

**Comment by saturday06** [comment]
ありがとうございます。macOSのCPUはIntelでしょうか？M1, M2系でしょうか？

**Comment by nira-yusan** [comment]
機体はMacBookAirM1です

**Comment by saturday06** [comment]
確認ありがとうございます。調査してみます。

**Comment by nira-yusan** [comment]
そういえば、旧バージョンでは「ConvertVRM(うろ覚えです………)」みたいなのが書かれたボタンですぐにXミラーが使えるといったことをいくつかの記事で見たのですが、それってどうなっているのでしょうか？

**Comment by saturday06** [comment]
ConvertVRMというのは見たことないので、別のツールかもです。いちおう、その件が掲載されている記事を貼っていただけますでしょうか？（私の方で探しても良いけど、ご指摘の記事と同一かどうかは自信がない）

**Comment by nira-yusan** [comment]
https://aozoranositade.ape.jp/vroid%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AEblender%E3%83%9C%E3%83%BC%E3%83%B3x%E3%83%9F%E3%83%A9%E3%83%BC%E5%AF%BE%E8%B1%A1%E5%8C%96%E3%81%AE%E6%9A%AB%E5%AE%9A%E7%9A%84%E6%96%B9%E6%B3%95/

**Comment by saturday06** [comment]
それでしたか。その機能に日本語訳をあてて「VRoidのボーンを短くする」という名前のボタンにした、というのが現在の状況です。

**Comment by saturday06** [comment]
原因見つけました。このBlenderのバグのようです。Windowsでも発生していました。
https://projects.blender.org/blender/blender/issues/93892

以降のバージョンで修正されているので、Blenderのバージョンアップで対処お願いします。バージョンアップ先は3.5最新版でも良いですが、3.3系の最新版が安定しているのでおすすめです。

**Comment by nira-yusan** [comment]
なるほど………そうだったんですね。今回の要望を出す前にツイッターで調べてたんですけど、その変化に気づいてない人がいくつかいました。自分としても、それだけだと第一印象でボーン名を短くするだけのもの、と思ったのでボタンの名前を少し変えてみてはどうでしょうか？

**Comment by nira-yusan** [comment]
ありがとうございます

**Comment by saturday06** [comment]
おすすめの名前はありますでしょうか？

**Comment by nira-yusan** [comment]
そうですね………ボーンの最適化、なんてどうでしょう？X軸ミラーの有効化やボーン名の短縮をしているので

**Comment by nira-yusan** [comment]
ただ、名前変えるだけじゃちょっと足りないので、X軸ミラーは使いたい人多いのでそのあたりはなにかしらの説明があったほうがいいかもです。

**Comment by saturday06** [comment]
VRoid限定機能のため「VRoidのボーンの最適化」とはなると思います。ただ、最適化という語は語義が広いので悩ましいところです。もうすこし考えてみますね。

**Comment by saturday06** [comment]
ご提案ありがとうございました！

**Comment by nira-yusan** [comment]
こちらこそ、ボタン名の変更提案を受け入れていただき、ありがとうございます！

**Comment by saturday06** [comment]
いろいろ考えたんですが、X軸ミラーをしたい人が使う機能だと思ったため「VRoidのボーン名をX軸対称化」にしてバージョン2.15.21で反映しました。ご提案ありがとうございました。
