### ISSUE TITLE
要望: Animated materials (image sequences) support

### ISSUE THREAD

**Issue by NaughtDZ** [saturday06/VRM-Addon-for-Blender#249]
https://www.youtube.com/watch?v=uMP4DHENKyg&t=3s
This effect is achieved in the instructional video using the UnitySDK to do, in fact, the principle should be a play image sequence of materials?

**Comment by saturday06** [comment]
That is a feature that exists only in VSeeFace; if you want to add such a feature to VRM, please propose it to the VRM Consortium ( https://github.com/vrm-c/vrm-specification/issues )
