### ISSUE TITLE
Bug report: Mesh becomes split after VRM import

### ISSUE THREAD

**Issue by comdost** [saturday06/VRM-Addon-for-Blender#250]
Bug:
Hi! I have a bug. The faces of the mesh become unwelded during VRM import.
Here is an example.

https://imgur.com/a/lLQ0XUV

I am not sure if this an issue with the VRM addon or Blender itself.
However I cannot seem to replicate it with other kind of imports (fbx, gltf)

To Reproduce
1. Import model
2. The model will have split the mesh into islands
3. This happens consistently with every VRM model (vroid, original model, etc)
4. The more times a VRM is imported and exported, the more split it becomes

I use windows 10, Blender 3.4.1, latest VRM addon extension.

Temp Fix:
Thankfully the model can be repaired easily by selecting all the verts, then (Merge vertices -> By Distance)

However it becomes very time consuming managing many models at once!

**Comment by saturday06** [comment]
Thanks for your report.

Maybe it's a bug, but it didn't happen on several models including vroid models in my Windows 10, Blender 3.4.1 environment. This add-on is frequently upgraded. Therefore, please download and install the latest version of the add-on again and try the operation again.

If not resolved, please send me the VRM file to my email address ([dyob@lunaport.net](mailto:dyob@lunaport.net)) or twitter DM (https://twitter.com/@saturday06) for investigation.

**Comment by saturday06** [comment]
Be sure to restart Blender when upgrading the add-on.
