### ISSUE TITLE
Bug report: VRM 1.0 Custom Expressions can't rename

### ISSUE THREAD

**Issue by B4TT3RY** [saturday06/VRM-Addon-for-Blender#252]
## To Reproduce

1. Select vrm version to `VRM 1.0`
1. Go to `Expressions`
2. Click on `Add Custom Expression`

## Expected behavior

i want rename expression

## Screenshots

![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/12368101/cc12cd68-89cb-4697-99cc-90eb1fc48193)

## Desktop (please complete the following information)

- OS: [e.g. Windows, macOS, Ubuntu Linux, ...] Windows 10
- Blender [e.g. 2.93.5, 3.1.2, ...] 3.5
- Addon Version [e.g. 2.4.7, 2.3.8, ...] 2.16.0

**Comment by saturday06** [comment]
Thanks for reporting!

The bug has been fixed in the latest version (2.16.1) I just released. Please try it.
