### ISSUE TITLE
Feature request: Detecting Collider for lower halve of the model

### ISSUE THREAD

**Issue by Nickdnr** [saturday06/VRM-Addon-for-Blender#254]
## Is your feature request related to a problem? Please describe

Right now there's only collider for Upper half of the model. when importing in Unity with vrm importer plugin from the same .vrm there appears to have all the bone which this plugin didn't do

## Describe the solution you'd like

Is it possible to have the plugin to import lower halves of the collider

## Describe alternatives you've considered

right now I'm thinking of maybe exporting from Maya( vrm import to Maya then export to Fbx and to be open in Blender )

**Comment by saturday06** [comment]
Thanks for the report. It is probably a bug. Please share the following screenshots for investigation.

- Blender, with the bottom half of the collider missing
- Unity, with all colliders present

**Comment by Nickdnr** [comment]
![Screenshot 2023-06-12 113744](https://github.com/saturday06/VRM-Addon-for-Blender/assets/136070055/36ca6785-3ff7-4a8c-9025-29c7d1fe8150)
Blender
___

![Screenshot 2023-06-12 112410](https://github.com/saturday06/VRM-Addon-for-Blender/assets/136070055/cf6fe8fb-e509-43b3-b1dd-392ed1a8f3bc)
Unity
___

These two models were originally imported from VROID

**Comment by saturday06** [comment]
I tried importing a VRoid 3D model and the lower body colliders seem to read correctly.

(VRod Studio 1.22.1 + Avatar Sample B + VRM 0.0)

<img width="600" alt="vroid_b0" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/29137d82-3df0-43e3-8a6e-fbb5aa239a7c">

**Comment by saturday06** [comment]
If not resolved, perhaps some bug is the situation that occurs only in your 3D model. If possible, please send me the VRM file to my email address (dyob@lunaport.net) or twitter DM (https://twitter.com/@saturday06) for investigation.
