### ISSUE TITLE
バグ報告:ダウンロードできません。よろしくお願いいたします。 

### ISSUE THREAD

**Issue by Tanukichi7333** [saturday06/VRM-Addon-for-Blender#255]
## バグについて

どのようなバグが起きているのか書いてください。

## バグの再現方法

バグが発生する手順を書いてください。
バグが発生するモデルのファイルやそのURL、エラーメッセージを添付してもらえると助かります。

## 期待する動作

どうのようにバグを直してほしいか書いてください。

## スクリーンショット

何か参考になりそうなスクショがあれば添付してください。

## PC環境情報

- OS: [Windows, macOS, Ubuntu Linux, ...]
- Blenderのバージョン [2.93.5, 3.1.2, ...]
- アドオンのバージョン [2.4.7, 2.3.8, ...]

**Comment by Tanukichi7333** [comment]
404エラーになります。ダウンロードできません。よろしくお願いいたします。

**Comment by saturday06** [comment]
すみません、リリース作業をミスってデータを削除してしまっていました。すぐに復旧します

**Comment by saturday06** [comment]
@Tanukichi7333 こちら復旧し、ダウンロードできるようになりました。お騒がせしました。

**Comment by Tanukichi7333** [comment]
ご対応ありがとうございます！
早速使わせていただきます！


2023年6月11日(日) 16:23 saturday06 ***@***.***>:
