### ISSUE TITLE
Feature request: Grouping of the toon shader.

### ISSUE THREAD

**Issue by etwodev** [saturday06/VRM-Addon-for-Blender#258]
## Is your feature request related to a problem? Please describe

On previous versions of this VRM-addon, the toon shader was a group, and this group was not only easy to edit and adjust, it was part of all the VRM model materials. However, after recently updating and importing my VRM model, I have to change each and every material individually if I want to replace it with a Principled BDSF, Transparent, etc... for aesthetic purposes in my renders. Not sure if this is a bug, or an intentional change? 

## Describe the solution you'd like

Grouping the toon shader, so the textures can be used with other shaders / the toon shader can be easily customised

## Describe alternatives you've considered

Using an older version of this plugin

**Comment by saturday06** [comment]
It is an intentional change.

**Comment by saturday06** [comment]
Grouping is useful and I will do it eventually. I'm trying to figure out what to do.

**Comment by saturday06** [comment]
In the latest version, I have reintroduced node groups!
