### ISSUE TITLE
バグ報告: VRM1のExpressionのオペレーター"Remove Texture Transform Bind"を使用するとエラーが出て実行できない

### ISSUE THREAD

**Issue by Yulit-c** [saturday06/VRM-Addon-for-Blender#268]
## バグについて

VRMのExpression用のオペレーター"vrm.remove_vrm1_expression_texture_transform_bind"を使用するとエラーになり
Texture Transfor Bindを削除できない｡

## バグの再現方法

1. 編集するVRMのバージョンを1.0にして任意のExpressionに"Add Texture Transform Bind"でTexture Transform Bindを追加する｡
2. 任意のTexture Transform Bindに設けられた"Remove Texture Transform Bind"を実行する
3. `addons\VRM_Addon_for_Blender\editor\vrm1\ops.py", line 499, in execute
    expressions = armature.vrm_addon_extension.vrm1.expressions
AttributeError: 'VrmAddonObjectExtensionPropertyGroup' object has no attribute 'vrm1'`
とコンソールにエラーが出力され､Texture Transform Bindを削除することが出来ない

## 期待する動作
`expressions = armature.vrm_addon_extension.vrm1.expressions`
となっていてArmature DataではなくArmature Objectを参照してしまっているようなので､
`expressions = armature.data.vrm_addon_extension.vrm1.expressions`
が正しいように思えます｡

## PC環境情報

- OS: Windows11
- Blenderのバージョン 3.6.0
- アドオンのバージョン 2.17.2

**Comment by saturday06** [comment]
バグ報告ありがとうございます！

いただいた報告をもとに修正したバージョン ( https://github.com/saturday06/VRM-Addon-for-Blender/releases/tag/2_17_3 ) を先ほどリリースいたしました！ぜひお試しください
