### ISSUE TITLE
要望: VRM1のExpressionsでMaterial Color BindのTarget Valueを定義しているFloatVectorPropertyのサブタイプをColorにすると便利ではないかと思いました

### ISSUE THREAD

**Issue by Yulit-c** [saturday06/VRM-Addon-for-Blender#272]
## バグじゃないけどアドオンの動作でなにか困ってることがあれば
`VRM1`の`Expressions`に`Material Color Bind`を設定する際､現行の仕様ですとUI上の`Target Value`の表示がデフォルト状態の設定になっており色を定義するのが難しいと感じました｡
![default](https://github.com/saturday06/VRM-Addon-for-Blender/assets/18331487/1179ecf7-d8ec-4e57-a31d-25f8b10bd674)

## どう動いてほしいかをどうぞ
Target Valueのサブタイプを変更してプロパティが色の表示になれば､パラメーター設定をしやすくなると思いました｡
![before](https://github.com/saturday06/VRM-Addon-for-Blender/assets/18331487/15350171-e1e5-4e34-b0ad-dfafd4e36c25)

## なんかほかに書きたいことがあれば
サブタイプを変更するのみだとラベルとプロパティが縦に並んでしまい､他のプロパティの表示と
整合性がとれない気がしたため､
rowのサブレイアウトを設けてTarget Valueを配置した方が､より見やすい表示になるのではないかと思いました｡
![after](https://github.com/saturday06/VRM-Addon-for-Blender/assets/18331487/618e38ae-8a2c-4d4c-89b6-819b7c6d58d5)

**Comment by saturday06** [comment]
ありがとうございます。
ご提案のとおり、サブタイプを色にする、また入力欄を横に並べる方針で実装を検討します。

**Comment by saturday06** [comment]
https://github.com/saturday06/VRM-Addon-for-Blender/releases/tag/2_17_4 にてリリースされました。ぜひお試しください。

**Comment by Yulit-c** [comment]
リクエストを聞いていただきありがとうございます m(_ _)m
