### ISSUE TITLE
Bug report: MToon Appears Black on New Version

### ISSUE THREAD

**Issue by Nickdnr** [saturday06/VRM-Addon-for-Blender#278]
Hi, Reporting a bug on the MToon shader on the new version

Currently the MToon Doesn't work and Model appear as black as [Screenshot (1)]
![Screenshot 2023-07-18 140937](https://github.com/saturday06/VRM-Addon-for-Blender/assets/136070055/7d2abab9-a3a5-4d84-83dd-a04e0df8b8f3)

from what I have suspect it might be that there is no Material Output Node at the end [Screenshot (2)]
![Screenshot 2023-07-18 141220](https://github.com/saturday06/VRM-Addon-for-Blender/assets/136070055/97e3157d-7626-4b73-a240-76f0ab35cfe9)

I have been using the Addon in version 2.16 and the shader works fine

**Comment by saturday06** [comment]
Thanks for reporting!

MToon seems to work fine in my Windows11+Blender3.6.0 environment. Please let us know your OS and Blender version so we can investigate.

Also, there is a tutorial on how to use MToon, so check it out https://vrm-addon-for-blender.info/en/material-mtoon/

**Comment by Nickdnr** [comment]
The shader seems to work great! I just have to manually plug it in MToon, sorry for the misunderstanding. it's just that the older version it plugs the surface automatically and the outline appears just fine, I just have to figure out how the outline works

Edit: After testing a bit, I open 2 Blender at the same time and now it works properly! I have no idea how it happened. now every node is assigned automatically and correctly (Vroid Model)
