### ISSUE TITLE
Bug report: Thumb Bones Assigning

### ISSUE THREAD

**Issue by Nickdnr** [saturday06/VRM-Addon-for-Blender#279]
## Describe the bug

When remapping the armature's thumb's bone on "VRM Optional Bones" it doesn't let you, instead it uses [Thumb1] again for the second slot where [Thumb2] should be as example in the [Screenshot(1)]

so the slot would shown as Thumb1,Thumb1,Thumb3 where it should be Thumb1,Thumb2,Thumb3 like other fingers
this problem happens on both sides L Thumb / R Thumb

## Screenshots

![Screenshot 2023-07-18 145244](https://github.com/saturday06/VRM-Addon-for-Blender/assets/136070055/223f7ae8-59bb-4acf-8b39-bbbebd8276ca)

## Additional context

I tried on multiple models, vroid mainly and the other one created myself but the problem remain the same even in different bones name.
the model is port straight out of Vroid, the other one I tested is a model which the bone was made from blender

this results in model that couldn't move their thumb properly

**Comment by saturday06** [comment]
Thanks for your bug reporting. This bug has been fixed in the latest version I just released. Please try it out https://github.com/saturday06/VRM-Addon-for-Blender/releases/tag/2_17_6

**Comment by Nickdnr** [comment]
Thank you so much! the VRM 1.0 has been fixed and it works great, although VRM 0.0 still have the same problem

**Comment by Nickdnr** [comment]
After some testing and exporting in VRM 1.0 and going back to VRM 0.0 everything seems to be working properly now. Thank you!
