### ISSUE TITLE
Bug report: fbx cannot automatically configure the blend shape proxy after the vrm node is exported

### ISSUE THREAD

**Issue by spencer17x** [saturday06/VRM-Addon-for-Blender#281]
## Describe the bug

When I export fbx to vrm format, the vrm blend shape proxy is empty

## To Reproduce

1. import .fbx file
2. export .vrm file

## Expected behavior

Fill in blend shape proxy automatically

## Desktop (please complete the following information)

- OS: macOS
- Blender: 3.6.1
- Addon Version: 2.17.7

**Comment by saturday06** [comment]
The add-on doesn't fill in blend shape proxy automatically for .fbx because .fbx doesn't contain a blend shape proxy. This is not a bug.

It may be possible to automatically create a blend shape proxy from VRChat or MMD shape keys.

**Comment by spencer17x** [comment]
> The add-on doesn't fill in blend shape proxy automatically for .fbx because .fbx doesn't contain a blend shape proxy. This is not a bug.
> 
> It may be possible to automatically create a blend shape proxy from VRChat or MMD shape keys.

Can you provide some tutorials?Thanks. I don't know much about this, is it manual or automatic, is it in blender.

**Comment by spencer17x** [comment]
So.fbx suffix file can not export blend shape?
<img width="295" alt="image" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/32794413/0c3afc75-4a58-4cfd-8dc2-6d6b04580e1f">
Are these shape keys useless?

**Comment by spencer17x** [comment]
Is there a way to convert to vrm format, automatically generate a blend shape proxy according to shape keys

**Comment by saturday06** [comment]
VRM Blend Shape Proxy is not a shape key. VRM Blend Shape Proxy is a mapping to find shape keys based on the type of character's facial expression.

Python can be used to automatically set this up, but no tutorial currently exists.

<img width="406" alt="スクリーンショット 2023-07-31 042311 - コピー" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/6e9eb7f7-3827-4705-8f67-1634272d15a8">

**Comment by spencer17x** [comment]
Is there any relevant plug-in?

**Comment by saturday06** [comment]
I don't know.
