### ISSUE TITLE
Bug report: Whether to export the vrm model with animation

### ISSUE THREAD

**Issue by spencer17x** [saturday06/VRM-Addon-for-Blender#285]
## Describe the bug

The exported vrm does not have animation

## To Reproduce

1. Import glb models with animations
2. Exporting the vrm Model

## Expected behavior

vrm model with animation

## Desktop (please complete the following information)

- OS: macOS
- Blender：3.6.1
- Addon Version：2.17.7

**Comment by saturday06** [comment]
Exporting VRM 1.0 will include animation.
![221404322-266648e9-e7f8-40b9-869c-7cb9a1c4a600](https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/4a6c053c-a708-4cd2-a48a-c051eea61834)

**Comment by saturday06** [comment]
VRM 0.0 does not export animations because it is not compatible with glTF.

**Comment by spencer17x** [comment]
Is this a vrm problem or a plug-in problem?

**Comment by saturday06** [comment]
This is a VRM 0.0 problem. Please use VRM 1.0

**Comment by spencer17x** [comment]
So you're saying that VRM-0.x is not compatible with glTF animation？

**Comment by saturday06** [comment]
Yes. I think

**Comment by saturday06** [comment]
VRM 0.0 does not allow for scaling or rotation of glTF nodes. glTF animations do scale and rotate nodes.

It is unclear if that restriction applies to glTF animations, but it appears that the VRM Consortium does not want to do any further specification maintenance on VRM 0.0.
