### ISSUE TITLE
Bug report: Joints on vertex id:# in: mesh are truncated

### ISSUE THREAD

**Issue by GearType** [saturday06/VRM-Addon-for-Blender#289]
## Describe the bug

I am not sure if this qualifies as a bug, but I do not know where else to find understanding or resolution. 

When exporting a rigged mesh from blender using vrm, I see the error "Joints on vertex id:649 in: mesh.obj are truncated" . This error occurs for several different vertex ids. 

## To Reproduce

1. import model in blender
2. Create armature
3. Bind armature and model
4. set meta data and bone heirarchy info
5. export model as vrm (using vrm 0)

## Expected behavior

export without warnings

## Desktop (please complete the following information)

- OS: Windows 11
- Blender 3.6.1

**Comment by saturday06** [comment]
A warning is issued if the number of vertex weights is greater than 4. The VRM specification supports more than 4 weights, but [the VRM Consortium reference implementation does not support them](https://github.com/vrm-c/UniVRM/issues/1476), so there is no interoperability.
