### ISSUE TITLE
Bug/Request export from Blender to 3tene

### ISSUE THREAD

**Issue by Frinyi** [saturday06/VRM-Addon-for-Blender#29]
**Describe the bug :バグについて**
I'm not sure if this is a exportation bug or it's just that it's not compatible with 3tene or whatever, that's why it might be a request as well.

The VRM exportation looks good except for some vertices being in strange positions when imported to 3tene, I'll add some screenshots.

In the captures you can see that in Blender, the arms bend just fine, but when I import it to 3tene, the vertices of the shoulders break and I've tried many things to fix it but nothing works. I used a base model and edited it in blender, and the original model looks good in 3tene, but the edited version doesn't.

I just want to know if this can be fixed or if there's anything I can do to fix this manually.

どのようなバグが起きているのか書いてください。

**To Reproduce:バグの再現方法**
1. Export your character to VRM
2. Import it to 3tene
3. Some vertices look bad on 3tene
バグが発生する手順を書いてください。
バグが発生するモデルのファイルやそのURL、エラーメッセージを添付してもらえると助かります。

**Expected behavior:期待する動作**
I expected it to look like it does in Blender, smooth and with vertices in their places. Eveything else works fine, the expressions, the physics, etc. Maybe the clothes are sometimes wrong but that's ok because I want this model to be seen only from the chest to the head.
どうのようにバグを直してほしいか書いてください。
**Screenshots:スクリーンショット**
![Blenderfine](https://user-images.githubusercontent.com/74723030/99685741-36003e00-2a83-11eb-87d4-422e043a3610.PNG)
(Edited model looks good on blender)
![3Tenewrong](https://user-images.githubusercontent.com/74723030/99685804-41536980-2a83-11eb-818d-e6ab284759ce.PNG)
(Edited model from blender looks bad on 3tene)
![3TeneOriginalRight](https://user-images.githubusercontent.com/74723030/99685809-43b5c380-2a83-11eb-9a6a-388f63a2bff0.PNG)
(Original model looks fine on 3tene)
何か参考になりそうなスクショがあれば添付してください。
**Desktop (please complete the following information):PC環境情報**
 - OS: Windows 10
 - Blender 2.9.0.0
 - Addon Version Latest

**Additional context :なにか他に書いておきたいことはこちらへ**

**Comment by saturday06** [comment]
I fixed vertex transformation bug in https://github.com/saturday06/VRM_IMPORTER_for_Blender/commit/563592585e73789ef00267f2beb104ea476f6e1e yesterday. Please install latest addon and check your bug is fixed or existing yet. If your bug exists, please send me `.blend` file to investigate.

**Comment by EatThePath** [comment]
I can report that I had the exact same issue that the reporter had, and updating my copy of the plugin fixed it marvelously.
