### ISSUE TITLE
VRM 1.0 models not colliding at feet

### ISSUE THREAD

**Issue by GearType** [saturday06/VRM-Addon-for-Blender#290]
When I export models using VRM0 spec, the models correctly land on their feet in game spaces (such as onhyper.io) when I import them online. When I use VRM1 spec, the models fall through the floor to approximately their midpoints (can only see torso and above). Not sure how to correct.

- OS: Windows 11
- Blender 3.6.1
- Addon Version latest avaiable 8/8/2023

**Comment by saturday06** [comment]
I think there is currently a fault in hyperfy.io's VRM 1.0 support, [the official VRM 1.0 model from the VRM Consortium](https://github.com/vrm-c/vrm-specification/blob/master/samples/Seed-san/vrm/Seed-san.vrm) is not showing up correctly either.

Please contact hyperfy.io.

## Expected screenshot:
<img width="500" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/f34239f4-43c1-4673-a274-2f769c777cd6">

## hyperfy.io screenshot in August 27, 2023:
<img width="500" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/f601cba0-49a2-4b29-b72e-129d746c541c">
