### ISSUE TITLE
Bug report: UDIM runtime error on export

### ISSUE THREAD

**Issue by sinfulgurotesque** [saturday06/VRM-Addon-for-Blender#294]
## Describe the bug
When trying to export a model to .vrm, the export fails with the following runtime error:

> RuntimeError: Error: When saving a tiled image, the path 'C:\Users\Kelsey\AppData\Local\Temp\tmp_fwjdu8e\img' must contain a valid UDIM marker
> Error: Image 'Possum.UDIM.001' could not be saved to 'C:\Users\Kelsey\AppData\Local\Temp\tmp_fwjdu8e/img'

## To Reproduce

1. In UV Editing, under the Image tab, Create New Image. Check the 'Tiled' checkbox.
2. In Image sidebar, go to Image tab and make sure the source is set to UDIM Tiles.
3. In the Material Properties tab of the mesh, make sure the MainTexture is connected with your UDIM texture.
4. Attempt to export as .vrm.
5. See error.

## Desktop (please complete the following information)

- OS: Windows
- Blender 3.3.1
- Addon Version 2.17.7

## Additional context

Note that the UDIM files are appropriately named and run in blender just fine - they also export to any native file format with no issue.

**Comment by saturday06** [comment]
UDIM is currently not supported. Because the glTF add-on does not support it. VRM is an extended format of glTF.

For more information, please refer to the glTF add-on issue.
https://github.com/KhronosGroup/glTF-Blender-IO/issues/1663
