### ISSUE TITLE
Leg bone rotation axis off by 45 degrees

### ISSUE THREAD

**Issue by wooooooosh** [saturday06/VRM-Addon-for-Blender#3]
The 4 leg bone rotation axis are wrong.

I double checked to compare them to the Unity importer, so I know it' s just the vrm to blender importer.

**Comment by iCyP** [comment]
I can't understand what you say.
Please show me about difference of you expected and current by images and so on.

**Comment by iCyP** [comment]
If you say about bone local axis, it is technical specifications. 
VRM(gltf) gives only joint position, so vrm importer presumes bone tail position (it makes bone local axis) by bone childlen positions.

Thanks.
