### ISSUE TITLE
FBXでエクスポートすると、、、

### ISSUE THREAD

**Issue by project100man** [saturday06/VRM-Addon-for-Blender#30]
テクスチャが吐き出されずに真っ白になっちゃうんですけど、どうやって対処したら良いんでしょうか？

**Comment by fire** [comment]
You have to create a MTOON material in the Blender shader graph.

Translated from DeepL. I do not speak Japanese.

> BlenderのシェーダグラフにMTOONマテリアルを作成しなければなりません。
>
> DeepL から翻訳しました。日本語は話せません。

**Comment by project100man** [comment]
thanks!!!
