### ISSUE TITLE
Bug report: Issue assigning bones

### ISSUE THREAD

**Issue by Gioooo2004** [saturday06/VRM-Addon-for-Blender#302]
Hello, I'm attempting to assign the required bones to my armature but for some reason it won't let me select the bones, there's just no options on any of them. Any idea why this is happening? Not sure if it's a bug or just my ignorance. Thanks!

![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/144067516/15be2db3-3f0f-4a9c-9a46-c0fd42d5b7fb)

**Comment by saturday06** [comment]
Hi !

VRM has a parent-child relationship for bones in the specification. The addon only shows a drop-down selection of bones that satisfy the relationship.

Please see VRM specification: https://vrm.dev/en/univrm/humanoid/humanoid_overview#id3

If it doesn't work,  for investigation please attach a screenshot like below

<img width="314" alt="スクリーンショット 2023-09-05 21 51 42" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/c906eeb8-e1b2-415c-9ac3-62ebefdd2f60">

**Comment by saturday06** [comment]
I think it is not a bug, but an issue caused by the bone structure.

It will be closed if there is no additional information for 3 months.
