### ISSUE TITLE
要望: インポートしたオブジェクトの回転値が逆になっているのを直せないでしょうか？

### ISSUE THREAD

**Issue by Rio514** [saturday06/VRM-Addon-for-Blender#325]
## バグじゃないけどアドオンの動作でなにか困ってることがあれば
初めまして。いつもVRM-Addon-for-Blenderをありがたく使用させていただいております。

モデリングは勉強中、プログラミングの知識は皆無なので的外れなことを言ってしまっていたら申し訳ありません。

要望ですが、こちらのアドオンを使用してVRMモデルを読み込むと回転値が逆(180度真後ろ)になっているようで、
それが原因でシェイプキーを左右分割するアドオン（LazyShapekeys）を使用すると分割が逆になってしまう現象をもし可能でしたら解消していただきたいです。

## どう動いてほしいかをどうぞ
こちらを希望している理由としては、VRoidモデルの表情をBlenderで編集したあとにアドオンを使用してラクに表情の左右分割を行いたいためです。
現状ではVRMモデルを読み込み、例えば目閉じシェイプキーをアドオンで左右分割すると目閉じ.Rが左目の目閉じ、目閉じ.Lが右目の目閉じになってしまうという状態です。

無知で申し訳ないのですが、もし回転が入っていることに理由があるのでしたらすみません…！

## なんかほかに書きたいことがあれば
使用しているBlenderは3.6.2LTS、VRM-Addon-for-Blenderは2.20.5、LazyShapekeysは1.0.56です。
もし足りない情報がございましたらすみません…！

お忙しいなか申し訳ございませんが、ご検討をよろしくお願いいたします…！

**Comment by saturday06** [comment]
ご報告ありがとうございます。

VRMとBlenderの座標軸は違うので、Blenderへのインポート時にそれを合わせるために回転が行われます。VRMアドオンはその回転をBlender公式のglTFインポート機能を使って行っています。そのため、インポート時にモデルの向いている方向が怪しいという場合は、Blender公式のほうにイシューを立てるのをお願いします → https://github.com/KhronosGroup/glTF-Blender-IO/issues

ただ、mmd_tools ( https://github.com/UuuNyaa/blender_mmd_tools ) でMMDのファイルをBlenderに読んだ場合もモデルはVRMをインポートした場合と同じ方向を向いているので、そこまでおかしい変換では無いと思っています。

LazyShapekeysは持ってないので未確認ですが、LazyShapekeysのドキュメントにMMDモデルが掲載されていますが、特に左右逆になるとかの注意書きも無いので、これは仕様として手動でL/Rの名前を変更するというのが想定されているか、あるいはLazyShapekeys自身に左右反転で命名をする機能が存在しているのかもしれないと思いました。

**Comment by Rio514** [comment]
返信ありがとうございます！

座標軸を合わせるために回転を行っていたのですね…！
一応モデルの読み込み後に適用→回転を適用することでLazyShapekeysが正しく左右分割されるようになるので、そちらで対応しようと思います。
回転を適用すると動きがおかしくなる可能性があるのであれば、今まで通りLazyShapekeysで分割→LとRが逆なのを手動でリネームします。

改めまして、ご回答いただきありがとうございました！
