### ISSUE TITLE
VRM1.0で出力したモデルの視点操作に不具合が起きる件

### ISSUE THREAD

**Issue by teresayawn** [saturday06/VRM-Addon-for-Blender#329]
## どのようなバグが起きているのか書いてください。
VRM1.0モデルをで出力した場合、モデルの水平方向の視点操作ができなくなり、カメラ目線も機能しなくなる。
（0.xモデルでは上記不具合は起きません）

## バグの再現方法
Blender（3.6.4）にVRM-Addon-for-Blender(2.20.7)をインストールし、Vroid studio（1.23.2）で出力した
v1.0モデルのファイルを読み込ませ、VRMファイルを再出力させると上記不具合が起きます。
Blender内で何か操作することに関係なく、単純にv1.0のVRMファイルの読み込みと書き出しをするだけで生じます。

## バグが発生するモデルのファイルやそのURL、エラーメッセージを添付してもらえると助かります。
Unityで確認すると、J_Adj_L_FaceEyeおよびJ_Adj_R_FaceEyeのテールが下向きになっていました。
Blenderでバグが発生たファイルを再度読み込むと、当該ボーンは正面を向いており、正常のように見えます。
　応急処置として、Blenderのボーン編集モードで、2つのボーンのテールを上向き（ワールドz軸方向）に
してから出力させると、ボーンのテールは、ほぼ正面を向くので、例えば、VRM posing desktopなどの
アプリ上での視点操作やカメラ目線は正常に機能するようになります。しかし、このファイルを再度
Blenderに読み込ませ、上記応急操作をせずに出力すると、また視点操作の不具合が再発します。

## 期待する動作

どうのようにバグを直してほしいか書いてください。
視点操作において、ver0.xと同じような出力結果を希望します。

## スクリーンショット

何か参考になりそうなスクショがあれば添付してください。

## PC環境情報

- OS: [Windows, macOS, Ubuntu Linux, ]
- Windous10
- Blenderのバージョン [2.93.5, 3.1.2, ...]
- 3.6.4
- アドオンのバージョン [2.4.7, 2.3.8, ...]
- 2.20.7

## なにか他に書いておきたいことはこちらへ
Vroid studio側に問題が潜んでいる可能性も排除できないので
その可能性があれば、VRoid事務局にも報告したいと思います。

**Comment by saturday06** [comment]
ご報告ありがとうございます。この問題は非常に難しい問題のため、継続して改善中です。過去にもご報告あったのでリンクを貼ります https://github.com/saturday06/VRM-Addon-for-Blender/issues/227

直接の原因は、お使いの視点操作ソフトウェアが、VRMの視点操作に未対応なのだと思います。調査のため、どのような視点操作ソフトをお使いか教えていただけますでしょうか？

--------- 以下状況を解説します ---------
> VRMの視点の操作をするためには、VRM0の場合はVRM Lookatコンポーネント、VRM1の場合はVRMInstanceコンポーネントの機能を使って操作する必要があります。これは、VRMの下記の仕様をカバーするするためです。
> 
> - ブレンドシェイプによる視点操作と、ボーン回転による視点操作の切り替えができる。
> - VRM 1.0のボーン回転の場合は、ボーンのデフォルトの回転値はどんな値でも良い。
>
> お使いの視点操作ソフトウェアはそれらのコンポーネントを使わず、直接ボーンの回転を操作しているのかなと思っています。それを行うと、今回と同様の事象が発生します。VRM posing desktopで正常なのは、VRM posing desktopはVRMの視点操作に対応しているからだと思います。また、VRMをUnity上のVRM未対応ソフトウェアで再生する場合は、一度何らかの変換ソフトウェアを噛ませる必要がありそうです。
>
> おそらくVRChatかなと想像しています。VRChatはUnity 2019だったのでVRM 0.0からの持ち込みしかできなかったところ、VRChat Open BetaでUnity 2022に対応し、VRM 1.0からの持ち込みがベータ版で可能になったことで問題が顕在化します。
>

**Comment by saturday06** [comment]
また、BlenderのVRMアドオンでは、子供の無いeyeボーンを上に向けてエクスポートしたとしても、再度インポートすると正面を向いてしまうという問題があります。

この問題が解決するまでの一時的対応として、eyeボーンに子ボーンを追加し、その子ボーンはeyeボーンの上に配置することで、eyeボーンの向きを上向きに固定する方法があります。エンドボーン、終端ボーンなどと呼ばれる手法です。

Blender 4.0の機能を使うことでこの問題が完全解決できそうなので、大変申し訳ないのですがこちらの手法で一時的対応をお願いします。

--------- 以下状況を解説します ---------
> VRMには「ボーンの向き」という概念が存在しません。しかしBlenderにはボーンの向きという概念が存在するので、ボーンの向きを自動的に推定する必要があります。ボーンに子ボーンがある場合はその子ボーンの方向を向ければ(*1)良いのですが、子ボーンが無いボーンが向いている方向を決めることができません。その場合はどうにか方向をでっちあげる必要が出てきます。
>
> VRMアドオンでは「目は正面向いているのが普通」という考えから、目のボーンに子ボーンが無い場合は正面(*2)を向けています。
>
> このようなことから、目のボーンを上に向けてVRMエクスポートした場合「目のボーンが上を向いている」という情報は失われてしまい、再度インポートする際はまた「目は正面向いているのが普通」という推定が発生し、インポート時に目が正面を向いてしまうという現象です。
>
> Blender 4.0から「ボーンの向きを気にしなくて済む設定」が追加されるので、それを用いることでこのような自動変換をしないで良くなる、という解決が可能になるため、完全解決はそれまでお待ちいただけると助かります。
>
> > *1 正確には、完全にその方向まっすぐ回転させるのでは無く、一番近い方向を向くように軸の変換を行います
> > *2 BlenderのglTF(VRMの親仕様)インポーターにおける正面である -Y 方向を正面として扱い軸の変換を行います。

**Comment by teresayawn** [comment]
早速のご回答有り難うございます。

過去の同内容の報告を確認できず、失礼しました。
解決の可能性が見通せているとのことですので、一安心しました。

VRMの挙動を確認しているソフトは、最近ver1.0に対応した、VRM Posing Desktop ver 4.09-2 および、VPic ver
2.0.0です。
共にVroid Hubで連携アプリとして紹介されています。

3DCGは、最近手を出したばかりの若輩者ですが
今後ともどうぞ宜しくお願いします。


2023年10月3日(火) 9:04 saturday06 ***@***.***>:

**Comment by saturday06** [comment]
VRM Posing DesktopやVPicなどのアプリで視点操作に不具合が発生する件は、UniVRMの不具合が原因のようでした。本件UniVRMにバグ報告をしました。

こちらでバグ報告の最新の状況が確認できます → https://github.com/vrm-c/UniVRM/issues/2159

[VRMお手軽ポーズ](https://www.vrmwebpose.app/) や[VRoid Hub](https://hub.vroid.com/)の写真撮影画面など、UniVRMではなくthree-vrmを用いるアプリでは、本BlenderアドオンからエクスポートしたVRM1.0モデルにおいても視点操作は正しく動作していることを確認しました。

**Comment by saturday06** [comment]
UniVRMの視点操作のバグが修正されました (https://github.com/vrm-c/UniVRM/pull/2163 )。VRM Posing DesktopやVPicで利用されているUniVRMが最新バージョンにアップデートされた際に、このアドオンで作成されたモデルの視点操作が正しく行われるようになります。

**Comment by saturday06** [comment]
報告いただいたケースは、VRMインポートアプリが視点操作のバグを含む古いUniVRMを利用しているのが原因のバグでした。UniVRM側が修正完了したため、こちらは解決済みとします
