### ISSUE TITLE
Bug report: Mesh, textures, and armature are imported, but data such as Meta, Humanoid, Blend Shape Proxy, and Spring Bone are not imported.

### ISSUE THREAD

**Issue by nilepereiraa** [saturday06/VRM-Addon-for-Blender#336]
## Describe the bug

I am able to import the models and the armature just fine, but bringing up the VRM Panel through the "N" menu shows that all the data is empty. Meta info, Humanoid bone assignments, Blendshape Proxy, First Person, and Spring Bone data are nonexistent. "vrm.json" does not seem to be imported

## To Reproduce

1. Install latest version of VRM Addon
2. Import model
3. Check VRM N Panel
4. No data in any of the sections

## Expected behavior

VRM Addon should import the data associated with the model, instead of just the Textures, Armature, Meshes, and Empties.

## Screenshots

![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/63991493/3434eac2-6fea-4b5b-8a86-d16dc3ab9953)
![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/63991493/7c73e217-e7ea-49cd-9dd7-22d57921c6f6)

## Desktop (please complete the following information)

- OS: Windows
- Blender 3.6.4 LTS (Steam Version)
- Addon Version 2.20.7

## Additional context

I'm not sure what causes it to behave this way. Could it be the custom workspaces? Or Filter Addons being enabled? Everything else works fine. Back when it was still working, there was a vrm.json that would get imported along with all the files, but now I don't see that file being imported or created with the addon.

**Comment by saturday06** [comment]
Thanks for reporting!

Maybe it is a bug in the add-on. To investigate the bug, error messages are shown in the console, so please go to the menu "Window" -> "Toggle System Console" to display the console and share its contents.

<img width="880" alt="screenshot" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/b8124b95-bd4b-4915-95bc-e9e7bd0fff5a">

**Comment by saturday06** [comment]
This console may contain your PC username, so to be safe, please remove it from the screenshot.

**Comment by nilepereiraa** [comment]
Hello! I may have determined the cause for the bug. 
![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/63991493/d265d11a-e970-483f-aba7-f7fdf6cbab3e)

To reproduce the bug:
- Install AgX color transform from Troy Sobotka's GitHub,
- Import model that has "Non-color" images such as normal maps
- Addon will spit out error saying that "Non-color" cannot be found in the list of available color spaces (Troy's AgX color transform renames "Non-Color" to "Generic Data")

It seems that the addon fails to import the rest of the VRM data like the meta info, bone assignments, and blend shape proxy if the building of the mToon shaders fail.

I have gotten around this problem by installing the color transformations from Blender 4.0, which does include "Non-color". Perhaps a fallback could be added to force the addon to continue importing data despite the mToon shaders failing to build?

**Comment by saturday06** [comment]
The error was resolved with the latest add-on released a while ago. Please try!

> Perhaps a fallback could be added to force the addon to continue importing data despite the mToon shaders failing to build?

Although this is possible, it is difficult because the data will be corrupted without the user knowing.
It's a pain to add a process to make the user aware of the bug, so I'll deal with it another time.
