### ISSUE TITLE
Bug report: Textures are not Exported using Principled BSDF

### ISSUE THREAD

**Issue by Recon419A** [saturday06/VRM-Addon-for-Blender#362]
## Describe the bug

Following [this tutorial](https://vrm-addon-for-blender.info/en/material-pbr/?) as linked in several previous issues from about twelve months ago fails to yield the expected result; instead, it yields an unlit mesh.

## Desktop (please complete the following information)

- OS: Windows 11
- Blender 4.0.0
- Addon Version 2.20.17

## Additional Context

Blender file is [attached as untitled.zip](https://github.com/saturday06/VRM-Addon-for-Blender/files/13361818/untitled.zip), along with the generated VRM and a generated FBX to prove the material is correctly exported to FBX.

**Comment by Recon419A** [comment]
It's possible I'm just an idiot, as I've never done this before, but as best I can tell I didn't miss anything in the tutorial, which I used to isolate the bug after struggling with more complicated Blender files earlier in the day.

**Comment by saturday06** [comment]
Thank you for the report!

In reality, VRM materials are not fully compatible with Principled BSDF, so some information is missing.
See [the glTF tutorial](https://docs.blender.org/manual/en/4.0/addons/import_export/scene_gltf2.html#exported-materials) to learn what information is exported from Principled BSDF to VRM.

VRM is a standard based on glTF, and the VRM add-on uses the glTF add-on when exporting Principled BSDF.

**Comment by Recon419A** [comment]
That doesn't surprise me, and I fully expect I may have problems with more complicated renders, but I was heavily surprised I couldn't get it working with a basic blue-shaded sphere. It's possible the tutorial is just out of date; do you have an example of a recent, working export I can take a look at to emulate?

I appreciate your quick response, by the way. I'm realizing I jumped in with terrible timing since Blender 4.0.0 released literally hours before I downloaded it.

**Comment by Recon419A** [comment]
@saturday06 I can confirm this issue is isolated to Blender 4.0.0. Using the previous version of Blender 3.6 and the plugin version intended for it (one release back, 2.20.16) exports materials as intended using the same data files.

**Comment by saturday06** [comment]
My operation confirmation was insufficient. This is an addon bug and occurs in Blender 4.0.
I have fixed that bug in the latest version of the add-on (2.20.18) that I just released.

Thanks for your report!

**Comment by ghost** [comment]
it seems that all texture are gone when exporting as fbx in 4.x, do you know what's the reason?
@saturday06

**Comment by saturday06** [comment]
Old add-on do not support fbx texture export. Could you tell me the add-on version you are using?

**Comment by saturday06** [comment]
The latest version 2.20.60 supports it.
