### ISSUE TITLE
Bug report: When exporting vrm, materials are not applied to the character.

### ISSUE THREAD

**Issue by pgw130** [saturday06/VRM-Addon-for-Blender#365]
## Describe the bug

When exporting after applying a material to Principled BSDF, the character appears gray without the material applied.
This can be resolved by downgrading the version, but I would like to know the fundamental solution.
If it is a bug, I would appreciate it if you could fix it.

## Desktop (please complete the following information)

- OS: Windows10
- Blender 4.0.0
- Addon Version 2.20.17

**Comment by saturday06** [comment]
This is an addon bug and occurs in Blender 4.0. I have fixed that bug in the latest version of the add-on (2.20.18) that I just released. Please try it.

**Comment by pgw130** [comment]
I tested it and it was resolved successfully. Thank you very much.
