### ISSUE TITLE
要望: FBXエクスポート時の「テクスチャを埋め込む」オプションに対応したシェーダーノードでのインポート

### ISSUE THREAD

**Issue by diglateam3** [saturday06/VRM-Addon-for-Blender#367]
### どの動作で困っているのか
BlenderのFBX Exporterには「パスモード」を「コピー」にした際、テクスチャをFBXバイナリに埋め込めるオプションが提供されています。
2.15.xまではこのオプションによりFBXへテクスチャの埋め込みを伴う形での出力が可能でした。

しかしながら、2.16.0以降のシェーダーノード構造の変更以降、FBX Exporterが`MToon 1.0 Material Output`を解釈しきれず、ノードが存在しないと解釈され（FBXエクスポート時にシステムコンソールに`NO NODES!`を出力する）、上述のオプションを用いた際にテクスチャを含まない状態でエクスポートされるようになってしまっています。

### なぜその挙動だと困ることになるのか
VRM形式でExportすれば確かに問題は発生しません。しかしながら、以下のユースケースで支障が発生しています。

* 複雑なテクスチャ構造のアバターをFBXで出力し、最後の調整（揺れ物やシェーダーの設定など）はUnity上で行いたい
* それに付随する形で、VRoid Studio製のアバターを微調整する際、別途何らかの形で他にテクスチャを書き出し手動で再割り当てするとしても、非常に時間も行程もかかり、手間である

VRoid Studioユーザーの方にこの事象を説明したところ、要望を頂きましたので、本人の許諾の上で掲載いたします。
（その方が主催するオンラインワークショップの最中で、前述のエクスポートのワークフローの際に私含む複数の参加者で今回の事象が発覚し、私が代理でIssueを立てるに至った、という経緯もあります）

```
* VRoidStudio製VRMをVRChatで利用するに際し、フルボディトラッキングでの挙動を修正するためにBlenderでの調整が必要である（VRMConverterでは修正できないポイントが存在する）
* 手順の簡略化のためCATS Blender PluginのAuto Fixを利用することから、最終的にBlender2.93.1でFBXエクスポートを実施する（VRMエクスポートを実行しない）
* MaterialCombiner等で一部マテリアルのアトラス化手続きを実施する都合上、インポート前のVRMのテクスチャをUnity上で流用できない箇所がある
* UnityでFBXに対し手動で10～20個のマテリアルを適用させる作業が発生するため、手続きが煩雑化する。
特に同一の衣装メッシュを利用している場合やVRoidStudioでマテリアル削減機能を利用していた場合は、対応しているマテリアルの判別が難しくなる。

＞要約するとembedできなくなることで手続きが煩雑化し作業が遠回りになるのを回避したい、というところです
```

## どう動いてほしいかをどうぞ
（ここでの「どう動いてほしいか」がActionではなくBehaviorであることは承知の上で）2.15.xまでのシェーダーノードの構造でのインポートのオプションの追加

## 他にこんなんでもいいよ、というのがあれば
テクスチャの埋め込みに対応した別のシェーダーノードでのインポート

## なんかほかに書きたいことがあれば
Closedされたもの含めIssueを確認しても既出ではなかったため、本来想定外のレアなユースケースなのかもしれません。
しかしながら、当事象で困っているユーザーがいることもまた事実であり、その事実を認識して、かつ自分もそれに遭遇し問題が発生したにも関わらず、Issueを立てない、という選択を取るのは難しかったため、こうしてIssueとして報告した次第です。

**Comment by saturday06** [comment]
ご報告ありがとうございます。こちら時期は明言できませんが対応する方向で進めます。

たしかに、インポートしたものをそのままfbxエクスポートした際にテクスチャがついてくる設定が可能ならば、便利だと感じました。

**Comment by saturday06** [comment]
いったんは、BlenderからエクスポートされたVRMを、UnityにUniVRMパッケージを経由してアセットフォルダに展開し、そこから所望の最終調整を行っていただく方針で作業いただければと思います。

**Comment by saturday06** [comment]
@diglateam3

先ほどリリースした最新版でこちらの機能を実装いたしました。

VRMアドオンが生成するシェーダーノードを、BlenderのFBX Exporterが要求するシェーダーノード構造の仕様を満たすように変更しました。これにより、FBXエクスポート時に「パスモード」を「コピー」に指定し、また「テクスチャを埋め込む」を有効にすることでFBXファイルにテクスチャが埋め込まれるようになりました。

ぜひご確認ください。

**Comment by diglateam3** [comment]
`Version 2.20.48`にてエクスポートしたFBXにテクスチャが埋め込まれることを確認しました！  
かなり特殊なユースケース想定にも関わらず、丁寧に実装して頂きありがとうございました。
