### ISSUE TITLE
Blender 4.0でVRM 1をインポートするとアーマチュアが正しくインポートされない

### ISSUE THREAD

**Issue by ykomatsu** [saturday06/VRM-Addon-for-Blender#368]
## バグについて

Blender 4.0でVRM 1をインポートするとアーマチュアが正しくインポートされず、添付のスクリーンショットのようになります。

## バグの再現方法

Blender 4.0でFile→Import→VRMで次のデータをインポートします。

https://github.com/vrm-c/vrm-specification/blob/master/samples/VRM1_Constraint_Twist_Sample/vrm/VRM1_Constraint_Twist_Sample.vrm

## 期待する動作

Blender 3.6ではアーマチュアを含めて正しくインポートできていたので、それと同じ動作を期待します。

## スクリーンショット

<img width="1582" alt="スクリーンショット 2023-11-18 15 16 51" src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/277653/c1d025b9-a53a-4d11-9035-fe4b23bf2166">

## PC環境情報

- OS: macOS Sonoma 14.1.1
- Blenderのバージョン 4.0.1
- アドオンのバージョン 2.20.18

## なにか他に書いておきたいことはこちらへ

**Comment by saturday06** [comment]
ご報告ありがとうございます。こちらアーマチュアの編集モードでボーンの伸びる方向がおかしなことになっているように見える、という報告だと解釈しました。こちらちょっと重い問題なのですが、最悪でもBlender 4系のLTS版が出るまでには良い感じに見えるように調整したいと思っています。

この問題の原因は、Blender 4.0に同梱されている、VRMの親規格であるglTF 2.0アドオンの仕様変更によるものです。
仕様変更の経緯はこちらに記載されています https://github.com/KhronosGroup/glTF-Blender-IO/issues/1662 

その親規格のアドオンがいい感じになれば自動的にVRMアドオンもいい感じになるため、もし良ければそちらにもイシューを立てていただけると非常に助かります。

----- 以下もうちょっと細かい事情説明 -----

Blender 4.0に同梱されているglTF 2.0アドオンから「ボーンの進行方向」のデフォルト設定が変更されました。今までは「Temperance」という設定だったのが「Blender」という設定になりました。

glTFは「ボーンの進行方向」という概念が無いです。しかしBlenderには「ボーンの進行方向」という概念があります。そのため、いい感じにボーンの進行方向をでっち上げないといけないです。その方法としてBlender 3系まではデフォルトで「Temerance」という方式が用いられていました。これは「あるボーンの進行方向は、X軸、Y軸、Z軸、-X軸、-Y軸、-Z軸のうち、子ボーンの座標に一番近い軸にする」というものです。これはわりと実用的ではあったのですが、glTFアドオンのレポジトリでは様々な問題があったようで、例えばVRMにおいては、コンストレイントを扱う際に変換不可能な軸の組み合わせが(たぶん)あったり、そもそも処理が複雑でバグりやすいという問題がありました。

そのため、デフォルトでは軸の変換を全く行わないインポートになったようです。

イシュー https://github.com/KhronosGroup/glTF-Blender-IO/issues/1662  でも語られていますが、軸の変換を行わないとボーンの進行方向が変な方向を向くことがあります。お使いのVRMコンソーシアムのモデルで発生している現象はそれです。Blender 4.0からの別の仕様変更でそのへんが解決したと伺っていたのですが、実際に動かしてみるとまだまだ発展途上な感じに見えます。

私としては、そのあたりの親規格のデフォルト設定に合わせておかないと、ただでさえ多いVRMアドオン独自仕様がまた増え、親規格・親仕様への追従コストがもりもり増えると感じたため、Blender 4.0以降の仕様変更をそのまま受け入れた形となりました。

でもやっぱり編集モードでボーンが上向いちゃうのはしんどいのでどうにかいい感じに対応したいと考えています。

**Comment by ykomatsu** [comment]
ありがとうございます！

説明が分かりにくくて申し訳ございません。
そんなにややこしい話だったんですね。
了解いたしました。

**Comment by saturday06** [comment]
先ほどリリースした最新版 2.20.19 で、Blender 4.0においても3.6と同様のインポートするように変更しました。Blender側が安定するまではしばらくはこのままいこうと思います

**Comment by ykomatsu** [comment]
ありがとうございます！

ボーンの方向が3.6と同じようになりました。
完全な解決ではないのかもしれませんが一旦閉じさせていただきます。
