### ISSUE TITLE
VRM0.xにおけるSpring Bone Groupの"Stiffness"のプロパティ名が"stiffiness"になっている点について

### ISSUE THREAD

**Issue by Yulit-c** [saturday06/VRM-Addon-for-Blender#370]
## バグについて
VRM0.xのSpring Bone Groups内にあるプロパティ`Stiffness`のData Path上の名前が`stiffiness`になっていました｡
VRM1.0のSpring BoneにおけるSprings内では`stiffness`になっていたのでタイポなのかなと思いました｡

## 期待する動作
アドオンの動作上､問題になることはゼロだとは思いますが､スクリプトでデータにアクセスする際に混乱する要因になりそうなので､
可能であれば内部上のプロパティ名を正しいスペルに修正していただけると幸いです｡

## スクリーンショット
![vrm0_spring_bone_group_stiffness](https://github.com/saturday06/VRM-Addon-for-Blender/assets/18331487/cc0cd31b-d911-4281-bb97-d3a8cf282052)
![vrm1_spring_bone_joint_stiffness](https://github.com/saturday06/VRM-Addon-for-Blender/assets/18331487/25d478e7-17ac-47e6-b559-e1ca4f63f29a)

## PC環境情報
- OS: Windows11 22H2
- Blenderのバージョン 3.3.8
- アドオンのバージョン 2_20_18

## なにか他に書いておきたいことはこちらへ
このアドオンには非常に助けられております｡VRMのデータ作成/修正がBlenderだけでほぼ完結できて最高です｡

**Comment by saturday06** [comment]
ご報告ありがとうございます。すみません、こちらのtypoに関しては、仕様で決まってしまったtypoという特殊事情があるため、修正は無しとしております。

----- 以下、細かい経緯です -----

こちらの stiffiness のtypoは、VRM 0.0 仕様で決まってしまった、VRM 0.0ファイル内部に存在するtypoになります。

仕様の記載箇所はこちら:
https://github.com/vrm-c/vrm-specification/blob/1723a45abfb4f12ac5d3635a3f66dc45e2f93c83/specification/0.0/schema/vrm.secondaryanimation.spring.schema.json#L9-L12
関連する公式のイシューはこちら
https://github.com/vrm-c/vrm-specification/issues/82

VRMアドオンでは、VRM 0.0ファイルの内部データを可能な限りそのままPropertyGroupに移しているため、内部的にはtypoが残った状態になっています。

同様のtypoとして、extensions.VRM.meta.commercialUssageName などがあります。これらのtypoはVRM 1.0で改善されました。

**Comment by saturday06** [comment]
今回は事情が特殊だったので特殊対応をさせていただいておりますが、一般的なtypoに関しては報告いただき次第対処しております。もしほかに何かあればご報告いただけるとありがたいです。あるいはPull Requestを出していただければすぐにマージいたします！

**Comment by Yulit-c** [comment]
ご丁寧な経緯の説明ありがとうございます｡
今回報告しつつも､それと同時に何となく､このタイポは特殊な事情があるのではないかと思ってもおりましたが､親元のリポジトリの方にあった仕様だったのですね｡
迅速な対応に感謝いたします｡ありがとうございました｡
