### ISSUE TITLE
Blender4.0においてVRM MToonマテリアル設定時に起きる現象

### ISSUE THREAD

**Issue by teresayawn** [saturday06/VRM-Addon-for-Blender#372]
お世話になっております

さて、Blender（4.0.1）および、VRM Add-on for Blender（2.20.19）の環境下、新規作成したマテリアルの設定において、VRM MToonマテリアルを有効にした直後、既存の全てのVRM MToonマテリアルの発色に不具合が生じます（スクショ一枚目、二枚目参照）。
この現象はBlender3.6.5と上記最新アドオンとの組み合わせでは発生しないようです。また、VRMのバージョン（0.ｘまたは1.0）に関係なく不具合は発生しています。

![Bug_231123A_01](https://github.com/saturday06/VRM-Addon-for-Blender/assets/146738533/33b2474c-e7c6-42b1-b301-33fcae656059)
![Bug_231123A_02](https://github.com/saturday06/VRM-Addon-for-Blender/assets/146738533/eb2b39c8-7110-4184-87f0-9fdc1c2c1385)

上のスクショでは、床にマテリアルを新規作成し、その設定にあるVRM MToonマテリアルを有効にした場合です。
VRMモデル以外のオブジェクトであっても、シーン内で新規マテリアルを作成し、VRM MToonマテリアルを有効にすると、
既存の全てのVRMマテリアルに影響を与える不具合が発生するようです。

今のところの対処法は、VRM MToonマテリアルのチェックを入れなおすと、上記問題は解消しますが、一つずつマテリアルを修正しなけらばならず、数が多いと面倒なことになります（三枚目のスクショはその修復作業を行っているところです）。

![Bug_231123A_03](https://github.com/saturday06/VRM-Addon-for-Blender/assets/146738533/d2391fb6-bc8d-4774-b3b0-e9aa374df40b)

なお、スクショでは床の影が消えますが、この状態でもLightingのShade Colorの明度を下げると影は現れます。
直前のバグ報告で、Vroid出力のVRMモデルの影が消えることを報告していますが、Vroid Studioではアルファモードが不透明ではなく、Cutoutで出力されていることが原因かもしれません。影が消える現象はBlenderのバージョンアップとは直接関係ないと思われます。また、UniVRMプラットフォームでは、Cutout出力であっても影は現れます。

## 期待する動作
Blender４.0に限って起こる現象のようなので、今のところ、最新アドオンで問題が起きないBlender3.6.5で事足りています。4.0は仕様変更で躓くことが多く、今はよく使う機能の操作について確認しているところです。

## PC環境情報
 Windows10
 Blenderのバージョン [4.0.1]
アドオンのバージョン [2.20.19]

今回使用したVRM（0.ｘ）モデルは、以下のサイトからダウンロードしたものです。
https://3d.nicovideo.jp/alicia/
　
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　以上

**Comment by saturday06** [comment]
報告ありがとうございます！調査いたします！

**Comment by saturday06** [comment]
先ほどリリースした最新版2.20.20で真っ黒になる現象は解決しました。お試しください！

影が出ないことがある問題はちょっと難しそうなので対応に時間がかかるかもです。

**Comment by teresayawn** [comment]
いつもながら素速いご対応ありがとうございます。

最新アドオンで確認したとこと、VRMマテリアルの問題は解消されていることを確認いたしました。
ありがとうございました。

影については、Vroid Sutdioで出力後、いつもUnityアプリ上で確認していたので、先の方が報告されるまで気がつきませんでした。

本件と話がそれますが、私がUnityアプリをVRMの撮影に使う理由のひとつに、Blender内ではRender queueによるレンダリング順序が反映されないことがあります。例えば、マンガでよくある髪の毛の上に本来隠れるべき眉毛などを投影させる描画方法です。もし、それが既にBlender内で可能であれば、ご教示願いたいと思います。

よろしくお願いします。
