### ISSUE TITLE
バグ報告: 

### ISSUE THREAD

**Issue by RideREX** [saturday06/VRM-Addon-for-Blender#376]
## バグについて

Blender4.0.1にアップデートしたところ、VRM add on for Blenderがアドオンからチェックが消えて使えなくなっていました。アドオンのチェックを入れるとエラーが出て使えず、再インストールしても同様にエラーが出ました。画像添付してあります。エラー表示の最後の行によれば「GL_BYTE」というプログラムがインストールできないとのことです。

## バグの再現方法

Blender3.4からBlender4.0.1へアップグレードしたところ、アドオンが動かなくなっていました。
エラーメッセージは画像で添付してある通りです。

## 期待する動作

アドオンが問題なく起動するようにBlender4に対応したデータを配布してください。

## スクリーンショット

エラーメッセージが出た画面をスクリーンショットで添付してあります。

## PC環境情報

- OS: Windows11
- Blenderのバージョン　4.0.1
- アドオンのバージョン　2.20.20

## なにか他に書いておきたいことはこちらへ
VRoidの変換に重宝しています。開発ありがとうございます。
![スクリーンショット (595)](https://github.com/saturday06/VRM-Addon-for-Blender/assets/38597011/3505993d-e89d-4db5-8338-6b8409150ecf)

**Comment by saturday06** [comment]
報告ありがとうございます！

現象の調査のため、下記のファイルをメモ帳で開いて、結果のスクリーンショットを貼っていただけますでしょうか！

**C:\Users\あなたのユーザー名\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\VRM_Addon_for_Blender-release\common\gl.py**

私の手元のWindows11, Blender 4.0.1, アドオン2.20.20でインストールを試したのですが、特にエラーは発生しませんでした。そのため、当該のファイルのデータの一部が何らかの原因で壊れてしまったのではないかと感じているため、そのスクリーンショット貼り付けを要望させていただきました。

私の手元で試した動画はこちらになります。

https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/e2ee1b46-bf5b-48d6-b799-3720be8a76f0

**Comment by RideREX** [comment]
ご指定のファイルをスクリーンショットしました。他にも解決のために必要なファイルがあれば、お知らせいただけたら貼り付けます。
![スクリーンショット (596)](https://github.com/saturday06/VRM-Addon-for-Blender/assets/38597011/59203ac4-48b3-45fc-9052-aa98f0c79cb7)

**Comment by saturday06** [comment]
ご協力ありがとうございます。スクショで頂いた内容は正常で、壊れていませんでした。はじめにご指摘いただいたGL_BYTEというデータはそのファイルの二行目に記載されているものになります。データが正常なのに読めないというエラーが起きているので、かなり難しい問題が発生しているものと思われます。

お手数ですが、下記の作業を行い、正常に動作するかどうかを確認いただけますでしょうか？

- Blenderを起動している場合は終了
- **C:\Users\あなたのユーザー名\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons** フォルダをデスクトップかどこか安全な場所に移動する。元あった箇所からは削除。
- PCを再起動
- Blenderを起動し、VRM Add-on for Blenderアドオンをzipファイルからインストール
- チェックボックスを押して有効化できることを確認
- 有効化できることを確認できたら、Blenderを終了し、さっき安全なところに移動したフォルダの中身から、`VRM_Addon_for_Blender-release` フォルダを除いたものを元の場所に戻す。
- チェックボックスを押して再度エラーが出た場合、すみませんがもう一度エラーのスクショの貼り付けをお願いします。

(この作業をしていただく意図は、1.VRMアドオンを実行するpythonのキャッシュが壊れている可能性があるのでそれを削除、2.別のアドオンと相性が悪くうまく動かないという可能性の排除、による原因調査になります)

**Comment by RideREX** [comment]
お知らせいただいた通りにアドオンを入れ直したところ、正常に動くようになりました。ありがとうございました。心当りがひとつあり、つい最近pythonの別のプログラムを実行しようとしてエラーで起動できなかったものがあるので、それが影響していたのかもしれません。Blender3.4ではアドオンが正常に動いているのですが、なぜかBlender4ではインストールのチェックボタンがクリックできず、困っていました。これで最新版を使用できます。助かりました。

**Comment by saturday06** [comment]
お役に立ててうれしいです！

正直、今回のやつ試していただいてもダメだったら打ち手が無くなるところだったので安心しております。引き続きよろしくお願いします！
