### ISSUE TITLE
バグ報告: 

### ISSUE THREAD

**Issue by minamo** [saturday06/VRM-Addon-for-Blender#378]
## バグについて

Blender 4.0.1にアップデートした後、設定を引き継がないで初期化しても、VRM Export時に添付スクリーンショットのエラーが発生します。

## バグの再現方法

Python再インストールしても、Blender再インストールしても、設定ファイル引き継がなくとも発生します。

## 期待する動作

Blender 3.6.2では問題なくExportできるため、同じように動作することを期待します。

## スクリーンショット

![スクリーンショット 2023-12-01 212127](https://github.com/saturday06/VRM-Addon-for-Blender/assets/1066847/2d1e51ca-3658-4ae2-9275-9afa03b7e81d)

## PC環境情報

- OS: Windows11(23H2)
- Blenderのバージョン 3.6.2、4.0.1
- アドオンのバージョン 2-20-20

## なにか他に書いておきたいことはこちらへ
VRM AddonがBlender4に対応していないものと思っていましたが、別の報告で対応できていると描きこみをみたため、何か解決できないかと問い合わせさせていただいた次第です。

**Comment by minamo** [comment]
すみません、おそらく描きだしたいファイルに依存した問題のようですので、取り下げ致します。

**Comment by saturday06** [comment]
ご報告ありがとうございます。こちら取り下げとのことですが、こちらのバグを修正したバージョン 2.20.21を先ほどリリースいたしました。ぜひお試しください！(アドオンアップデート後はBlenderを一度再起動お願いします)

エラー全体のスクリーンショットを貼っていただいたことで、怪しい箇所の調査がスムーズに進みました。次回も何かあったらよろしくお願いします！

**Comment by minamo** [comment]
アップデートありがとうございます！
確かに2.20.21にアップデートしたところ正常に書き出しができました。
今後もよろしくお願いいたします。
