### ISSUE TITLE
要望: VRM1.0 : 同一の画像を複数のマテリアル･スロットで参照した場合に画像を複製しない動作

### ISSUE THREAD

**Issue by Yulit-c** [saturday06/VRM-Addon-for-Blender#380]
## バグじゃないけどアドオンの動作でなにか困ってることがあれば
添付画像のように､同じ画像を複数のマテリアルのスロットに指定する､あるいは同じマテリアルの複数のスロットで参照した場合､書き出されたVRMファイルには､複製された画像として格納されるため､同じ画像であってもファイル数が増えてしまい､書き出されたファイルのサイズがその分大きくなってしまうと思います｡
![reference_same_image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/18331487/2911b3f5-4290-4fc5-acff-61c536c87c04)

![duplicated_images](https://github.com/saturday06/VRM-Addon-for-Blender/assets/18331487/eb101148-1eb2-49c9-964c-a28507e370fc)

## どう動いてほしいかをどうぞ
ファイルサイズを抑制するため､あるいは書き出し後に再編集をする際に､一つのファイルを編集すれば全てに反映できるようにするために､同一の画像ファイルは単一の画像ファイルとしてエクスポートされると嬉しいと感じました｡

**Comment by saturday06** [comment]
ご要望ありがとうございます！調査いたします

**Comment by Yulit-c** [comment]
後から思ったことですが､UniVRMによるインポート側の設定である気も...?
最初に書き忘れていた､こちらで試してみたことも追記しておきます｡

1. Blenderからエクスポート
2. UnityにVRMファイルをインポートしてマテリアルとテクスチャを展開
3. 複製されて別画像としてアサインされているテクスチャを同一のものに修正する
4. Unityから再エクスポート
5. Unity内で確認してみるとテクスチャは複製されていない

という動作は確認しています｡

**Comment by saturday06** [comment]
先ほどリリースした2.20.23でこちらのテクスチャが増える問題を修正しました。お試しください！
