### ISSUE TITLE
Blender4.0におけるVRM1.0入出力時の問題：Issues with VRM 1.0 Input/Output in Blender 4.0

### ISSUE THREAD

**Issue by teresayawn** [saturday06/VRM-Addon-for-Blender#381]
いつもお世話になっております。

Blender4.0.1、および、最新アドオン(version 2.20.21)の環境下において、VRM1.0ファイルをインポートした場合に起きるボーンの異常、および、エクスポートしたVRM1.0ファイルがUnity（UniVRM v0.115.0）に正しく読み込めない問題をご報告致します。glTF 2.0アドオンの問題が解決されていないのであれば、ご容赦下さい。

なお、上記問題について、Blender3.6.5では、最新アドオンであっても起きないことを確認しております。また、Blender4.0.1で出力したVRM1.0ファイルであっても、Blender3.6.5で再度、読み込み、書き出しを行うと、これら問題は修復されるようです。

下の画像（1枚目）はVRM1.0の公式サンプル（[VRM1_Constraint_Twist_Sample](https://github.com/vrm-c/vrm-specification/tree/master/samples/VRM1_Constraint_Twist_Sample)）を用い、上記Blender4.0.1の環境でインポートし、ポーズモードでの画面を示したものです。

![Fig_1](https://github.com/saturday06/VRM-Addon-for-Blender/assets/146738533/f92bcab1-9536-4575-aa9c-03ff0280d245)

ボーンの代わりに球体が配置され、これを回転させるとポーズ機能は働いているようです。しかし、この状態では、ボーンのつながりが非常にわかりにくいです。ビューポートの表示を変えても、変化しません。ただし、編集モードだけは、正常な形のボーンで表示されます。表示切り替えも有効です。

アウトライナーを見るとglTF_not_exported という名称のコレクションが作成されており、その中にICO球と言うメッシュが存在します、これがボーンの代わりに表示されているように思えたため、それを削除すると、2枚目の画像のように、正常な形のボーンに戻りました。

![Fig_2](https://github.com/saturday06/VRM-Addon-for-Blender/assets/146738533/5364f8e4-5e82-4439-b9db-ea2d1983c008)

しかし、ICO球を削除するしないにかかわらず、上記Blender4.0で出力したVRM1.0ファイルは、Unity（UniVRM v0.115.0）にインポートできません（画像3枚目）。

![Fig3B](https://github.com/saturday06/VRM-Addon-for-Blender/assets/146738533/6ace5000-263c-4eb2-b302-af7dd70051ef)

各エラーの詳細については、テキストファイルを添付します。
[console_error_message.txt](https://github.com/saturday06/VRM-Addon-for-Blender/files/13542718/console_error_message.txt)

以上の問題は、VRoid Studioで出力したV1.0のVRMファイルも同様に起きます。
Therr.js上で動く環境（例えば、[VRMお手軽ポーズ](https://www.vrmwebpose.app/)）では、正常に読み込まれます。

例外として、Blender4.0.1内で新たにVRM1.0のモデルを作成した場合（簡易モデルでの検証ですが）、ICO球は生成せず、その出力ファイルはUnityに正常に読み込ませることができます。また、このファイルはBlender4.0.1で入出力を繰り返しても問題は生じません。

現状、Blender3.6.5と最新アドオンの組み合わせで、ｖ0.x系も含め、やりたいことはできていますが、Blender4.0正式版公開時から気になっていたので、ご報告致しました。

どうぞ宜しくお願いします

## PC環境情報
- OS: [Windows10 Home]
- RAM: 32 GB
- Blenderのバージョン [4.0.1]
- アドオンのバージョン [2.20.21]
- UniVRM [v0.115.0]
##

**Comment by lyuma** [comment]
This is really a bug in UniVRM: they did not implement one valid unsigned type for sparse accessor: UNSIGNED_BYTE.
I have opened a pull request to UniVRM requesting UNSIGNED_BYTE to be added for VRM 1:
* vrm-c/UniVRM#2186

This is the bad file exported by Blender.
[constraintexample.zip](https://github.com/saturday06/VRM-Addon-for-Blender/files/13544851/constraintexample.zip)

HOWEVER... even if UniVRM implements support for UNSIGNED_BYTE, there is a long tail of VRM apps that will need to update with compatibility for this bugfix on VRM 1.0, and perhaps other applications which are still on Unity 2019, which is no longer supported by vrm-c and will not receive updates such as this fix.

The options are to either continue using VRM 0.0 on Blender, or create some mitigation to prevent blender from using UNSIGNED BYTE sparse indices. For example, if at most 255 unused vertices are added in front, it might force blender to pick UNSIGNED_SHORT, which is supported by UniVRM. Perhaps better solutions exist, but this is one idea.

**Comment by lyuma** [comment]
As a comment, the bug only affects VRM 1.0.

glTF and VRM 0.0 has full support for byte, short and int sparse accessors in UniVRM. It is unclear to me why UniVRM uses different code in `Vrm10ImportData.cs` for VRM 1.0.

**Comment by teresayawn** [comment]
Thank you for your detailed comments. 

While I'm not well-versed in programming, I wonder if UNSIGNED_BYTE wasn't implemented to prevent a performance decrease due to increased data volume in that field. Alternatively, could it be related to compatibility issues, or was it simply a matter of lower priority and omission? 
　Considering the Sparse Accessor, it seems like UNSIGNED_BYTE should be implemented, even for VRM 1.0. It would be a reasonable expectation. Perhaps it's just a simple oversight.

**Comment by saturday06** [comment]
I have just released the latest version 2.20.23, which exports VRM1 readable by UniVRM. Please try it out.

**Comment by teresayawn** [comment]
早速の対応、ありがとうございます。
最新のUniVRM環境で、Blender4.0.1から出力されたVRM1.0ファイルが読み込まれることを確認いたしました。基本的な操作にも問題ないようです。
Blenderに読み込んだ際のICO球はまだ発生するようですが、削除してもUnityへのインポートには問題ないようです。

Thank you for your swift response.
I have confirmed that VRM 1.0 files exported from Blender 4.0.1 in the latest UniVRM, can be successfully imported. Essential operations also seem to work without any issues.
While the occurrence of ICO mesh still appears upon loading into Blender, it seems that deleting them doesn't pose any problems for the import into Unity.

**Comment by saturday06** [comment]
> Blenderに読み込んだ際のICO球はまだ発生するようですが

こちらはバグという認識でしょうか？バグという認識の場合Blender同梱のglTFアドオン https://github.com/KhronosGroup/glTF-Blender-IO/issues のバグのため、そちらに報告をお願いします。

glTFはVRMの親仕様のため、VRMアドオンではそのglTFアドオンの処理を使っています。glTFアドオンはICO球を自動追加します。

ICO球を自動で削除する処理を追加しても良いのですが、VRMアドオンはそのような独自処理が既に多すぎて使いにくいアドオンになってしまっているので、独自処理もうそんなに追加したく無いという経緯があります。公式の方が方針を変えてくれれば非常に助かるという感じです。

**Comment by saturday06** [comment]
> While the occurrence of ICO mesh still appears upon loading into Blender

Do you think this is a bug? If so, please report it there because it is a bug in the glTF add-on included with Blender https://github.com/KhronosGroup/glTF-Blender-IO/issues.

The glTF add-on automatically adds ICO spheres.

Automatic removal of ICO spheres is possible. However, VRM add-on already has too many such proprietary processes that make it a difficult add-on to use, and I don't want to add that many more. It would be very helpful if the official version would change its policy.

**Comment by saturday06** [comment]
とはいえ、ICO球がそんなに使いやすいとは僕も思わないので、そのうち何らかの対応をします。ただ、公式のほうで対応してくれた方が独自処理の追加がなくて都合が良いです。

**Comment by saturday06** [comment]
However, I don't think the ICO sphere is that easy to use, either, so I will make some kind of support for it soon. But it would be more convenient if the official side handles it, since there is no additional proprietary processing.

**Comment by teresayawn** [comment]
”[Unexpected Sphere Artifacts Importing VRM 1.0 File In Blender 4.0](https://github.com/KhronosGroup/glTF-Blender-IO/issues/2073)”と題して、 glTFアドオンにもICO球の問題について報告しました。ご確認下さい。


"[[Unexpected Sphere Artifacts Importing VRM 1.0 File In Blender 4.0]](https://github.com/KhronosGroup/glTF-Blender-IO/issues/2073) I have also reported the issue of ICO spheres to the glTF add-on development team. Please review."

**Comment by teresayawn** [comment]
Duroure氏とやり取りを行いましたが、解決策は得られず、「Blender community forumsで質問して下さい」で終わりました。こちらが言いたかったことが正確に伝わったかどうか、心配ではありますが、これ以上専門的な話しにはついていけそうにないのでこちらから逃げた感じになってしまいました。申し訳ありません。

ちなみに、Blender4.0.2がstableになったので、それでも試しましたが、VRM1.0では、まだICO球表示のままでした。

**Comment by teresayawn** [comment]
lyuma, thank you. 
It seems my intention wasn't accurately conveyed. 
Unchecking the "Shapes" option has brought about what I desired.

Blender 4.0.2; VRM Add-on (v2.20.23)
![231207_02](https://github.com/saturday06/VRM-Addon-for-Blender/assets/146738533/3fe1fb48-363a-4abb-97af-0a077ebbbf60)

**Comment by lyuma** [comment]
The icosphere feature does not work properly for me.

Here's the example fox showing the icosphere and poorly visible bones:
![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/39946030/39015bc9-8904-4f44-bf93-14acf3496fac)
It's just an ominous icosphere at 0,0,0, and the selected bones in pose mode are just represented by a dashed line and are very difficult to see.

If I uncheck "Shapes", I get the result I want. Yes, I know the bones are pointing X-positive in this import. That is really important information. I need to be able to see this. Otherwise I'm working blind.
![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/39946030/b83cea2e-f1ff-4beb-a2d5-5326ee9bd9cc)

And since it's per-armature, it means another thing I have to do on each import. I never knew the Shapes checkbox existed before but maybe I can mention this in the documentation for the VRM and Godot tooling I work on.

**Comment by saturday06** [comment]
新しいバージョンのアドオンではインポート時の表示を角錐に戻しました。このイシューはResolvedとします
