### ISSUE TITLE
Some questions:

### ISSUE THREAD

**Issue by Supermagnum** [saturday06/VRM-Addon-for-Blender#385]
Hello, can I use the add on for a already rigged model ( done with auto rig)..

Do I have to create shape keys for mouth shapes ch o and so on?

**Comment by saturday06** [comment]
> Hello, can I use the add on for a already rigged model ( done with auto rig)..

Yes

Parent-child relationships of bones must follow the VRM Humanoid definition.
https://vrm.dev/en/univrm/humanoid/humanoid_overview.html#id3

> Do I have to create shape keys for mouth shapes ch o and so on?

Yes.

Please assign the shape key to VRM BlendShape Proxy.
