### ISSUE TITLE
Can't Edit Body Mesh

### ISSUE THREAD

**Issue by BonxBon** [saturday06/VRM-Addon-for-Blender#398]
When importing the vrm into blender, I can see the model and textures but only the bones are able to be edited. I can't edit the base mesh in either modeling or scultping. I tried downloading older versions of blender and this addon, but it still doesn't work. Does anyone know why this would be happening?

**Comment by saturday06** [comment]
Normally, you can edit the mesh as explained in the following video.
https://www.youtube.com/watch?v=34FBeC9mktE

I can help if you can tell me in more detail which step you're failing at.

**Comment by BonxBon** [comment]
Is there a specific version of both blender and the vrm addon I need to be using together? I know how to go into edit mode, but those editing tools or scultping tools are not there anymore, and it only lets me edit the bones. 
I tried the recommended versions, but maybe I got that wrong?

**Comment by saturday06** [comment]
The recommended version combination is the latest LTS version of Blender and the latest version of VRM Add-on for Blender. Currently, this is Blender 3.6.7 and VRM Add-on for Blender 2.20.23.

**Comment by saturday06** [comment]
> those editing tools or scultping tools are not there anymore

Could you please send me a screenshot so I can investigate?

**Comment by BonxBon** [comment]
![VRM](https://github.com/saturday06/VRM-Addon-for-Blender/assets/155675897/d93b55b3-c2aa-4c21-ad9e-bdc948f90aea)

**Comment by BonxBon** [comment]
I noticed it says body is baked(merged) could that by why? Would you perhaps know if that is a vroid studio problem?

**Comment by saturday06** [comment]
You are currently in Edit Mode for the Armature, so you cannot edit the Mesh. Selecting a mesh is not enough to enter the mesh's Edit mode.

You need to return to Armature's Object Mode. Then select the mesh and enter Edit Mode.

**Comment by BonxBon** [comment]
You are my hero, it worked, thank you! I'm brand new to editing humanoid models and I was selecting by dragging the mouse instead of just clicking on the body. XD
I really appreciate all your help <3
