### ISSUE TITLE
2.8 Not Importing

### ISSUE THREAD

**Issue by Metalraptor** [saturday06/VRM-Addon-for-Blender#4]
When importing a VRM file, it doesn't import the mesh, it does import the bones and the materials though.  I've had this issue with 2.8 since it was officially launched, I just replaced the addon with the latest version and it still seems to be happening.  Just wanted to mention this.

**Comment by iCyP** [comment]
I have not faced on this problem.
I can import VRM in Addon v076 and Blender2.80(steam) and latest daily build of blender.
You share VRM file, Json file in VRM or error message from blender,  if you want to resolve this issue. And if you don't share below, this issue will be closed as :can't fix: .

Thanks.

**Comment by Metalraptor** [comment]
Here is one of the VRMs I tried to import: 
https://drive.google.com/file/d/1C07DaiAqhr5DPz3lbmKgzeQu2xFvXmOl/view?usp=sharing

And a screenshot of what it looks like: 
https://drive.google.com/file/d/1GCAo2viYuNbLFXjCbhx8w6R5ia6hFagi/view?usp=sharing

Error message: 
```
"'Material' object has no attribute 'shadow_method'
location: <unknown location>:-1"
```

I hope this helps.

**Comment by iCyP** [comment]
From your screen shot, Icons of black and white only means your blender is older blender2.80 may before official release.
Please update your blender over official 2.80 version.
 I tried import your vrm by blender 2.80 official win64 version [[Link]](https://www.blender.org/download/Blender2.80/blender-2.80-windows64.zip/) and it success.
![コメント 2019-10-14 100148](https://user-images.githubusercontent.com/3232308/66725189-fae81000-ee69-11e9-9ed1-e25a39c76cfd.jpg)

Thanks.

**Comment by Metalraptor** [comment]
That's odd, I remember reinstalling the latest version of Blender 2.8 after the official release came out, I'll look into this and see if it fixes the issue.  Thank you for pointing that out. :)

**Comment by Metalraptor** [comment]
That fixed it. :) 
https://drive.google.com/file/d/12wINfiiO0z4lHnGFVZbUdHNqtRd2VuPv/view?usp=sharing

I had to reinstall 2.8 and that did the trick, thank you for noticing that! :D

**Comment by iCyP** [comment]
Have nice days.
