### ISSUE TITLE
Bug report: armature changes not exported

### ISSUE THREAD

**Issue by incompetentcoder** [saturday06/VRM-Addon-for-Blender#419]
blender 4.0 on linux with vrm add on 2.20.28
I have a vrm i edited successfully before but on export the edits to a spring bone are not applied and always reverted when i export and reimport as vrm. in blender itself it looks all fine. I even tried deleting the bones and recreating them and recreating the spring bone group but it still reverted size and rotation of the spring bones. the other issue is a lower body bone that is connected to one of the leg bones - making the leg not connected and moving the lower body bone to the middle and exporting and importing reverts that as well. I am very nonplussed as everything else i edited worked fine and applied. Do i have to delete all spring/collider groups when editing something so it isn't cached in some way maybe?

**Comment by saturday06** [comment]
VRM Add-on does not have a cache for object coordinates, rotation, or scaling. I couldn't cause that bug with Blender 4.0 on Windows 11 or macOS Sonoma. Please let me know your Linux distribution name, version, and cpu architecture so I can investigate.

**Comment by incompetentcoder** [comment]
thank you i just retried it with completely deleting the springbone collection the bones were part of and collider groups - i noticed that recreating the collider group then would spawn the collider at a place offset from where it was to where i had moved the bone - going into edit and out of it and then recreating the collider group at least made the collider show up in the right place but exporting then still made the springbones point wrong and the leg bone connected to the lower body bone and the lower body bone extended to the lower left to the leg bone. I am on archlinux x86_64,  update state is november 23 with blender 4.0.2 and vrm addon 4.20.28. attached is how it is in the .blend before exporting to the left and to the right what happens if i import that exported vrm back into blender, chest are the spring bones and lower body connected to the left thigh on the imported vrm
![2024-02-07-190730_1366x734_scrot](https://github.com/saturday06/VRM-Addon-for-Blender/assets/23316994/85519134-10ec-424b-849a-cc7e82d69edb)
 
the vrm is rather huge but i could also provide it if that would help - it's about 30 megs tho. i could just throw it on my github and link you if needed

**Comment by saturday06** [comment]
I understand.

VRM 0.0 cannot save bone rotation and scaling to files. Save only the position. If you rotate or scale bones, that information will not exist in the exported VRM 0.0. If you reload VRM0.0, it will behave as if the rotation and scaling have disappeared.

> https://github.com/vrm-c/vrm-specification/tree/ad14db33ba68d2cff0c09d6c7e2961328bacaae2/specification/0.0#vrm-rules
> No local rotation for bone
> No scale for bone

VRM 1.0 now saves bone rotation and scaling. It is possible that this problem can be improved. However, since the direction of bone progression is not defined, another problem may remain.

**Comment by incompetentcoder** [comment]
Ah i see, thank you. I guess I can just try exporting as vrm 1.0 then, thanks for the explanation! Marking this as closed
