### ISSUE TITLE
Bug report : バグ報告

### ISSUE THREAD

**Issue by xenodorian** [saturday06/VRM-Addon-for-Blender#42]
I've tried various VRM importer addons for various versions of blender, and I keep getting error messages. Is there any chance someone could just email me a working copy of their blender 2.whatever folder from their program files? I don't care which version of blender, I just want it to work.

**Comment by saturday06** [comment]
> a working copy of their blender 2

here https://1drv.ms/u/s!ArBnN9uqKBlwpUoANmXeBdqvs5-q?e=PAeScp

What kind of error did you get?
I would like to see a screenshot of what kind of error occurred.

**Comment by xenodorian** [comment]
> > a working copy of their blender 2
> 
> here https://1drv.ms/u/s!ArBnN9uqKBlwpUoANmXeBdqvs5-q?e=PAeScp
> 
> What kind of error did you get?
> I would like to see a screenshot of what kind of error occurred.

I received this error trying to load the code: https://i.imgur.com/9BngIjw.png
Which is why I was asking someone send me this file: https://i.imgur.com/G0JWHdX.png   with the addon already installed

**Comment by xenodorian** [comment]
> > a working copy of their blender 2
> 
> here https://1drv.ms/u/s!ArBnN9uqKBlwpUoANmXeBdqvs5-q?e=PAeScp
> 
> What kind of error did you get?
> I would like to see a screenshot of what kind of error occurred.

Also, thank you for trying to help :)

**Comment by saturday06** [comment]
I see. I think your addon installation folder is broken.
Please Try the following steps.

- Remove `C:\Users\(Your user name)\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons` folder
- Restart Blender 2.91
- Reinstall addon

**Comment by saturday06** [comment]
> Which is why I was asking someone send me this file: https://i.imgur.com/G0JWHdX.png with the addon already installed

Sorry. I don't know how to install the addon into blender program folder.

**Comment by xenodorian** [comment]
> I see. I think your addon installation folder is broken.
> Please Try the following steps.
> 
> * Remove `C:\Users\(Your user name)\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons` folder
> * Restart Blender 2.91
> * Reinstall addon

that worked! thanks so much! follow up question: I see two VRM export extensions: https://i.imgur.com/mj9Sof8.png there are two .vrm's. Does it matter which one I use?

**Comment by saturday06** [comment]
It should be a bug. I think you can use either. The bug occurs when the plugin is enabled or disabled multiple times. I'll fix it.
Or it occurs when multiple plugins are installed. In that case, please uninstall old plugin.

**Comment by xenodorian** [comment]
> It should be a bug. I think you can use either. The bug occurs when the plugin is enabled or disabled multiple times. I'll fix it.
> Or it occurs when multiple plugins are installed. In that case, please uninstall old plugin.

Thanks, I fixed it.

**Comment by saturday06** [comment]
👍

**Comment by saturday06** [comment]
done
