### ISSUE TITLE
Error when importing a vrm 1.0 file to UE5 with vrm4u, after having it exported in Blender.

### ISSUE THREAD

**Issue by beepboobbeep** [saturday06/VRM-Addon-for-Blender#429]
## Describe the bug

I can directly import a unmodified 1.0 file to ue with no error. However, when importing it first to Blender and then exporting it, the ue importer will throw an error. 
Log:
"LogVRM4ULoader: GetVRMMeta:std::stringFileName=㩃唯敳獲䐯癡摩慇業杮䐯獥瑫灯㌯⽤潤⁡档牡⽡牶⽭慤楬桡瘮浲
LogVRM4ULoader: GetVRMMeta: filesize=18345432
LogVRM4ULoader: GetVRMMeta: mScenePtr=0000000000000000
LogSlate: Window 'VRM Import Options' being destroyed
LogVRM4ULoader: VRM:(0.016 secs) ReadFileFromMemory
LogVRM4ULoader: Warning: VRM4U: read failure.
LogUObjectHash: Compacting FUObjectHashTables data took   0.38ms
LogSlate: Window 'Message' being destroyed
Message dialog closed, result: Ok, title: Message, text: Failed to import 'C:/Users/Gaming/Desktop/3d/doa chara/vrm/daliah.vrm'. Failed to create asset '/Game/NewFolder1/daliah'.
Please see Output Log for details.
LogAssetTools: Warning: Failed to import 'C:/Users/Gaming/Desktop/3d/doa chara/vrm/daliah.vrm'. Failed to create asset '/Game/NewFolder1/daliah'.
Please see Output Log for details.
LogAutomationController: Ignoring very large delta of 5.22 seconds in calls to FAutomationControllerManager::Tick() and not penalizing unresponsive tests
LogSlate: Took 0.000737 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/DroidSansFallback.ttf' (3848K)
LogSlate: Last resort fallback font was requested. Font: '../../../Engine/Content/Slate/Fonts/DroidSansFallback.ttf', Character: '㩃 (U+3a43)'
LogSlate: Took 0.001227 seconds to synchronously load lazily loaded font '../../../Engine/Content/SlateDebug/Fonts/LastResort.ttf' (5269K)"

## To Reproduce

Import 1.0 vrm file to Blender
Export vrm 1.0 file
Import it to ue5, error

## Expected behavior

After importing it, there should be files generated in ue.
It works without problems with 0.0 files.

## Desktop (please complete the following information)

Win10 Prof.
Blender 4.02, also tested on Blender 3.6.7
Addon version 22032 
Unreal Engine 5.3
VRM4U 20240212

**Comment by saturday06** [comment]
Thank you for the report. I'll investigate. Is your Unreal Engine version 5.3.2?

**Comment by beepboobbeep** [comment]
Yes, I have the version 5.3.2.

**Comment by saturday06** [comment]
Now, when I made VRM4U read the official VRM 1.0 sample model ( https://github.com/vrm-c/vrm-specification/blob/master/samples/VRMC_materials_mtoon_UV_Animation_Test/vrm/VRMC_materials_mtoon_UV_Animation_Test.vrm ), the same error as yours occurred. (Windows 11, Unreal Engine 5.3.2, VRM4U_5_3_20240212.zip)

I think this is probably a bug in VRM4U, so please file a bug report for VRM4U.

<img src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/1cf47e14-9347-49a8-9a1f-9f09373e6198" width="800">
