### ISSUE TITLE
Bug report: i dont know this bug or not but i cant export and stuck on this problem

### ISSUE THREAD

**Issue by susus002** [saturday06/VRM-Addon-for-Blender#445]
im trying to export my file in blender to vrm file, but there one problem

![_ Vrm C001  D__OBJ_Arzuka (Akirav2)_Vrm C001 blend  - Blender 4 0 20_03_2024 22_06_37](https://github.com/saturday06/VRM-Addon-for-Blender/assets/164206589/0f04f4e3-e8d2-494a-8c8b-42175481b338)

in windows 10
im  use blender 4.0 
with addons vrm 2_3_22

![_ Vrm C001  D__OBJ_Arzuka (Akirav2)_Vrm C001 blend  - Blender 4 0 20_03_2024 22_28_44](https://github.com/saturday06/VRM-Addon-for-Blender/assets/164206589/15743a86-ac78-4d35-a3ab-b527a13b390f)

i can export vrm.1.x but not VRM 0.x
im also add pose lib on Vrm T-pose but nothing happen still have same problem, pose section under pose lib dint show any mark
also using vrm from Vroid, and import chara model to blender then export without any modif to file, still found same problem

**Comment by saturday06** [comment]
Thanks for reporting!

VRM Add-on 2.3.22 you are using does not support Blender 4.0. Please update to the latest version, 2.20.35.
