### ISSUE TITLE
バグ報告: VRM 0.x Spring Bone の順序入れ替えが正常に動作しない

### ISSUE THREAD

**Issue by hiro-0511** [saturday06/VRM-Addon-for-Blender#482]
## バグについて

VRM 0.x Spring Bone -> Spring Bone Groups
で順序を入れ替えるボタンの「▼」が「▲」と同じ動作をします。

( move_down_vrm0_secondary_animation_group )

## バグの再現方法

VRM 0.x Spring Bone -> Spring Bone Groups にある、
「＋」ボタンで項目を3個以上追加し、それぞれ異なる名前(コメント)を付ける。

2番目の項目を選択し「▼」をクリックすると、選択項目が上に移動する。

## 期待する動作

「▼」クリック時に選択した項目が下に移動してほしいです。

## PC環境情報

- OS: [Windows]
- Blenderのバージョン [4.1.1]
- アドオンのバージョン [2.20.48]

**Comment by saturday06** [comment]
ご報告ありがとうございます！

こちらは先程リリースしたバージョン2.20.49で修正を行い、移動方向が正しくなりました。お試しください

**Comment by hiro-0511** [comment]
お疲れ様です。素早い対応ありがとうございます！
