### ISSUE TITLE
Bug report: Texture Interpolation not respected - linear makes blurry image in pixelart. 

### ISSUE THREAD

**Issue by heksik** [saturday06/VRM-Addon-for-Blender#491]
## Describe the bug

In Pixelart there are small textures like 64x64. Blender by default make them blurry so in node editor interpolation has to be changed from default linear to Closest - OK.
In VRM editor when user imports VRM default value in texture interpolation is "linear" - OK.
After change interpolation to "closest" and export, output texture is blurry ignoring interpolation settings.

## To Reproduce

1. Create any object and use low resolution 64x64 for texture painting in blender. 
2. Change image interpolation in node editor from default linear to closest to have pixel perfect view
3. Export VRM and it's blurry in Unity. 
Probably image/png included in VRM file generated by blender is not respecting this attribute.

## Expected behavior

Texture in VRM file should looks the same like in Blender. 

Workaround:
Increase texture size to look the same in default linear image interpolation. 

## Screenshots

![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/69304554/7a8b0ec5-b489-4f77-9e63-8dbe0c551117)

## Desktop (please complete the following information)

- Blender 4.1
- Addon 2.20.49

## Additional context

 Probably something like to add somewhere:
if node.type == 'TEX_IMAGE':
 node.interpolation = 'Closest' 
 
 Shader.py
 Suggests it's somehow implemented in the code but not working. 
     # blender is ('Linear', 'Closest', 'Cubic', 'Smart')
    # glTF is Linear, Closest
    filter_type = GL_NEAREST if from_node.interpolation == "Closest" else GL_LINEAR

**Comment by saturday06** [comment]
Thanks for reporting!

This is a bug and will be fixed in a future version.

You can change export settings in material properties. However, it is not reflected in the viewport.

![スクリーンショット 2024-06-02 18 40 26](https://github.com/saturday06/VRM-Addon-for-Blender/assets/532872/a30f45a5-ed9b-442f-ba69-3295ead0da72)

**Comment by saturday06** [comment]
The bug was fixed with the latest version v2.20.51 just released. Thank you for your report.
