### ISSUE TITLE
Bug report: debug print statements cause severe slowdowns

### ISSUE THREAD

**Issue by Valerie-Bosco** [saturday06/VRM-Addon-for-Blender#499]
## Describe the bug

the add-on has debug log turned on by default, this is causing the print statements of the kind `[VRM Add-on:DEBUG] The duration to determine look at preview updates is 0.000028300 seconds` to severely slowdown blender, the debug settings should be either toggle-able in the preferences or off by default

not machine dependent, purely relies on the add-on design

**Comment by saturday06** [comment]
The bug was fixed with the latest version v2.20.52 just released. Thank you for your report.
