### ISSUE TITLE
Bug report : The addon install but is not working.

### ISSUE THREAD

**Issue by yugo-harago** [saturday06/VRM-Addon-for-Blender#5]
**Describe the bug ：バグについて**

After I click in Install from Blender Preferences > Addon I can't see the vrm import in the file imports.

**To Reproduce：バグの再現方法**
1. Go to Blender Preferences, Addon, ,
2. Click on Install addon
3.  Select VRM_IMPORTER_for_Blender2_8-master.zip
4. The vrm doesn't appear.

**Expected behavior：期待する動作**
I wish to see the vrm import like in the tutorial.

**Screenshots：スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。
The screen shots after installed.
![ScreenShot After install](https://user-images.githubusercontent.com/6818358/73316337-5b307100-4211-11ea-88c6-f7d6d3f045b2.png)
![ScreenShot After install2](https://user-images.githubusercontent.com/6818358/73316440-9f237600-4211-11ea-9f7c-e65e03e6a067.png)

**Desktop (please complete the following information):PC環境情報**
 - OS: Windows 10
 - Blender 2.81a
 - Addon Version 0, 78

**Additional context ：なにか他に書いておきたいことはこちらへ**
The Blender console:
Load Handler:
addon_utils.disable: VRM_IMPORTER_for_Blender2_8-master not disabled
Modules Installed (VRM_IMPORTER_for_Blender2_8-master) from 'C:\\Users\\yugoh\\Documents\\3D\\Blender\\Addon_2019\\Addon\\VRM_IMPORTER_for_Blender2_8-master.zip' into 'C:\\Users\\yugoh\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'

In the  log says:
Modules Installed (VRM_IMPORTER_for_Blender2_8-master) from 'C:\\Users\\yugoh\\Documents\\3D\\Blender\\Addon_2019\\Addon\\VRM_IMPORTER_for_Blender2_8-master.zip' into 'C:\\Users\\yugoh\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'

In \AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons the \VRM_IMPORTER_for_Blender2_8-master does exist

**Comment by iCyP** [comment]
There is this addon in TESTING tab, because this addon is under develop. 


![コメント 2020-01-29 125739](https://user-images.githubusercontent.com/3232308/73326910-3088fb80-4297-11ea-8e1f-c44cd5775bba.jpg)
Thank you.

**Comment by yugo-harago** [comment]
Oh noo!
SO SORRY, I forgot about that!
Solved!
完全にこの事を忘れていました、お騒がせして申し訳ございませんでした。
m（＿ ＿）m
