### ISSUE TITLE
バグ報告:  [VRM 0.x] Spring Bone のコライダー作成で意図しない動作になる

### ISSUE THREAD

**Issue by hiro-0511** [saturday06/VRM-Addon-for-Blender#510]
## バグについて

VRM 0.x において、Spring Bone のコライダーを作成したとき、
以前のバージョン (以下で確認)
Blender [3.6.4]
VRM Add-on for Blender [2.16.2]
では正常に動作していましたが、最近のバージョンではコライダーを作成したとき、意図しない位置に作成され、意図しないタイミングで移動してしまいます。

## バグの再現方法

① 「VRMモデルを作成」をクリックします。(既存の VRM モデルでも再現可能です)

② 「VRM 0.x Spring Bone」から「Collider Groups」欄の「＋」をクリックします。

③ 作成されたグループでボーンに Hips を設定します（どこでも OK です）

④ グループの「Colliders」の「＋」をクリックするとコライダーが原点座標に作成されます。（本来なら Hips に作成されてほしい）

⑤ 「Collider Groups」欄の「＋」をクリックします。

⑥ 手順⑤で作成されたグループでボーンにいずれかのボーンを設定します（どこでも OK です）

⑦ 手順③で設定したボーン (今回は Hips) にコライダーが移動してしまいます。

## なにか他に書いておきたいことはこちらへ
手順⑤以降でコライダーが移動するのは 1 回のみです。
手順④と⑤の間に、コライダーを移動させていた場合、⑤以降の操作をした場合、コライダーの位置が更に移動します。

## 期待する動作

手順④でコライダーが原点ではなく、手順③で設定したボーンに作成されてほしいのと、
手順⑤以降の操作でコライダーが移動してほしくないです。

## PC環境情報

    OS: [Windows]
    Blenderのバージョン [4.1.1]
    アドオンのバージョン [2.20.60]

**Comment by saturday06** [comment]
バグ報告ありがとうございます！

先ほどリリースした最新版の2.20.61で修正いたしました。お試しください！

**Comment by hiro-0511** [comment]
お疲れ様です。
迅速な対応ありがとうございます！
