### ISSUE TITLE
The texture was not giving me the actuall vrm materials

### ISSUE THREAD

**Issue by Alexiandroid** [saturday06/VRM-Addon-for-Blender#52]
Hi goodmorning, i downloaded the file yesterday and after installing successfully, i then import the vrm into blender 2.8 version, it opened but still the texture was not giving me the actuall vrm materials i download from vroid, you can see it but it was like transperent and blur, i tried to work on it manually by using texture painting in blender it worked, what do i need to do so i dont do it over again, not all the mesh part became clear.

**Describe the bug :バグについて**
どのようなバグが起きているのか書いてください。

**To Reproduce:バグの再現方法**
バグが発生する手順を書いてください。
バグが発生するモデルのファイルやそのURL、エラーメッセージを添付してもらえると助かります。

**Expected behavior:期待する動作**
どうのようにバグを直してほしいか書いてください。
**Screenshots:スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。
**Desktop (please complete the following information):PC環境情報**
 - OS: [e.g. Win,Mac,ubuntu,Fedora,...]
 - Blender [e.g. 2.80,2.81...]
 - Addon Version [e.g. 076]

**Additional context :なにか他に書いておきたいことはこちらへ**

**Comment by saturday06** [comment]
Changing `View Transform` to `Standard` may works fine.

<img src="https://user-images.githubusercontent.com/532872/106356416-c50eb980-6342-11eb-8f9f-8531db27b8c1.png" width="500">

 The addon still doesn't perfectly reproduce VRM materials in blender viewport. I'll work for it.

**Comment by saturday06** [comment]
The title edited because it is too long.

**Comment by Alexiandroid** [comment]
Hi goodmorning, i downloaded the file yesterday and after installing successfully, i then import the vrm into blender 2.8 version, it opened but still the texture was not giving me the actuall vrm materials i download from vroid, you can see it but it was like transperent and blur, i tried to work on it manually by using texture painting in blender it worked, what do i need to do so i dont do it over again, not all the mesh part became clear The texture was not giving me the actuall vrm materials
![16120381081361344785799](https://user-images.githubusercontent.com/61583908/106367214-3cdbe480-6341-11eb-87e1-a676157eb6bc.jpg)
![1612038166278564377236](https://user-images.githubusercontent.com/61583908/106367233-5aa94980-6341-11eb-9efd-00f6b5c76ec8.jpg)
![161203819544530779355](https://user-images.githubusercontent.com/61583908/106367247-6c8aec80-6341-11eb-9668-aa844628d5da.jpg)

That is how it should come out. This is texture paint mode

**Comment by saturday06** [comment]
Changing `View Transform` to `Standard`  works fine for me. But the addon still doesn't perfectly reproduce VRM materials\. I'll work for it. Thanks.

**Comment by saturday06** [comment]
Can you send me your `.vrm` file for inspectation ? I couldn't confirm `transperent and blur`  I tried importing vroid sample model "vivi" and "darkness_shibu".

**Comment by saturday06** [comment]
Fixed in add-on version 1.8.0 which released just a while ago. Thanks for reporting !!!

![image](https://user-images.githubusercontent.com/532872/113771515-6c063c00-975e-11eb-895a-c0ffde29a60c.png)
