### ISSUE TITLE
Bug report: Blend shapes don't work except for blinking in game Virtual Droid 2

### ISSUE THREAD

**Issue by AgreSsorz** [saturday06/VRM-Addon-for-Blender#520]
Hello! 
I'm making a character for the game Virtual Droid 2. When checking the model by using Validate VRM Model, I see an error: 
Mesh "" doesn't have "" shape key. But blend shape group needs it. 
I've searched through many resources on modeling, but I still haven't found an answer. Please help.

Perhaps it is because of this error that Lip Sync does not work in the game using blend shapes.

![Screenshot](https://github.com/user-attachments/assets/855eb975-a73c-4f96-95db-75ee7257b78a)

Blend shapes work in Blender itself:

![Screenshot01](https://github.com/user-attachments/assets/77f37a46-9e98-4327-b284-21393def4cef)
![Screenshot02](https://github.com/user-attachments/assets/f0265946-f0cf-4c0f-9fef-2292297cc995)
![Screenshot03](https://github.com/user-attachments/assets/eb6c5685-8e03-4c64-a235-1ffe646803b4)
![Screenshot04](https://github.com/user-attachments/assets/5a427e2e-d409-4d87-bbfb-7c8c8ef5bddd)
![Screenshot05](https://github.com/user-attachments/assets/260347d5-a8a3-438c-88b4-3df5ab52c1fc)

This is the only thing that works in the game:
![Screenshot06](https://github.com/user-attachments/assets/042476e0-f03b-470f-8ff0-e9af3d2c4208)

- OS: Windows 10
- Blender 4.1
- Addon Version 2.20.61

**Comment by saturday06** [comment]
Thanks for reporting!

At least the message `mesh "" doesn't have "" shape key. But blend shape group needs it.` is broken. The latest version 2.20.64 fixes the message. Please try it.

**Comment by AgreSsorz** [comment]
Awesome! Updated the addon version and the error disappeared. Thank you very much for your help!
