### ISSUE TITLE
バグ報告: [VRM1.0] Blender 4.2以降のバージョンだとエクスポート時にExpressionが消える

### ISSUE THREAD

**Issue by furamon** [saturday06/VRM-Addon-for-Blender#535]
## バグについて

VRM1.0において、VRMをエクスポートしたときにExpressionが全部消滅します。
Blender4.1では保持されるので4.2でのみ起こるバグのようです。

## バグの再現方法

ExpressionのついたVRMファイルを「Blender 4.2以降で」エクスポートするとExpressionが全部消えている。

## 期待する動作

Blender4.2でもExpressionをエクスポートしたい。

## PC環境情報

- OS: [Windows11]
- Blenderのバージョン [4.2]
- アドオンのバージョン [2.20.71]

## なにか他に書いておきたいことはこちらへ

4.1から4.2でずいぶん破壊的変更があったようで大変だとは思いますが、よろしくお願いいたします。

**Comment by saturday06** [comment]
ご報告ありがとうございます！先ほどリリースした最新版の2.20.73でこちら修正しました。

4.2から、Blenderに同梱のエクスポートライブラリの仕様変更により、エクスポート時にモディファイアを適用する設定を行うとシェイプキーが消えるようになったみたいで、その影響を受けていました。当該設定を4.2以降で無効化することで対策しました。

しかし、この方法だとモディファイアの自動適用が無くなるので、ちょっと不便になってしまいます。

Blenderの仕様変更の理由は多分、モディファイアとシェイプキーの相性が悪くて出力結果がおかしくなることがあるのを避けてのことだと思うのですが、なんとなく動いてしまっていたので放置していました。

将来的には、シェイプキーがあるメッシュにモディファイアを可能な限り適用するようなものを自前で実装しようと思います。
