### ISSUE TITLE
Bug report : import error ... ?

### ISSUE THREAD

**Issue by rainy-color** [saturday06/VRM-Addon-for-Blender#55]
先日はbag対応ありがとうございました。
新しいバージョンがうまく動作しなかったので相談させてください。
(blender バージョンが 2.9 なのでそのせいかもしれませんが、以前のものは動いていたので…)

**Describe the bug :バグについて**
インポートするとエラーを出力します。

![20210320_vrmimporter_bugreport](https://user-images.githubusercontent.com/57064960/111853839-f3327200-895f-11eb-9963-01b96d413573.JPG)

そのモデルを何も手を加えない状態で”VRMモデルのチェック”をクリックするとエラーを出力します。

![20210320_vrmimporter_bugreport2](https://user-images.githubusercontent.com/57064960/111853868-01808e00-8960-11eb-9c40-edac64d82e53.JPG)

**To Reproduce:バグの再現方法**
1. ファイル > インポート > VRM からvrmモデルをクリックします
2. インポート時のエラーが発生します。
3. モデルに変更を加えない状態で、Nキー > VRMタブ >VRMモデルのチェック をクリックします。
4. エラーが発生します。

**Expected behavior:期待する動作**
正常にインポート/エクスポートできる方法を教えて下さい。

**Desktop (please complete the following information):PC環境情報**
- OS: win10
- Blender 2.90
- Addon Version 1.4.1

**Additional context :なにか他に書いておきたいことはこちらへ**

補足：
- VRM_IMPORTER_for_Blender-master を使用していました。
- 説明にある通り、以前のVRMのアドオンはリムーブしています。
![20210320_vrmimporter_bugreport3](https://user-images.githubusercontent.com/57064960/111854211-6ab4d100-8961-11eb-82ed-d7f627943454.JPG)
![20210320_vrmimporter_bugreport4](https://user-images.githubusercontent.com/57064960/111854213-6d172b00-8961-11eb-8edc-8a092e107ede.JPG)
- 必要に応じて、blenderファイルやvrmファイルなどをお渡しできます。

質問：他に3つほど質問があります。

- blender 2.9系は対応していませんか？
- collidarが生成されなくなったのは仕様ですか？
- マテリアルフォルダが生成されなくなったのは仕様ですか？

**Comment by saturday06** [comment]
バグレポートありがとうございます。調査いたします。


> blender 2.9系は対応していませんか？

対応している想定です。上手く動作しない場合はバグになります。

> collidarが生成されなくなったのは仕様ですか？

こちらの動作は変更していないです。そのため、おそらくインポートエラーが原因で生成されないのだと思います。

> マテリアルフォルダが生成されなくなったのは仕様ですか？

すみません、こちらは仕様になります。glTFインポーターと同様の動作をさせたいためです。以前と同じ動作にするには、インポートダイアログで「テクスチャ画像をフォルダに展開」をチェックしてください。

![無題](https://user-images.githubusercontent.com/532872/111871709-f6187b80-89ce-11eb-8dbb-b0e500ae62e2.png)

**Comment by saturday06** [comment]
@rainy-color エラーの原因が判明したため、すぐに修正します。2.9系の最新版であるBlender 2.92.0を使うとエラーが発生しないため、Blenderのバージョンアップも併せてお試しいただければと思います。

**Comment by rainy-color** [comment]
返信ありがとうございます。
マテリアルフォルダが生成されなくなったのが仕様だという件、了解しました。
インポートできるようになったら動作を確認してみたいと思います。

現状はAddonを前のものに戻して使用してます。
また、必要であればファイルを送付することもできますので、よろしくおねがいします。

**Comment by rainy-color** [comment]
修正いただけるとのこと、ありがとうございます。
現在、作業中のファイルがあり、これが来週には片付く見込みですので、その後、blenderのバージョンを上げて確認してみようかと思います。

**Comment by saturday06** [comment]
先ほど報告いただいたバグの修正バージョン 1.4.2 をリリースしました。作業が落ち着いたらご確認いただければと思います。報告ありがとうございました。

**Comment by rainy-color** [comment]
了解しました。
ありがとうございます。
