### ISSUE TITLE
Bug report : バグ報告  Can't export shapekeys.

### ISSUE THREAD

**Issue by IKAKUNE** [saturday06/VRM-Addon-for-Blender#56]
**Describe the bug :バグについて**
表情を出力できなくなっていました。

**To Reproduce:バグの再現方法**
表情の付いたモデル(BlendShape も設定済み)をエクスポートする。
エクスポートダイアログに'メッシュ「Head」が見つかりません。テキストエディタの「blendshape_group.json」を修正してください。'などと表示される。
Unity や外部ソフトで確認しても、シェイプキーが出力されていない。

**Expected behavior:期待する動作**
手元で修正した結果、とりあえず動作するようになりましたので査読と修正をお願いいたします。

 io_scene_vrm/misc/glb_factory.py | 2 +-
 io_scene_vrm/misc/vrm_helper.py  | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/io_scene_vrm/misc/glb_factory.py b/io_scene_vrm/misc/glb_factory.py
index 0e4d51b..08462ba 100644
--- a/io_scene_vrm/misc/glb_factory.py
+++ b/io_scene_vrm/misc/glb_factory.py
@@ -1735,7 +1735,7 @@ class GlbObj:
                     }
                 primitive_list.append(primitive)
             self.json_dic["meshes"].append(
-                OrderedDict({"name": mesh.data.name, "primitives": primitive_list})
+                OrderedDict({"name": mesh.name, "primitives": primitive_list})
             )
             bm.free()
             # endregion hell
diff --git a/io_scene_vrm/misc/vrm_helper.py b/io_scene_vrm/misc/vrm_helper.py
index 739eeda..7e27152 100644
--- a/io_scene_vrm/misc/vrm_helper.py
+++ b/io_scene_vrm/misc/vrm_helper.py
@@ -577,7 +577,7 @@ class WM_OT_vrmValidator(bpy.types.Operator):  # type: ignore[misc] # noqa: N801
                 return make_json_return_value(json_as_dict)
 
             mesh_name_to_mesh = {
-                obj.data.name: obj.data for obj in export_objects if obj.type == "MESH"
+                obj.name: obj.data for obj in export_objects if obj.type == "MESH"
             }
             # region humanoid_parameter
             text_block_name_to_json("humanoid_params")

**Screenshots:スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。
**Desktop (please complete the following information):PC環境情報**
 - OS: [e.g. Win,Mac,ubuntu,Fedora,...]
 - Blender [e.g. 2.80,2.81...]
 - Addon Version [e.g. 076]

**Additional context :なにか他に書いておきたいことはこちらへ**
アドオン、とてもありがたく使わせていただいております。
github の使い方に慣れていないため、このようなテキストベースでの報告となってしまい、申し訳ありません。

**Comment by saturday06** [comment]
ありがとうございます！調査いたします。ただ、申し訳ないのですがこちらの不具合は最近のアップデートによって一部互換性が壊れたのが原因のように思えます。修正か、あるいは回避方法をお伝えするため少々お待ちください。

**Comment by saturday06** [comment]
こちらのバグの修正を、先ほどリリースした最新バージョン1.7.2へ反映しました。いただいたコードでは現在 `mesh.data.name` となっていたところを `mesh.name` に変更していただいてましたが、古いバージョンのアドオンでVRMをインポートすると `mesh.name` に、新しいものでは `mesh.data.name` に正しい名前が入るようなので、互換性のためどちらに入っても大丈夫なようにする変更を入れました。ご報告ありがとうございました！。
