### ISSUE TITLE
Bug report : バグ報告  Can't export normal maps.

### ISSUE THREAD

**Issue by IKAKUNE** [saturday06/VRM-Addon-for-Blender#57]
**Describe the bug :バグについて**
ノーマルマップテクスチャがエクスポートされません。

**To Reproduce:バグの再現方法**
ノーマルマップテクスチャを設定した MToon マテリアルを使ったモデルを出力する。
Unity や外部アプリで確認すると、ノーマルマップテクスチャが出力されていない。

**Expected behavior:期待する動作**
'NomalmapTexture' の typo がらみのバグのようです。
とりあえず手元では修正できましたので、査読と修正をお願いいたします。

 io_scene_vrm/misc/glb_factory.py | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/io_scene_vrm/misc/glb_factory.py b/io_scene_vrm/misc/glb_factory.py
index 08462ba..1b8529e 100644
--- a/io_scene_vrm/misc/glb_factory.py
+++ b/io_scene_vrm/misc/glb_factory.py
@@ -476,6 +476,12 @@ class GlbObj:
         def get_texture_name_and_sampler_type(
             shader_node: bpy.types.Node, input_socket_name: str
         ) -> Optional[Tuple[str, int, int]]:
+            if (
+                input_socket_name == "NormalmapTexture"
+                and "NormalmapTexture" not in shader_node.inputs
+                and "NomalmapTexture" in shader_node.inputs
+            ):
+                input_socket_name = "NomalmapTexture"
             if (
                 not shader_node.inputs.get(input_socket_name)
                 or not shader_node.inputs.get(input_socket_name).links

**Desktop (please complete the following information):PC環境情報**
 - OS: [e.g. Win,Mac,ubuntu,Fedora,...]
 - Blender [e.g. 2.80,2.81...]
 - Addon Version [e.g. 076]

**Additional context :なにか他に書いておきたいことはこちらへ**
前回に続き、テキストでのご報告にて申し訳ありません。
どうぞよろしくお願いいたします。

**Comment by saturday06** [comment]
報告、修正コードのご提供ありがとうございます。こちら確認の上反映させていただきます 🙇

**Comment by saturday06** [comment]
こちら、頂いたコードを[そのまま使わせていただきました](https://github.com/saturday06/VRM_Addon_for_Blender/commit/7ebc5068aefd4ef226d07d7c66bbb8cedc95eff1)。先ほどリリースした現在の最新版1.7.2に反映しました。ありがとうございます！
