### ISSUE TITLE
Bug report: VRM1.0: Mesh with modifiers is duplicated on export

### ISSUE THREAD

**Issue by rcelyte** [saturday06/VRM-Addon-for-Blender#571]
## Describe the bug

Exporting a mesh with modifiers as VRM 1.0 adds the post-modifier mesh to itself.

## To Reproduce

1. Click 'Create VRM Model' and set spec version to 1.0
2. Add a mesh with any generative modifier (array, mirror, etc.)
3. Export VRM multiple times
4. Observe multiplying geometry

## Video

https://github.com/user-attachments/assets/d7afc70e-0106-4c40-b7cd-b6254429e1af

## Desktop

- Blender version 4.2.1
- Addon version 2.20.86

**Comment by saturday06** [comment]
Thanks for your report!

The bug has been fixed in the latest version 2.20.87 just released. Please try it.

**Comment by rcelyte** [comment]
That fixed it :+1:
