### ISSUE TITLE
Bug report: Mesh Export Broken in Blender 4.2.1, latest addon version 2.20.87

### ISSUE THREAD

**Issue by tdw46** [saturday06/VRM-Addon-for-Blender#573]
## Describe the bug

Several meshes that used to export without issue now won't export properly. I'm unsure if root cause is blender version change or addon code-base change.

## To Reproduce

1. Open this blender file in blender 4.2.1: [DeadBob.zip](https://github.com/user-attachments/files/17085141/DeadBob.zip)
2. Try to export in latest addon version ( RESULT : No mesh exported )
3. Try to export in addon version 2.20.82 ( RESULT : Mesh exported properly )
4. This is a totally separate example of a different mesh exporter related issue. Please also try to export this one: 
[Example 2.zip](https://github.com/user-attachments/files/17085286/Example.2.zip) It always exports a cube around the character. **This is still a problem in the older addon version 2.20.82.** I determined root cause of this was hidden mesh with armature modifier targeting desired export rig. Even if "Export Only Selected Objects" is set True, this object still exports even when unselected and hidden. 
![image](https://github.com/user-attachments/assets/79d0776a-77b3-4161-9ffb-89c758e1efa4)
 

## Expected behavior

Mesh should export properly on latest version as well.

## Screenshots

![Example 1](https://github.com/user-attachments/assets/b374dcd9-abd7-4846-9956-0e432cc654e8)
![Example 2](https://github.com/user-attachments/assets/09fc92ff-fb94-4c04-ac6b-3f7f8987f397)

## Desktop (please complete the following information)

- OS: Windows 11
- Blender 4.2.1
- Addon Version 2.20.82 - 2.20.87 (other versions not tested)

**Comment by saturday06** [comment]
Thanks for your report!

These bugs have been fixed in the latest version 2.20.88 just released. Please try it.
