### ISSUE TITLE
Bug report : バグ報告 1.4.0-1.7.2 インポートエラー

### ISSUE THREAD

**Issue by PommesDog** [saturday06/VRM-Addon-for-Blender#58]
久しぶりにバージョンアップしたら動かなくなってしまったので、報告致します。

**Describe the bug :バグについて**
VRMをインポートしようとした時にエラーします。

**To Reproduce:バグの再現方法**
Windows 10
Blender 2.8.3
VRM_Addon_for_Blender 1.4.0と1.7.2
(1.3.6だとインポート出来ます)
VRMをインポートしようとした場合

モデルデータがフルスクラッチで作って貰った物で高価すぎるので
ここに張り付けが出来なく、
saturday06さんに直接渡す方法があればお渡しできます

**Expected behavior:期待する動作**
新しいバージョンでもVRM をインポートできるようにして欲しい

**Screenshots:スクリーンショット**
1.7.2
![172](https://user-images.githubusercontent.com/43842191/113540892-0742c880-961c-11eb-954e-57018f5b3fb4.png)

1.4.0
![140](https://user-images.githubusercontent.com/43842191/113540874-001bba80-961c-11eb-9b2d-9a5579fbc6b4.png)

**Comment by saturday06** [comment]
報告ありがとうございます。最近のバージョンでアニメーションのデータもインポートするようになったのですが、何らかの原因でそのアニメーションのインポートに失敗してしまっているようです。こちら、インポートに失敗したらアニメーションを無視するようにすることで対応します。

**Comment by saturday06** [comment]
本当はアニメーションのインポート自体の処理を修正したいのですが、アニメーションのインポートはBlenderに搭載されているインポート機能を利用しているため、私の力でそれを修正するのが難しいという事情があります.....

**Comment by saturday06** [comment]
先ほどリリースしたバージョン1.7.3で修正完了しました。アドオンをバージョンアップして再度インポートが上手く行くか確認をお願いします 🙇

**Comment by PommesDog** [comment]
saturday06さん
1.7.3で確認しました。
無事にインポートができるようになりました。　早い対応ありがとうございます！

**Comment by saturday06** [comment]
確認ありがとうございます！動いて良かったです！
