### ISSUE TITLE
Bug report: Importing VRM model creates weird planes

### ISSUE THREAD

**Issue by khoin343** [saturday06/VRM-Addon-for-Blender#597]
Importing a VRM models create these weird planes once in a while. They can disappear and reappear at any time, but they usually pop up when posing. Trying to delete the plane also deletes the body.

1. Import a VRM model into Blender (in my case, I used a model from VRoid)
2. If it doesn't appear right away, pose the model (you may have to move many bones for it to appear)

![Screenshot From 2024-10-19 16-22-29](https://github.com/user-attachments/assets/787dadae-5a5a-4407-b980-b2967c15d277)
![Screenshot From 2024-10-19 16-25-01](https://github.com/user-attachments/assets/9db20e96-60c4-46f8-ad07-7bc6db36b211)

- OS: OpenSUSE Tumbleweed
- Blender 4.2
- Addon Version 2.20.88

**Comment by saturday06** [comment]
It worked correctly on my machine. Is it possible to upload your .vrm file here for investigation?

<img src="https://github.com/user-attachments/assets/a847abff-e474-4e79-ba05-f236ce4b646c" width="500">

**Comment by khoin343** [comment]
And it seems to have resolved itself. I probably just needed to restart Blender. Sorry for all the hassle.
