### ISSUE TITLE
編集モード→オブジェクトモードでColliderがずれる

### ISSUE THREAD

**Issue by nossori** [saturday06/VRM-Addon-for-Blender#6]
インポート直後の編集モードから、オブジェクトモードにblenderを切り替えると
複数のColliderが本来の位置からズレるようです。
このとき、アンドゥすると高確率でBlenderが落ちます。
メッシュ、ボーンに変化はありません。

blenderはまだ使い始めたばかりのため
理解不足からくる不備でしたら申し訳ありません。

環境
Blender 2.81a
VRM importer for 2.8 v0.78
VroidStudio 0.8.2

![d875d48323779711c9b01d2dc327064e](https://user-images.githubusercontent.com/60937409/74263061-6e7b2a80-4d41-11ea-855c-6a0264a67336.gif)
頭部Colliderが左に崩れているほうがオブジェクトモードに切り替え後です

**Comment by iCyP** [comment]
同環境で0.8.2のvitaをインポートしましたが再現しませんでした。(Blender2.81a(steam),VRM importer開発版(zipを直接インストールする方法でよく紹介されているもので入る))
ので、ちょっとわからないです。

> インポート直後の編集モードから

この点ですが、基本動作ではインポート直後はオブジェクトモードになっているはずです。何かエラーが出ておりませんでしょうか？

ただ、なんとなくですが、画像から2つの原因を予想します。
 1. ボーン構成が偏っていて、ボーンの向き決定にズレが生じている
 1. １で間違った方向に向いているボーンのロールを設定が原因

なので、インポート時のオプションにロール設定するかどうか（Set bone roll : デフォルトはTrue：する）のフラグを追加しましたので、アドオンを再インストールし、Set bone rollのチェックを外してインポートしてみてください。
お手数おかけしまして申し訳ありません。

![コメント 2020-02-12 125758](https://user-images.githubusercontent.com/3232308/74301725-51714680-4d97-11ea-987c-910cd83f393c.png)

**Comment by nossori** [comment]
お世話になります。
結論からいいますと、(フラグ追加された)アドオンを再インストールすることで解決しました。

> この点ですが、基本動作ではインポート直後はオブジェクトモードになっているはずです。何かエラーが出ておりませんでしょうか？

特にエラーはでていませんでした。
画像はimport vrmボタンを押してから完了するまでのログです
![キャプチャ](https://user-images.githubusercontent.com/60937409/74323462-e17bb400-4dc8-11ea-92b5-4c4eec278c74.JPG)
(0.8.2のvitaで試してみたところ、現象が再現したので今回はvitaを使って試行してみました)

> なので、インポート時のオプションにロール設定するかどうか（Set bone roll : デフォルトはTrue：する）のフラグを追加しましたので、アドオンを再インストールし、Set bone rollのチェックを外してインポートしてみてください。

先に書きましたとおり、新しいアドオン入れ直しで問題解決したのですが、
Set bone rollのオンオフに関係なく正常な動作をしました。
インポート直後のモードも、オブジェクトモードになりました。
(blenderは blender.orgからダウンロードして入れたものです)

ログの変化はimport_scene.vrm()直前のeditmode_toggleが
旧アドオンが1回、Set bone rollオフで0回、オンで2回といった変化くらいです。

インストール作業によるトラブルかと思い、手動で同じ手順で数度に渡り
新旧アドオンを交互に入れ直ししたのですが、旧アドオンの挙動は
前の報告通り変化はありませんでした。
(フォルダ名を含めパスも完全一致させています)

ちょっと不思議な感じですが、ともあれ無事解決しました。
今回は大変お手数をおかけしました。ありがとうございました。
もし追加で何か検証が必要でしたらお知らせください。

**Comment by iCyP** [comment]
詳細なご報告ありがとうございます。また、解決してよかったです。
再発するような報告が上がれば、さらに調査してみます。
ありがとうございました。
