### ISSUE TITLE
Feature request:要望 VRMパネルに表示するテキスト

### ISSUE THREAD

**Issue by FujiSunflower** [saturday06/VRM-Addon-for-Blender#60]
**Is your feature request related to a problem? Please describe.:バグじゃないけどアドオンの動作でなにか困ってることがあれば**
VRMパネルに条件分岐の結果ほぼ常時表示されるテキストは不要かと思いました。
![1](https://user-images.githubusercontent.com/20571538/114877340-26223580-9e3a-11eb-8b06-1bfcd97fcb69.png)

**Describe the solution you'd like:どう動いてほしいかをどうぞ**
モードに合っているものだけ表示される方が良い

**Describe alternatives you've considered:他にこんなんでもいいよ、というのがあれば**
カテゴリにパネルを複数用意するのも良いと思います。

**Additional context::なんかほかに書きたいことがあれば**
ついでに、VRMパネルで編集モードの際に表示している対称化機能は不要なのではないか
![2](https://user-images.githubusercontent.com/20571538/114877702-7f8a6480-9e3a-11eb-8c81-d318081fdab5.png)

**Comment by saturday06** [comment]
フィードバックありがとうございます 🙇 

確かに不要だと思うので削除してしまいます。現在出していただいているPull Requestのほうでついでに直していただいても問題無いです。

**Comment by FujiSunflower** [comment]
不具合修正とテキスト削除したものをプルリクとして一旦提出します。 #59

**Comment by saturday06** [comment]
ありがとうございます！
