### ISSUE TITLE
Feature request:要望 バージョンチェックが不要かも

### ISSUE THREAD

**Issue by FujiSunflower** [saturday06/VRM-Addon-for-Blender#61]
**Is your feature request related to a problem? Please describe.:バグじゃないけどアドオンの動作でなにか困ってることがあれば**
[バージョンチェック](https://github.com/saturday06/VRM_Addon_for_Blender/blob/420bc8e7f87d16f0eb04da60e2a8f58b5a0e0fe4/io_scene_vrm/__init__.py#L571)が用意されていますが、Blender側が[bl_info](https://github.com/saturday06/VRM_Addon_for_Blender/blob/420bc8e7f87d16f0eb04da60e2a8f58b5a0e0fe4/__init__.py#L18)から警告を出す仕様だったはずなので不要かもしれません。

**Describe the solution you'd like:どう動いてほしいかをどうぞ**
バージョンチェック処理の削除

**Additional context::なんかほかに書きたいことがあれば**
同様にBlender側がエラーを出す仕様のはずなので、[UnregisterでのRuntimeError](https://github.com/saturday06/VRM_Addon_for_Blender/blob/420bc8e7f87d16f0eb04da60e2a8f58b5a0e0fe4/io_scene_vrm/__init__.py#L596)は不要かもしれません。

**Comment by saturday06** [comment]
### バージョンチェックについて

こちらのバージョンチェックはversion.version()関数が正しく動作しているかどうかのチェックのため、できれば消さないでそのままにしておきたいです。version.version()関数の実装はかなりトリッキーなコードになっており、正しく動作していることを常に確認しておきたいのです。

### UnregisterでのRuntimeErrorについて

仰る通り、こちらは不要に思えるため削除します。ご指摘ありがとうございました！

**Comment by FujiSunflower** [comment]
了解しました。
