### ISSUE TITLE
Tips:知識 Blenderアドオンの「作法」

### ISSUE THREAD

**Issue by FujiSunflower** [saturday06/VRM-Addon-for-Blender#62]
Blenderアドオンの基本的な「作法」の知識が足りていないと感じているので、書かせて頂きます。
# アドオンのサンプル
Blenderはアドオンのサンプルを用意しています。
![1](https://user-images.githubusercontent.com/20571538/114962416-97e39900-9ea5-11eb-96bd-8fe57d497f48.png)
# アドオンのリファレンス
![2](https://user-images.githubusercontent.com/20571538/114962948-a7171680-9ea6-11eb-9ef9-e8260d7e8942.png)
# オペレーター
Blenderでの処理を行う際は[オペレーター](https://docs.blender.org/api/2.92/bpy.types.Operator.html)を起動します。
オペレーターで用意する基本的な関数が以下の3つです。
- [invoke()](https://docs.blender.org/api/2.92/bpy.types.Operator.html#bpy.types.Operator.execute)
- [execute()](https://docs.blender.org/api/2.92/bpy.types.Operator.html#bpy.types.Operator.execute)
- [modal()](https://docs.blender.org/api/2.92/bpy.types.Operator.html#bpy.types.Operator.modal)
## invoke()
オペレーターを['INVOKE_DEFAULT'](https://docs.blender.org/api/2.92/bpy.ops.html)で起動した際に実行される関数です。
BlenderをGUI操作した場合はこちらが起動されます。
[キーイベント](https://docs.blender.org/api/2.92/bpy.types.Event.html)などを使った処理の準備が可能です。
## execute()
オペレーターを['EXEC_DEFAULT'](https://docs.blender.org/api/2.92/bpy.ops.html)で起動した際に実行される関数です。
スクリプトで何も指定しない場合はこちらが起動されます。
オペレーターの実際の処理を担当します。
## modal()
マウスカーソルで操作するような処理を担当します。
invoke()で['RUNNING_MODAL'](https://docs.blender.org/api/2.92/bpy.types.Operator.html#modal-execution)を呼び出す必要があります。
## 返り値
 オペレーターの返り値は以下の4つの文字列の[集合](https://docs.python.org/ja/3/tutorial/datastructures.html#sets)です。
- 'RUNNING_MODAL'
- 'CANCELLED'
- 'FINISHED',
- 'PASS_THROUGH'
> そのためcast(Set[str], ~)と書くのは冗長かもしれません。
# プロパティ
Blenderでの変数を扱う際は[プロパティ](https://docs.blender.org/api/2.92/bpy.props.html)を使用します。
一方で、モジュール内のグローバル変数を使うことも出来ますが、こちらはBlenderの作業ファイルに保存されません。
# アドオンの登録と解除
[register()とunregister()](https://docs.blender.org/api/2.92/info_quickstart.html#example-operator)でアドオンの登録と解除を行います。
アドオンの登録の際にプロパティを[既存クラスに差し込む](https://docs.blender.org/api/2.92/bpy.props.html)ことで登録されます。
登録したプロパティはアドオンの解除の際に[削除します](https://docs.blender.org/api/2.92/info_quickstart.html#custom-properties)。

**Comment by saturday06** [comment]
ありがとうございます！勉強させていただきます 🙇

**Comment by saturday06** [comment]
勉強したため、こちらは解決とします。ありがとうございます！
