### ISSUE TITLE
Request for permission to change the license of @aVersionOfReality's Pull Requests

### ISSUE THREAD

**Issue by saturday06** [saturday06/VRM-Addon-for-Blender#624]
@aVersionOfReality Hello!

I request permission to change the OSS license for your Pull Request from "MIT" to "MIT or GPL-3.0-or-later multi-license" to meet [The Blender Extensions platform](https://extensions.blender.org/add-ons/vrm/)'s requirement.

- https://github.com/saturday06/VRM-Addon-for-Blender/pull/317
- https://github.com/saturday06/VRM-Addon-for-Blender/pull/346

Users can choose whether to use the MIT or GPL-3.0-or-later license. The copyright for the code in the Pull Request belongs to the author, @aVersionOfReality, so I need to ask for permission to change the license.

After considering it, if possible, I would like to receive a comment granting permission to change it.

**Comment by saturday06** [comment]
### Background

VRM-Addon-for-Blender is distributed on [The Blender Extensions platform](https://extensions.blender.org/add-ons/vrm/) for Blender 4.2 and later. However, [from August 22, 2024, the license for add-ons that can be distributed has been limited to GPL-3.0-or-later](https://extensions.blender.org/approval-queue/vrm/#activity-2783). The platform is very convenient, and I want to use it, so I wanted to change the license.

### What kind of work is @saturday06 trying to do specifically?

In order to change the license of the source code, it is necessary to obtain consent from the person who wrote the source code (https://www.reddit.com/r/opensource/comments/aq63ow/comment/ege3pp5/). For this reason, I am working to get permission from each contributor. In addition, if consent cannot be obtained, the relevant part of the source code will be excluded or rewritten from scratch.

### What is the impact of the license change on the code that @aVersionOfReality sent as a pull request?

At present, there will be no impact. In the future, when a new GPL license is issued, there is a minimal possibility of an effect, less than 0.001%. The GNU site currently says the MIT (X11) license is compatible with the GNU GPL license.

https://www.gnu.org/licenses/license-list.en.html#X11License

However, this will not be the case in the future. Because Blender requires a license of GPL-3.0-or-later, it is unclear what the licenses of GPL-4.0 and GPL-99.99, which have not yet been issued, will be. For example, if GPL-4.0 is published as public domain, there is a risk that the MIT license's restriction to "keep the original author's copyright notice" will become invalid.

But if that were to happen, the "compatible" statement on the GNU website would be retracted, and I think there would be a huge fuss involving Blender itself and OSS around the world, so I guess it's a risk that can be ignored.

### Why not switch completely to the GPL but instead use "multi-license"?

The main reason is that the impact on users of the license change is less.
To be honest, I also wanted to try using a special license, and I also had an excuse to use it.

### See also

The information is also summarized in the following issue:

- https://github.com/saturday06/VRM-Addon-for-Blender/issues/548.

That's all. Thank you for reading this far and for your understanding. Please consider my request.

**Comment by aVersionOfReality** [comment]
Yes, this is no problem. Permission granted. Please let me know if I need to do anything else.

**Comment by saturday06** [comment]
Thank you very much!

I have one more request.

Would you also permit me to use the efficient method you showed in your issue, “Layer Weight Node”?

- https://github.com/saturday06/VRM-Addon-for-Blender/issues/314
  <img src="https://github.com/saturday06/VRM-Addon-for-Blender/assets/36803956/e6f008ae-e504-44ec-97df-496c3ba7b088" width="300">

I imported this without using a pull request, so it was omitted from the initial request.

**Comment by aVersionOfReality** [comment]
Yup, that's fine too. I hope it all helps!

**Comment by saturday06** [comment]
Thank you! You've been a great help!
