### ISSUE TITLE
Feature request:要望 カスタムプロパティの使用を止めたい

### ISSUE THREAD

**Issue by FujiSunflower** [saturday06/VRM-Addon-for-Blender#63]
**Is your feature request related to a problem? Please describe.:バグじゃないけどアドオンの動作でなにか困ってることがあれば**
[VRMの変数などをカスタムプロパティで保存](https://github.com/FujiSunflower/VRM_Addon_for_Blender/blob/3dffab943b88f59d78ea16a985d700552175114f/io_scene_vrm/misc/make_armature.py#L516)していますが、今後のアップデートが複雑になるため使用を止めたいです。
プロジェクト全体に影響が発生する変更ですので、段階的な対応で良いと思います。

**Describe the solution you'd like:どう動いてほしいかをどうぞ**
代わりに下記のように[register()](https://github.com/saturday06/VRM_Addon_for_Blender/blob/3dffab943b88f59d78ea16a985d700552175114f/io_scene_vrm/__init__.py#L678)でプロパティグループを用意して、そちらを呼び出すようにします。
```
class VRMProps(bpy.types.PropertyGroup):
    boo0: bpy.props.PointerProperty()
    boo1: bpy.props.PointerProperty()

def register(init_version: Any) -> None:
    bpy.types.Object.vrm_props =  bpy.props.PointerProperty(type=VRMProps)

def unregister() -> None:
    del bpy.types.Object.vrm_props
```

**Additional context::なんかほかに書きたいことがあれば**
実際の値自体の保存はまだテキストブロックに書き込む方式で良いと思います。
実際の処理の変更は行わず、プロパティグループとUIパネルだけ追加したものをプルリクで送るつもりです。

**Comment by FujiSunflower** [comment]
プロパティのgetterを使用してUIの一部から設定が出来るようになりました。
![4](https://user-images.githubusercontent.com/20571538/115114294-7aa7eb00-9fc9-11eb-80f1-417ad7951b84.png)

**Comment by saturday06** [comment]
ご提案ありがとうございます。あと、SpringBoneとかVRMの拡張をjsonテキストで保存するのもやめたいんですよね・・・。

GWで時間が取れそうなので、そこで一気にやっちゃおうかなーとは思っています。

**Comment by FujiSunflower** [comment]
コンフリクトしていますが、参考程度にどうぞ #65
