### ISSUE TITLE
Feature request:要望 Automatically fix first person json bone mapping from the skeleton

### ISSUE THREAD

**Issue by fire** [saturday06/VRM-Addon-for-Blender#66]
**Is your feature request related to a problem? Please describe.:バグじゃないけどアドオンの動作でなにか困ってることがあれば**

No manual input is needed to fix first person json bone.

**Describe the solution you'd like:どう動いてほしいかをどうぞ**

1. The validator should check if head bone matches the head bone in the first person json. (Already exists)
1. If the bone does not match, copy the bone from the skeleton bone list to the first person json head attribute

**Describe alternatives you've considered:他にこんなんでもいいよ、というのがあれば**
Doing these steps manually to configure vrm.

**Additional context::なんかほかに書きたいことがあれば**
Trying to reduce the number of actions to configure a vrm.

**Comment by saturday06** [comment]
Thanks for your feature request! The latest release https://github.com/saturday06/VRM_Addon_for_Blender/releases/tag/2_0_5 supports the feature.

Json file is replaced by blender panel ui. When the addon detects that the first person bone doesn't match, The bone is set to head bone automatically.

![image](https://user-images.githubusercontent.com/532872/147126128-4f09ec00-3a06-414c-95ff-9c6eb16c52a5.png)

**Comment by fire** [comment]
Thanks!
