### ISSUE TITLE
Feature request:要望 Save previous skeleton bone mappings and use to pick bones 

### ISSUE THREAD

**Issue by fire** [saturday06/VRM-Addon-for-Blender#67]
**Is your feature request related to a problem? Please describe.:バグじゃないけどアドオンの動作でなにか困ってることがあれば**
It takes too many steps to configure a vrm.

**Describe the solution you'd like:どう動いてほしいかをどうぞ**
If a bone has been picked before, it should be saved in a priority list.

The list should be import/export as json.

The goal is to reduce the number of steps to configure a vrm. The best possible result is zero steps to configure and exporting takes only one step.

Alternatively, we can use a t-pose / a-pose character to pick only one side.

Alternatively, we can use a t-pose / a-pose character and for each area pick three points to wrap around and select the bone.

**Describe alternatives you've considered:他にこんなんでもいいよ、というのがあれば**

We have to do vrm bone configuration manually.

**Additional context::なんかほかに書きたいことがあれば**

See this Blender addon for an example of bone configuration.

https://github.com/fire/skeletal-motion-retarget-blender

**Comment by saturday06** [comment]
Thanks for your feature request. Importing and exporting VRM humanoid bone mappings as json file has been released in v1.15.0.

![image](https://user-images.githubusercontent.com/532872/145664511-75e3ee84-8cc4-4a0e-be8c-5066efa72422.png)
![image](https://user-images.githubusercontent.com/532872/145664591-5daaf2e7-b4d8-4d24-9a46-10229e3254d6.png)

**Comment by fire** [comment]
Thanks, I'll try it and review.
