### ISSUE TITLE
Bug report : バグ報告

### ISSUE THREAD

**Issue by tmatakiti** [saturday06/VRM-Addon-for-Blender#68]
**Describe the bug :バグについて**
Blender2.93でVRMImporterアドオン（1.11.0）を有効にできない

**To Reproduce:バグの再現方法**
Blender2.93でVRMImporterアドオン（1.11.0）をインストール後、チェックが入らないのでチェックを入れる
以下エラー時のログです。（パスは少し削ってます）
---↓ここから---
情報: Updated sidebar tabs
Exception in module register(): Blender Foundation\Blender\2.93\scripts\addons\VRM_Addon_for_Blender-release\__init__.py
Traceback (most recent call last):
  File "Blender Foundation\Blender\2.93\scripts\modules\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "Blender Foundation\Blender\2.93\scripts\modules\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "Blender Foundation\Blender\2.93\scripts\modules\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "Blender Foundation\Blender\2.93\scripts\addons\VRM_Addon_for_Blender-release\__init__.py", line 71, in register
    from . import io_scene_vrm  # type: ignore[attr-defined]
  File "Blender Foundation\Blender\2.93\scripts\addons\VRM_Addon_for_Blender-release\io_scene_vrm\__init__.py", line 13, in <module>
    from . import editor, exporter, importer, shader, version
  File "Blender Foundation\Blender\2.93\scripts\addons\VRM_Addon_for_Blender-release\io_scene_vrm\importer\__init__.py", line 13, in <module>
    from . import blend_model
  File "Blender Foundation\Blender\2.93\scripts\addons\VRM_Addon_for_Blender-release\io_scene_vrm\importer\blend_model.py", line 28, in <module>
    import numpy
  File "Blender Foundation\Blender\2.93\scripts\modules\numpy\__init__.py", line 145, in <module>
    from . import core
  File "Blender Foundation\Blender\2.93\scripts\modules\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE"
  * The NumPy version is: "1.20.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
---↑ここまで---

**Expected behavior:期待する動作**
2.93で使えるよう対応をお願いできればと思います。

**Screenshots:スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。
**Desktop (please complete the following information):PC環境情報**
 - OS: [win10]
 - Blender [2.93.]
 - Addon Version [1.11.0]

**Additional context :なにか他に書いておきたいことはこちらへ**
いつもお世話になっております。頑張ってください～

**Comment by saturday06** [comment]
返信遅くなってすみません、バグ報告ありがとうございます。

私の手元でMicrosoft StoreからインストールしたBlender 2.93.2にアドオンをインストールしてみましたが、エラーが発生せず正常に動作しています。

エラー内容を拝見しましたが、Blenderインストール時に同梱されているはずのファイル `Blender\2.93\python\lib\site-packages\numpy\core\_multiarray_umath.cp39-win_amd64.pyd` が存在しないか壊れているように見えます。

Blender 2.93.0のインストーラーがバグっているか、ウイルス対策ソフトが不正なファイルだとして削除してしまった疑いがあります。そのため、お手数ですが最新版のBlender 2.93.2で再確認をお願いします。

**Comment by tmatakiti** [comment]
お忙しいところご確認と返信ありがとうございます！

>Blender 2.93.0のインストーラーがバグっているか、ウイルス対策ソフトが不正なファイルだとして削除してしまった疑いがあります。そのため、お手数ですが最新版のBlender 2.93.2で再確認をお願いします。

↑インストール済みの環境を一度アンインストールをして2.93.2をインストールしましたが症状は変わらずでした。ウィルス対策をOFFにしてインストールしても変わらずです。また、2.93のインストールフォルダを確認したところPython以下の該当フォルダ内に_multiarray_umath.cp39-win_amd64.pydは存在していました。（ファイルが正常かどうかはわかりませんが…）

>私の手元でMicrosoft StoreからインストールしたBlender 2.93.2にアドオンをインストールしてみましたが、エラーが発生せず正常に動作しています。

問題は解決していませんが、どうやら私のPC環境依存の問題のようなので、いったんクローズします。
ご確認ありがとうございました！

**Comment by saturday06** [comment]
追加情報ありがとうございます。こちらはBlender同梱のnumpyがトラブルを起こしているのは明らかなので、イシューは閉じていただいたのですが対応は続行しようと思います。ひとまずアドオンがnumpyを使わないように改修を行おうと思います。もし首尾よく改修が成功したらまた報告します。

**Comment by tmatakiti** [comment]
返信ありがとうございます。

>ひとまずアドオンがnumpyを使わないように改修を行おうと思います。

お手数をおかけします。気長に待っております。対応よろしくお願いします！

**Comment by saturday06** [comment]
先ほどnumpy削除の対応を行ったアドオンバージョンv1.11.1をリリースしました。お手すきの際に確認いただければと思います。

休日だったのと、当初思ったより対応箇所が少なかったのでやっちゃいました。numpy自体は将来的には使いたい気持ちがあるので、その際はそいつ原因で全体がぶっ壊れないような工夫をしようかと考えています。

**Comment by tmatakiti** [comment]
早速の対応ありがとうございます！

先ほど最新バージョンv1.11.1をダウンロードして私のBlender2.93.2環境で試したところ、アドオンを有効にしようとした時に出ていたエラーも発生せずVRMのインポートもできました！ありがとうございました～！

**Comment by saturday06** [comment]
上手く行ったようで良かったです。ありがとうございます！
