### ISSUE TITLE
Bug report : バグ報告 Import&ExportをするとTransparentWithZWrite→Transparent

### ISSUE THREAD

**Issue by ghost** [saturday06/VRM-Addon-for-Blender#72]
**Describe the bug :バグについて**
VRM_Addon_for_Blender 1.14.1でインポートして、エクスポートをするとTransparentWithZWrite→Transparentになっている

**To Reproduce:バグの再現方法**
UnityのUniVRM0.90を使って Shader VRM/Mtoon Rendering Type TransparentWithZWriteを使ってExportした VRMがあります。
Unityで再度VRMをImportするとTransparentWithZWriteのままで正常に開けます

Blenderの VRM_Addon_for_Blender 1.14.1で開くと Blender上では表示は壊れていないですが
何もせずにExport VRMすると　VRM表示アプリで表示がおかしくなります。

再度それをUnityで取り込んだら Rendering Type "TransparentWithZWrite"ではなく、”Transparent"として保存されています

**Expected behavior:期待する動作**
VRM_Addon_for_Blender 1.14.1で出力した際に"TransparentWithZWrite"で出力したい

**Additional context :なにか他に書いておきたいことはこちらへ**
参考になるかわからないですが、それっぽいURLを送ります
VRM Mtoon
https://vrm-c.github.io/UniVRM/ja/implementation/transparent_zwrite.html

**Comment by saturday06** [comment]
バグ報告ありがとうございます。こちら再現確認しました。大変申し訳ないのですが、TransparentWithZWriteを利用される場合は、修正完了するまではUnity上でマテリアルの設定を行う方式でお願いします。お手数おかけして申し訳ありません。

**Comment by ghost** [comment]
確認ありがとうございます！
修正のほうを楽しみにしてます。
よろしくお願いします

**Comment by lyuma** [comment]
I would also like to vote for this.

The model we tested has clothing with "Alpha Hashed" in Blender, which is supposed to use the depth buffer.

After converting to VRM, the clothing material was Transparent and looked like this:
![image](https://user-images.githubusercontent.com/39946030/158279845-97dc5532-36b2-45c5-a3b4-cf827982a4f3.png)

Ideally, this would become a "Dithered Cutout" shader, but VRM does not have such an option.
So I think Alpha Hashed should either convert to TransparentWithZWrite or Cutout.

I did not test "Alpha Blend", but that should be either Transparent or TransparentWithZWrite. Perhaps it would be good to ask the user.

We also noticed that materials had Cull Off after export, even though they had backface culling enabled in Blender. Backface culling would also reduce the impact of transparency sorting.

**Comment by saturday06** [comment]
完了
- インポートエクスポート時にTransparentWithZWriteがTransparentになるバグ

まだ
- アルファハッシュ設定時にエクスポート時のデフォルトをTransparentWithZWriteにする？
- カリングの設定がエクスポート時に反映されない？

**Comment by ghost** [comment]
saturday06さん　ありがとうございます。
2.3.6バージョンで、
"インポートエクスポート時にTransparentWithZWriteがTransparentになるバグ"　の修正確認ができました
助かりました

**Comment by saturday06** [comment]
遅くなってすみませんでした。確認ありがとうございます！

**Comment by saturday06** [comment]
> アルファハッシュ設定時にエクスポート時のデフォルトをTransparentWithZWriteにする？

こちらは TransparentWithZWrite かどうかを選択ボックスで設定するようにしました。

> カリングの設定がエクスポート時に反映されない？

こちらは修正しました。
