### ISSUE TITLE
Feature request:要望　揺れ物ボーンの設定

### ISSUE THREAD

**Issue by Bancho29** [saturday06/VRM-Addon-for-Blender#73]
初めまして。
このアドオンをよく使わせていただいております。

**Is your feature request related to a problem? Please describe.:バグじゃないけどアドオンの動作でなにか困ってることがあれば**

Vroidで出力したモデルをエクスポートした時の揺れ物ボーンの名前が、文字数制限で修正されるほどの長い名前なので、
（https://twitter.com/d17vrsft/status/1464964781446549506 及び https://twitter.com/m_sigepon/status/1464969144902717446 参照）

リネームして「VRMモデルをチェック」したら、
『spring_boneのボーン名「リネーム前のボーン名」がアーマチュア中に見つかりません。テキストエディタの spring_bone の json を修正してください。』
とエラーが出てきます。

この場合、「spring_bone.json」をテキストエディタで修復するか（ボーンが多いほどその分根気よく修復する必要あり）、「spring_bone.json」をリンク切断しない限り、エクスポート不可能になります。

**Describe the solution you'd like:どう動いてほしいかをどうぞ**

「VRM Armature Helper」で揺れ物ボーンの設定が出来るようにしてほしい。
その際、親ボーンを指定したら子ボーンも同時に設定できるようにしてほしい。
（最近配布された「PmxTailor」のボーン設定（https://www.nicovideo.jp/watch/sm39696512 の05:07以降）の様な感じです）

また、揺れ物を含めたボーン名のリネームも出来るようにしてほしい。

**Comment by saturday06** [comment]
ご要望ありがとうございます。現在、json記載の各種設定をBlenderのUI部品での設定へ置き換える作業をしています。それに伴いリネームなどで発生する問題を解決しようと目論んでおります。ただ、私のプログラミング能力の問題があり時間がかかっております。

ご不便おかけしていますが、お待ちいただけると幸いです。

**Comment by Bancho29** [comment]
ご返答ありがとうございます。

**Comment by saturday06** [comment]
最新リリースで揺れもの含むボーンの設定をBlenderのパネルUIで設定できるようにし、またボーン名の変更があった際に揺れものボーン含むUIに設定されているボーン名も同時に変更されるようにしました。是非アップデートしてお試しください 🙇

**Comment by saturday06** [comment]
@Bancho29 最新リリースで揺れもの含むボーンの設定をBlenderのパネルUIで設定できるようにし、またボーン名の変更があった際に揺れものボーン含むUIに設定されているボーン名も同時に変更されるようにしました。是非アップデートしてお試しください 🙇

**Comment by Bancho29** [comment]
早速確認いたしました。
揺れ物追加もリネーム追随も動作しました。
（3.0にて確認）

ただ、前バージョンにあった「rename Vroid_bones」ボタンが無くなったのは
何気に残念です。

実装ありがとうございました。

**Comment by saturday06** [comment]
確認ありがとうございます。「rename Vroid_bones」ですが、UI組み換えの際に誤って消してしまっていたようです。。。ボーン名を保存する仕様がだいぶ変わったのですぐには復活できないですが、時間ができたら試してみようと思います。

**Comment by Bancho29** [comment]
お待ちしております。

**Comment by saturday06** [comment]
先ほどリリースしたバージョンで「VRoidのボーン名を短くする」という命名で復活させました。VRoidっぽいボーンが存在する場合「VRoidのボーン名を短くする」ボタンが表示されます。

![image](https://user-images.githubusercontent.com/532872/147394975-a241f9b0-cdd3-4fd1-9bd4-fc46b09c3baf.png)

変換結果はこちらになります

![image](https://user-images.githubusercontent.com/532872/147394984-c703bf62-09ca-4c2f-9b43-abd361e797f9.png)

おそらく以前の動作を再現できたと思います。確認ありがとうございました。

**Comment by saturday06** [comment]
左に出てるアイコンがおかしいっすね。。。次のバージョンで直します。。。

**Comment by Bancho29** [comment]
ありがとうございます。
