### ISSUE TITLE
Bug report / バグ報告 textures seems to be missing when exporting

### ISSUE THREAD

**Issue by xfnw** [saturday06/VRM-Addon-for-Blender#85]
**Describe the bug / バグについて**

when exporting as a VRM, the material is missing the texture

**To Reproduce / バグの再現方法**

1. open [this blend file](https://ttm.sh/iwu.blend) in blender
2. export as a VRM
3. observe that the texture is missing in the resulting VRM file

**Desktop (please complete the following information) / PC環境情報**
- OS: Linux
- Blender 3.0.0
- Addon Version 2.1.3

**Additional context / なにか他に書いておきたいことはこちらへ**

this does not happen when exporting as glTF

**Comment by saturday06** [comment]
Thanks for reporting!

Please give me a screenshot of your setup when you did the glTF export. I tried the glTF export on my Ubuntu 20.04 & Blender 3.0.0, but no textures were exported.

<img width="300" src="https://user-images.githubusercontent.com/532872/151422641-1a66be8f-0bb1-4484-a85d-064de767ee14.png">

Here is a screenshot of my settings when I tried the glTF export.

<img height="300" src="https://user-images.githubusercontent.com/532872/151424089-8e28bb14-40e1-4c08-bdf7-8f82a67ec1be.png"> <img height="300" src="https://user-images.githubusercontent.com/532872/151424207-9679d3d5-92a5-4041-bafc-e72e30981e4c.png">

**Comment by xfnw** [comment]
huh it seems to export to VRM with the textures fine when the material is set to Principled BSDF instead of Diffuse BSDF
