### ISSUE TITLE
Bug report / バグ報告: コライダの位置がズレる

### ISSUE THREAD

**Issue by IKAKUNE** [saturday06/VRM-Addon-for-Blender#87]
**Describe the bug / バグについて**
バージョン 2.1.4 にて、colliders 用の empty オブジェクトを bone に配置してあるモデルをブレンダーに読み込むと、colliders の位置がズレてしまう不具合が発生しているようです
ズレるモデルとズレないモデルがあり、どのような違いで不具合が起きたり起きなかったりするのかは不明です
また、バージョン 2 以降のどこかの時点で、モデルをブレンダーに読み込んだ時点では正常に見えても、エクスポートした VRM の colliders の位置が同様にズレる不具合が発生していたようです
(おそらく、同じ不具合が 2.1.4 ではモデルを読み込んだ時に顕現するようになっただけではないかと思います)

**To Reproduce / バグの再現方法**
特定のモデルをブレンダーに読み込む
ちなみに colliders は、球の empty オブジェクトを追加し、ボーンを親としてペアレント設定したものです

**Expected behavior / 期待する動作**
colliders の位置がズレないようにしていただくか、もしくは、
位置がズレないような colliders の設定の仕方を教えていただければと思います

**Screenshots / スクリーンショット**
画像を三枚添付いたします

![1_16_0](https://user-images.githubusercontent.com/20639131/152284005-f3cb8208-2b4a-459c-8488-b4b225a278f8.png)
![2_1_4](https://user-images.githubusercontent.com/20639131/152284029-edf5c246-10cd-41c2-9907-0c6cfe66f2db.png)
![2_1_4_tv](https://user-images.githubusercontent.com/20639131/152284040-049ad700-f337-4428-a020-71e4f06e36be.png)

一枚目がアドオンを削除して読み込み colliders を選択した画像
二枚目と三枚目がアドオンのバージョン 2.1.4 を有効にした状態で読み込み colliders を選択した画像です

**Desktop (please complete the following information) / PC環境情報**
- OS: Windows10
- Blender 3.0.1 (3.0, 2.93 でも確認いたしました)
- Addon Version 2.1.4

**Additional context / なにか他に書いておきたいことはこちらへ**
いつも大変お世話になっております！
原因を特定できていないあやふやな報告で申し訳ありませんが、とり急ぎご報告まで……参考になりましたら幸いです

**Comment by saturday06** [comment]
ご報告ありがとうございます！

すみません、こちらアドオンのバージョン2で物理の設定をjsonからBlenderのPropertyGroupに移行するコードを書いたのですが、そのあたりのコードにバグがありそうです。土日に詳しく調査します 🙇

**Comment by saturday06** [comment]
@IKAKUNE すみません、こちら手元で検証したのですがどうしてもバグを再現できませんでした。

たいへんお手数ですが、調査がしたいためこちらのバグが再現する .blend ファイルを外部に出せないメッシュなどを削除した状態で、私のtwitter (https://twitter.com/saturday06) のDMなどでお送りいただきたいです。(メッシュは削除してもそのままだと.blendファイルに残る恐れがあるので、「ファイル」→「クリーンアップ」→「未使用データブロックを再帰」で完全に消せます)

すみませんが、ご検討お願いします 🙇

**Comment by saturday06** [comment]
こちらの方にも同様の依頼をさせていただきました。（おそらく関係者の方だと推察します）

https://twitter.com/saturday06/status/1497846503016378369?s=20&t=5GGSCS06f4MqYFwpo7xCVg

**Comment by IKAKUNE** [comment]
お手数おかけいたしております。
ツイッターのDMにてファイルを送らせていただきました。
VRM_Addon_for_Blender の 2.1.4 にてファイルを開くと、コライダがズレるかと思います。

ただ、このコライダですが、私が自作スクリプトにて追加したものですので、ひょっとしたらそれが原因なのかもしれません。
以下のようなスクリプトです。

```
# Add Empty
empty_obj = bpy.data.objects.new('Collider_a_a', None)
bpy.context.scene.collection.objects.link(empty_obj)

# Parent to bone
empty_obj.parent = parent_obj
empty_obj.parent_type = "BONE"
empty_obj.parent_bone = bone_name

# Move to ypos
empty_obj.location = Vector([0.0, -ypos, 0.0])

# Set parameters
empty_obj.empty_display_type = 'SPHERE'
empty_obj.empty_display_size = collider_size
```

もしも上記のスクリプトが原因でしたら、大変申し訳ありません。。。

**Comment by saturday06** [comment]
ありがとうございます！頂いたデータで検証したところ、報告いただいたバージョン(2.1.4)でバグの発生を確認できました。こちら最新版(2.1.13)で試したところコライダーは正しそうな位置になってバグは修正済されたようなので、バージョンアップして再度ご確認お願いします！

2.1系のパッチバージョンで細かいデータ関連の修正を行ったので、このうちの一つが運よくこのバグの原因を取り除いたものだと思われます。

ご報告ありがとうございました！

コライダーを追加するスクリプトは書いていただいたもので問題無かった想定です。ただ、2系のアドオンだとこれに加えてArmatureのプロパティに登録しないといけないため、ちょっとどうしようか検討中です。。。

**Comment by IKAKUNE** [comment]
こちらでも 2.1.13 での読み込み、およびエクスポートを試し、直っていることを確認いたしました！
ご対応ありがとうございました！！

VRM は設定すべき項目がたくさんあり、VroidStudio や Unity 由来の都合もあったりして、ご対応は大変かと思います。
微力でもお力になれるといいのですが。。。
