### ISSUE TITLE
Can't export due to error. mesh :Face.baked is not found. Please fix setting in textblock : blendshape_group

### ISSUE THREAD

**Issue by Silver0006** [saturday06/VRM-Addon-for-Blender#9]
Im on windows 10 running blender 2.9 I needed to edit a vrm model so I decided to use blender. I keep running into this error and was wondering if you could help. 
mesh :Face.baked is not found. Please fix setting in textblock : blendshape_group
As far as I can tell everything else is fine.
Thank you for your time.

**Comment by iCyP** [comment]
![コメント 2020-09-08 214229](https://user-images.githubusercontent.com/3232308/92477852-4773d100-f21c-11ea-8c27-2641635a7fd2.png)
Please like above image.
1.  Open texteditor in blender
2. Select ***_blendshape_group.json in texts (replace *** to your model name)
3. Replace all "Face.baked" in text to your new mesh name of face that belong shapekeys. ( Don't remove double quotation)
4. (If you change shapekey name in editing model, you have to change shapekey name to new shapekey name in same text )  

Sorry about my cheap English.
 Thanks.

ps. if you mod bones, you may need edit other texts like this.

**Comment by Silver0006** [comment]
Thank you.
